import json,sys; sys.path.insert(0,'.'); sys.path.insert(0,'/home/claude/build')
from common import *
from oia_thoracic import OIA as OT
from oia_pelvic import OIA as OP
L8=["Brachiocephalicus","Omotransversarius","Trapezius","Rhomboideus","Serratus ventralis","Latissimus dorsi","Sternocephalicus","Sternohyoideus","Sternothyroideus","Superficial pectoral","Deep pectoral"]
M=[]
for k,(o,i,a) in OT.items():
    if k=='Brachioradialis': continue
    M.append(dict(n=k,o=o,i=i,a=a,r='Thoracic limb · extrinsic/neck' if k in L8 else 'Thoracic limb · intrinsic'))
for k,(o,i,a) in OP.items(): M.append(dict(n=k,o=o,i=i,a=a,r='Pelvic limb'))
LM=[("Greater tubercle (insertion)",["Supraspinatus","Infraspinatus"],"T"),("Lesser tubercle or its crest (insertion)",["Subscapularis","Coracobrachialis"],"T"),("Teres major tuberosity (insertion)",["Teres major","Latissimus dorsi"],"T"),("Deltoid tuberosity (insertion)",["Deltoideus"],"T"),("Tuber olecrani (insertion)",["Triceps brachii","Tensor fasciae antebrachii","Anconeus"],"T"),("Accessory carpal bone (insertion)",["Flexor carpi ulnaris","Ulnaris lateralis"],"T"),("Lateral epicondyle of humerus (origin)",["Extensor carpi radialis","Common digital extensor","Lateral digital extensor","Ulnaris lateralis","Supinator"],"T"),("Medial epicondyle of humerus (origin)",["Pronator teres","Flexor carpi radialis","Superficial digital flexor","Flexor carpi ulnaris","Deep digital flexor"],"T"),("Supraglenoid tubercle (origin)",["Biceps brachii"],"T"),("Serrated face of scapula (insertion)",["Serratus ventralis"],"T"),("Spine of scapula (insertion)",["Trapezius","Omotransversarius"],"T"),("Dorsal border of scapula (insertion)",["Rhomboideus"],"T"),("Middle phalanges, thoracic limb (insertion)",["Superficial digital flexor"],"T"),("Distal phalanges, flexor tubercles (insertion)",["Deep digital flexor"],"T"),("Greater trochanter (insertion)",["Middle gluteal","Piriformis","Deep gluteal"],"P"),("Third trochanter (insertion)",["Superficial gluteal"],"P"),("Trochanteric fossa (insertion)",["Internal obturator","External obturator","Gemelli"],"P"),("Lesser trochanter (insertion)",["Iliopsoas"],"P"),("Ischiatic tuberosity (origin)",["Biceps femoris","Semitendinosus","Semimembranosus"],"P"),("Tuber calcanei (insertion)",["Gastrocnemius","Superficial digital flexor","Biceps femoris","Semitendinosus"],"P"),("Tibial tuberosity (insertion, via patellar lig.)",["Quadriceps femoris"],"P"),("Extensor fossa of femur (origin)",["Long digital extensor"],"P"),("Pelvic symphysis (origin)",["Gracilis"],"P"),("Tuber coxae (origin)",["Tensor fasciae latae"],"P"),("Sacrotuberous ligament (origin)",["Superficial gluteal"],"P")]
# stick figure items: joints list with correct action
STICK=[
("Supraspinatus","T",("S",0.35,14.0),("H",0.08,12.0),{"shoulder":"extend"}),
("Deltoideus","T",("S",0.55,-6.0),("H",0.35,-10.0),{"shoulder":"flex"}),
("Teres major","T",("S",0.25,-14.0),("H",0.3,-12.0),{"shoulder":"flex"}),
("Biceps brachii","T",("S",0.95,14.0),("A",0.1,10.0),{"shoulder":"extend","elbow":"flex"}),
("Brachialis","T",("H",0.3,-8.0),("A",0.12,10.0),{"elbow":"flex"}),
("Triceps brachii, long head","T",("S",0.55,-16.0),("A",-0.08,14),{"shoulder":"flex","elbow":"extend"}),
("Triceps brachii, lateral head","T",("H",0.25,-12.0),("A",-0.08,14),{"elbow":"extend"}),
("Extensor carpi radialis","T",("H",0.9,8.0),("M",0.15,8.0),{"carpus":"extend"}),
("Common digital extensor","T",("H",0.92,6.0),("D",0.8,6.0),{"carpus":"extend","digits":"extend"}),
("Ulnaris lateralis","T",("H",0.92,-10.0),("M",0.02,-14.0),{"carpus":"flex"}),
("Flexor carpi ulnaris","T",("A",0.02,-16.0),("M",0.02,-16.0),{"carpus":"flex"}),
("Superficial digital flexor (thoracic)","T",("H",0.95,-12.0),("D",0.5,-8.0),{"carpus":"flex","digits":"flex"}),
("Middle gluteal","P",("S",0.3,4.0),("H",0.02,14.0),{"hip":"extend"}),
("Iliopsoas","P",("S",0.2,16.0),("H",0.12,10.0),{"hip":"flex"}),
("Rectus femoris (quadriceps)","P",("S",0.55,14.0),("A",0.06,12.0),{"hip":"flex","stifle":"extend"}),
("Vastus lateralis (quadriceps)","P",("H",0.2,10.0),("A",0.06,12.0),{"stifle":"extend"}),
("Biceps femoris","P",("X",1,-0.0),("A",0.95,-14.0),{"hip":"extend","tarsus":"extend"}),
("Gastrocnemius","P",("H",0.9,-12.0),("A",1.06,-14.0),{"stifle":"flex","tarsus":"extend"}),
("Cranial tibial","P",("A",0.12,10.0),("M",0.15,8.0),{"tarsus":"flex"}),
("Long digital extensor","P",("H",0.95,10.0),("D",0.8,6.0),{"stifle":"extend","tarsus":"flex","digits":"extend"}),
("Superficial digital flexor (pelvic)","P",("H",0.9,-14.0),("D",0.5,-8.0),{"stifle":"flex","tarsus":"extend","digits":"flex"}),
("Deep digital flexor (pelvic)","P",("A",0.3,-12.0),("D",0.9,-8.0),{"tarsus":"extend","digits":"flex"})]
body='''<div class="tabs"><button class="on" data-t="o1">🦴 Action predictor</button><button data-t="o2">🕵️ Who am I?</button><button data-t="o3">📍 Attachment map</button><button data-t="o4">🔗 Match-up</button></div>
<div id="o1" class="panel on"><h2>🦴 Stick-figure action predictor</h2><p class="hint">The pink line is the muscle (● origin → ◆ insertion). Cranial = LEFT. For every joint it crosses, choose flex or extend, then watch it move. Flexor surfaces: thoracic = caudal shoulder · cranial elbow · palmar carpus/digits · pelvic = cranial hip · caudal stifle · dorsal tarsus · plantar digits.</p><div class="q" id="sname"></div><svg id="fig" viewBox="0 0 320 480" style="max-width:360px;margin:auto"></svg><div id="joints"></div><div class="fb" id="ofb"></div><div class="row"><button class="btn hot" id="onext">Next muscle ▶</button><span class="score" id="oscore"></span></div></div>
<div id="o2" class="panel"><h2>🕵️ Who am I?</h2><p class="hint">Clues reveal one at a time. Guess early for more points (3 → 2 → 1).</p><select id="wreg"><option value="">All regions</option><option>Thoracic limb · intrinsic</option><option>Thoracic limb · extrinsic/neck</option><option>Pelvic limb</option></select><div id="clues" style="margin:10px 0"></div><div class="grid" id="wopts"></div><div class="fb" id="wfb"></div><div class="row"><button class="btn" id="wclue">💡 Next clue</button><button class="btn hot" id="wnext">New muscle ▶</button><span class="score" id="wscore"></span></div></div>
<div id="o3" class="panel"><h2>📍 Attachment map</h2><p class="hint">Select EVERY muscle that attaches here, then Check.</p><div class="q" id="lq"></div><div class="grid" id="lopts"></div><div class="fb" id="lfb"></div><div class="row"><button class="btn hot" id="lcheck">Check ✓</button><button class="btn" id="lnext">Next ▶</button><span class="score" id="lscore"></span></div></div>
<div id="o4" class="panel"><h2>🔗 Match-up</h2><p class="hint">Tap a muscle, then tap its match. Three rounds per set: insertions → origins → actions.</p><select id="mreg"><option>Thoracic limb · intrinsic</option><option>Thoracic limb · extrinsic/neck</option><option>Pelvic limb</option></select><div class="q" id="mq"></div><div style="display:grid;grid-template-columns:1fr 1.4fr;gap:8px"><div id="mleft" style="display:grid;gap:8px"></div><div id="mright" style="display:grid;gap:8px"></div></div><div class="fb" id="mfb"></div><div class="row"><button class="btn hot" id="mnew">New set ▶</button><span class="score" id="mscore"></span></div></div>'''
js=TABJS+f'const M={json.dumps(M)},LM={json.dumps(LM)},ST={json.dumps(STICK)};'+r'''
tabs();
// ---- stick figure
const FIG={T:{base:[200,40],segs:[["S",125,115],["H",115,65],["A",125,88],["M",55,82],["D",45,158]],joints:{shoulder:1,elbow:2,carpus:3,digits:4},flex:{shoulder:-28,elbow:38,carpus:-40,digits:-35},names:["scapula","humerus","radius/ulna","metacarpus","digit"]},
P:{base:[120,70],segs:[["S",70,40],["H",120,105],["A",125,62],["M",100,95],["D",45,152]],joints:{hip:1,stifle:2,tarsus:3,digits:4},flex:{hip:28,stifle:-32,tarsus:32,digits:-35},names:["pelvis","femur","tibia","metatarsus","digit"],ischium:[222,108]}};
let cur=null,rot={},oi=0,osc=0,ost=0,order=sh(ST.map((_,i)=>i));
function pts(f){let p=[f.base.slice()],ang=0,out=[];f.segs.forEach((s,k)=>{let a=s[2];let jn=Object.keys(f.joints).find(j=>f.joints[j]===k);let r=(jn&&rot[jn])||0;ang+=r;let A=(a+ang)*Math.PI/180;let q=p[k];p.push([q[0]+Math.cos(A)*s[1],q[1]+Math.sin(A)*s[1]]);out.push({a:A})});return {p,seg:out}}
function att(f,P,[seg,t,off]){if(seg==='X')return f.ischium;let k=f.segs.findIndex(s=>s[0]===seg);let a=P.seg[k].a,p0=P.p[k],L=f.segs[k][1];return [p0[0]+Math.cos(a)*L*t-Math.sin(a)*off,p0[1]+Math.sin(a)*L*t+Math.cos(a)*off]}
function drawFig(){let [n,lim,o,i,acts]=cur;let f=FIG[lim],P=pts(f),h='';P.p.forEach((q,k)=>{if(k<P.p.length-1){let r=P.p[k+1];h+=`<line x1="${q[0]}" y1="${q[1]}" x2="${r[0]}" y2="${r[1]}" stroke="#e8dcc8" stroke-width="16" stroke-linecap="round"/><line x1="${q[0]}" y1="${q[1]}" x2="${r[0]}" y2="${r[1]}" stroke="#c9b28f" stroke-width="3"/>`}});
if(lim==='P')h+=`<line x1="${P.p[1][0]}" y1="${P.p[1][1]}" x2="${f.ischium[0]}" y2="${f.ischium[1]}" stroke="#e8dcc8" stroke-width="14" stroke-linecap="round"/>`;
Object.entries(f.joints).forEach(([j,k])=>{let q=P.p[k];h+=`<circle cx="${q[0]}" cy="${q[1]}" r="7" fill="#fff" stroke="#7b42a0" stroke-width="3"/><text x="${q[0]+12}" y="${q[1]+4}" font-size="12" font-weight="800" fill="#7b42a0">${j}</text>`});
let a=att(f,P,o),b=att(f,P,i);h+=`<line x1="${a[0]}" y1="${a[1]}" x2="${b[0]}" y2="${b[1]}" stroke="#e05fa8" stroke-width="6" stroke-linecap="round" opacity=".85"/><circle cx="${a[0]}" cy="${a[1]}" r="6" fill="#e05fa8"/><rect x="${b[0]-5}" y="${b[1]-5}" width="10" height="10" fill="#6a3392" transform="rotate(45 ${b[0]} ${b[1]})"/>`;
h+=`<text x="6" y="470" font-size="12" fill="#8a6b99" font-weight="800">◀ CRANIAL</text><text x="240" y="470" font-size="12" fill="#8a6b99" font-weight="800">CAUDAL ▶</text>`;$('#fig').innerHTML=h}
function anim(j,deg){let s=rot[j]||0,t0=null;function step(ts){if(!t0)t0=ts;let k=Math.min(1,(ts-t0)/600);rot[j]=s+(deg-s)*k;drawFig();if(k<1)requestAnimationFrame(step)}requestAnimationFrame(step)}
function oShow(){cur=ST[order[oi%order.length]];rot={};$('#sname').textContent=cur[0];$('#ofb').className='fb';let J=$('#joints');J.innerHTML='';let f=FIG[cur[1]];Object.entries(cur[4]).forEach(([j,ans])=>{let r=el('div','row');r.appendChild(el('b','',j.toUpperCase()+':'));['flex','extend'].forEach(v=>{let c=el('button','chip',v==='flex'?'Flex':'Extend');c.style.minWidth='110px';c.onclick=()=>{if(r.dataset.done)return;r.dataset.done=1;ost++;let ok=v===ans;if(ok)osc++;c.classList.add(ok?'ok':'bad');if(!ok)[...r.querySelectorAll('.chip')].forEach(x=>{if(x.textContent.toLowerCase()===ans)x.classList.add('ok')});anim(j,ans==='flex'?f.flex[j]:-f.flex[j]*0.6);$('#oscore').textContent=`${osc}/${ost}`;if([...J.children].every(x=>x.dataset.done)){let m=M.find(x=>cur[0].toLowerCase().startsWith(x.n.toLowerCase().split(' (')[0].toLowerCase())||x.n.toLowerCase()===cur[0].toLowerCase());$('#ofb').className='fb show';$('#ofb').innerHTML='<b>'+cur[0]+'</b>: '+Object.entries(cur[4]).map(([k,v])=>`${v}s the ${k}`).join(' · ')+(m?`<br><small>OIA doc: ${m.a}</small>`:'')}};r.appendChild(c)});J.appendChild(r)});drawFig()}
$('#onext').onclick=()=>{oi++;oShow()};oShow();
// ---- who am I
let wc=null,wk=0,wsc=0,wn=0,wdone=false;
function wNew(){let reg=$('#wreg').value;let pool=M.filter(m=>!reg||m.r===reg);wc=pool[Math.floor(Math.random()*pool.length)];wk=0;wdone=false;$('#wfb').className='fb';$('#clues').innerHTML='';let opts=sh([wc,...sh(pool.filter(m=>m!==wc)).slice(0,5)]);let o=$('#wopts');o.innerHTML='';opts.forEach(m=>{let c=el('button','chip',m.n);c.onclick=()=>{if(wdone)return;wdone=true;wn++;let ok=m===wc;let pts=ok?Math.max(1,3-wk+1):0;wsc+=pts;c.classList.add(ok?'ok':'bad');[...o.children].forEach(x=>{if(x.textContent===wc.n)x.classList.add('ok')});$('#wfb').className='fb show';$('#wfb').innerHTML=(ok?`✅ +${pts} pts. `:'❌ ')+`<b>${wc.n}</b><br>O: ${wc.o}<br>I: ${wc.i}<br>A: ${wc.a}`;$('#wscore').textContent=`${wsc} pts · ${wn} muscles`};o.appendChild(c)});wClue()}
function wClue(){if(wdone||wk>=3)return;let c=[['🎯 Insertion',wc.i],['📍 Origin',wc.o],['💪 Action',wc.a]][wk];$('#clues').appendChild(el('div','fb show',`<b>${c[0]}:</b> ${c[1]}`));wk++}
$('#wclue').onclick=wClue;$('#wnext').onclick=wNew;$('#wreg').onchange=wNew;wNew();
// ---- attachment map
let lorder=sh(LM),lk=0,lsc=0,lt=0,lchk=false;
function lShow(){lchk=false;let [name,ans,lim]=lorder[lk];$('#lq').textContent=name;$('#lfb').className='fb';let pool=M.filter(m=>(lim==='T'?m.r.startsWith('Thoracic'):m.r==='Pelvic limb')).map(m=>m.n);let d=sh(pool.filter(n=>!ans.includes(n))).slice(0,Math.max(4,8-ans.length));let o=$('#lopts');o.innerHTML='';sh([...ans,...d]).forEach(n=>{let c=el('button','chip',n);c.onclick=()=>{if(!lchk)c.classList.toggle('sel')};o.appendChild(c)})}
$('#lcheck').onclick=()=>{if(lchk)return;lchk=true;let ans=lorder[lk][1],all=true;[...$('#lopts').children].forEach(c=>{let s=c.classList.contains('sel'),r=ans.includes(c.textContent);if(r)c.classList.add('ok');else if(s)c.classList.add('bad');else c.classList.add('dim');if(s!==r)all=false});lt++;if(all)lsc++;$('#lfb').className='fb show';$('#lfb').innerHTML=(all?'✅ Perfect: ':'❌ Answer: ')+ans.join(' · ');$('#lscore').textContent=`${lsc}/${lt}`};
$('#lnext').onclick=()=>{lk=(lk+1)%lorder.length;if(!lk)lorder=sh(LM);lShow()};lShow();
// ---- match-up
let mset=[],mround=0,mpick=null,mok=0,mt=0;const RN=[['i','🎯 Insertions'],['o','📍 Origins'],['a','💪 Actions']];
function mNew(){let reg=$('#mreg').value;mset=sh(M.filter(m=>m.r===reg)).slice(0,4);mround=0;mRound()}
function mRound(){if(mround>2){$('#mq').textContent='🎉 Set complete!';$('#mleft').innerHTML='';$('#mright').innerHTML='';return}let [key,lab]=RN[mround];$('#mq').textContent=`Round ${mround+1}/3: ${lab}`;$('#mfb').className='fb';let L=$('#mleft'),R=$('#mright');L.innerHTML='';R.innerHTML='';mpick=null;let left=0;mset.forEach(m=>{let c=el('button','chip',m.n);c.onclick=()=>{if(c.disabled)return;[...L.children].forEach(x=>x.classList.remove('sel'));c.classList.add('sel');mpick=[c,m]};L.appendChild(c)});sh(mset).forEach(m=>{let c=el('button','chip',m[key]);c.style.fontSize='13.5px';c.onclick=()=>{if(!mpick||c.disabled)return;mt++;let [pc,pm]=mpick;if(pm===m){mok++;pc.classList.remove('sel');pc.classList.add('ok');c.classList.add('ok');pc.disabled=c.disabled=true;left++;if(left===mset.length){mround++;setTimeout(mRound,700)}}else{c.classList.add('shake','bad');setTimeout(()=>c.classList.remove('shake','bad'),400);$('#mfb').className='fb show';$('#mfb').innerHTML='❌ Not '+pm.n+"'s. Try again."}mpick=null;$('#mscore').textContent=`${mok}/${mt}`};R.appendChild(c)})}
$('#mnew').onclick=mNew;$('#mreg').onchange=mNew;mNew();'''
open('/home/claude/games/gross-anatomy-games-oia.html','w').write(page('💪 O/I/A games','Predict actions, guess the muscle, map attachments, match O/I/A',body,js))
print(len(M))
