import json,sys; sys.path.insert(0,'.')
from common import *
B=json.load(open('blocks.json'))
body='''<div class="tabs"><button class="on" data-t="p1">⏱️ Practical simulator</button><button data-t="p2">🔁 Misses mode</button></div>
<div id="p1" class="panel on"><h2>⏱️ Practical simulator</h2><p class="hint">Pick decks, set the station time, and go. Say or write your answer before time runs out. At the end you get a score + your misses (saved for Misses mode).</p>
<div id="picker" class="grid"></div><div class="row"><label><b>Seconds per station:</b> <select id="secs"><option>30</option><option>45</option><option selected>60</option><option>90</option></select></label><label><b>Max stations:</b> <select id="maxn"><option>10</option><option selected>20</option><option>30</option><option value="999">All</option></select></label><button class="btn hot" id="go">▶ Start</button></div>
<div id="stage" style="display:none"><div class="row" style="margin-top:0"><b id="snum"></b><span class="score" id="timer" style="font-size:24px"></span></div><div class="q" id="sq"></div><div style="background:#f7f0fb;border-radius:14px"><img id="simg" style="display:block;max-width:100%;max-height:60vh;margin:auto;border-radius:14px"></div><div class="fb" id="sans"></div><div class="row"><button class="btn hot" id="srev">Reveal</button><button class="btn" id="sgot" style="display:none;background:#e7f6ec;color:#155d33">✓ Got it</button><button class="btn" id="smiss" style="display:none;background:#fde7f0;color:#8e1041">✗ Missed</button></div></div>
<div id="end" class="fb"></div></div>
<div id="p2" class="panel"><h2>🔁 Misses mode</h2><p class="hint">Every card you miss is saved on this device. Get it right <b>twice in a row</b> to clear it.</p><div class="row" style="margin-top:0"><b id="mcount"></b><button class="btn hot" id="mgo">▶ Drill my misses</button><button class="btn" id="mclear">🗑️ Clear all</button></div><div id="mstage" style="display:none"><div class="q" id="mq"></div><div style="background:#f7f0fb;border-radius:14px"><img id="mimg" style="display:block;max-width:100%;max-height:60vh;margin:auto;border-radius:14px"></div><div class="fb" id="mans"></div><div class="row"><button class="btn hot" id="mrev">Reveal</button><button class="btn" id="mgot" style="display:none;background:#e7f6ec;color:#155d33">✓ Got it</button><button class="btn" id="mmiss" style="display:none;background:#fde7f0;color:#8e1041">✗ Missed</button></div></div><div class="fb" id="mend"></div></div>'''
js=TABJS+f'const B={json.dumps(B)};'+r'''
tabs();
const LS={get(){try{return JSON.parse(localStorage.getItem('pracMisses')||'[]')}catch(e){return[]}},set(v){try{localStorage.setItem('pracMisses',JSON.stringify(v))}catch(e){}}};
let lab=null;const P=$('#picker');[...new Set(B.map(b=>b[0]))].forEach(n=>{P.appendChild(el('div','',`<b style="color:#6a3392">Lab ${n}</b>`)).style.gridColumn='1/-1';B.filter(b=>b[0]===n).forEach(b=>{let c=el('button','chip',b[2]);c.dataset.f=b[1];c.onclick=()=>c.classList.toggle('sel');if(b[2].startsWith('⭐'))c.classList.add('sel');P.appendChild(c)})});
async function load(files){let out=[];for(const f of files){try{let t=await (await fetch(f+'?v='+Date.now())).text();let d=new DOMParser().parseFromString(t,'text/html');d.querySelectorAll('section.card').forEach((s,i)=>{let q=s.querySelector('.q');let qt=q?q.childNodes[0].textContent.trim():'Identify the structure.';let im=s.querySelector('.pic img');let a=s.querySelector('.an');if(!im||!a)return;let ai=a.querySelector('img');let name=[...a.childNodes].filter(n=>!(n.nodeName==='IMG')).map(n=>n.textContent).join(' ').trim();let more=[...s.querySelectorAll('.stg')].slice(1).map(g=>'<div><b>'+g.querySelector('.pr').textContent+'</b> '+g.querySelector('.an').textContent+'</div>').join('');out.push({f,i,q:qt,img:new URL(im.getAttribute('src'),location.href).href,ans:name,aimg:ai?new URL(ai.getAttribute('src'),location.href).href:'',more})})}catch(e){}}return out}
let deck=[],k=0,got=0,tm=null,left=0,missed=[];
function tick(){left--;$('#timer').textContent='⏱ '+left;if(left<=0){clearInterval(tm);reveal()}}
function showS(){let c=deck[k];$('#snum').textContent=`Station ${k+1} / ${deck.length}`;$('#sq').textContent=c.q;$('#simg').src=c.img;$('#sans').className='fb';$('#srev').style.display='';$('#sgot').style.display=$('#smiss').style.display='none';left=+$('#secs').value;$('#timer').textContent='⏱ '+left;clearInterval(tm);tm=setInterval(tick,1000)}
function reveal(){clearInterval(tm);let c=deck[k];$('#sans').className='fb show';$('#sans').innerHTML='<div style="font-size:20px">'+c.ans+'</div>'+c.more+(c.aimg?'<img src="'+c.aimg+'" style="max-width:100%;border-radius:12px;margin-top:8px">':'');$('#srev').style.display='none';$('#sgot').style.display=$('#smiss').style.display=''}
function nextS(ok){let c=deck[k];if(ok)got++;else{missed.push(c);let m=LS.get();if(!m.find(x=>x.img===c.img))m.push({...c,streak:0});LS.set(m)}k++;if(k<deck.length)showS();else{$('#stage').style.display='none';$('#end').className='fb show';$('#end').innerHTML=`<div style="font-size:22px">🏁 Score: ${got}/${deck.length} (${Math.round(100*got/deck.length)}%)</div>`+(missed.length?'<b>Missed (saved to Misses mode):</b><br>'+missed.map(x=>'• '+x.ans).join('<br>'):'🎉 No misses!');updM()}}
$('#go').onclick=async()=>{let files=[...P.querySelectorAll('.chip.sel')].map(c=>c.dataset.f);if(!files.length){alert('Pick at least one deck');return}$('#go').textContent='Loading…';let all=await load(files);$('#go').textContent='▶ Start';deck=sh(all).slice(0,+$('#maxn').value);k=0;got=0;missed=[];$('#end').className='fb';if(!deck.length){alert('No cards found');return}$('#stage').style.display='';showS()};
$('#srev').onclick=reveal;$('#sgot').onclick=()=>nextS(true);$('#smiss').onclick=()=>nextS(false);
// misses mode
let mq=[],mk=0;function updM(){$('#mcount').textContent=`${LS.get().length} saved misses`}updM();
function mShow(){if(mk>=mq.length){$('#mstage').style.display='none';$('#mend').className='fb show';$('#mend').innerHTML=`Round done. ${LS.get().length} misses left.`;updM();return}let c=mq[mk];$('#mq').textContent=c.q+`  (streak ${c.streak||0}/2)`;$('#mimg').src=c.img;$('#mans').className='fb';$('#mrev').style.display='';$('#mgot').style.display=$('#mmiss').style.display='none'}
$('#mgo').onclick=()=>{mq=sh(LS.get());mk=0;$('#mend').className='fb';if(!mq.length){$('#mend').className='fb show';$('#mend').textContent='No misses saved yet. Run the simulator first!';return}$('#mstage').style.display='';mShow()};
$('#mrev').onclick=()=>{let c=mq[mk];$('#mans').className='fb show';$('#mans').innerHTML='<div style="font-size:20px">'+c.ans+'</div>'+(c.more||'')+(c.aimg?'<img src="'+c.aimg+'" style="max-width:100%;border-radius:12px;margin-top:8px">':'');$('#mrev').style.display='none';$('#mgot').style.display=$('#mmiss').style.display=''};
function mRes(ok){let m=LS.get(),c=mq[mk],x=m.find(y=>y.img===c.img);if(x){x.streak=ok?(x.streak||0)+1:0;if(x.streak>=2)m=m.filter(y=>y!==x)}LS.set(m);mk++;updM();mShow()}
$('#mgot').onclick=()=>mRes(true);$('#mmiss').onclick=()=>mRes(false);$('#mclear').onclick=()=>{if(confirm('Clear all saved misses?')){LS.set([]);updM()}};'''
open('gross-anatomy-games-practical.html','w').write(page('⏱️ Practical simulator','Timed stations from your decks + a misses list that follows you',body,js))
# hub
hub='''<div class="panel on" style="margin-top:12px"><h2>Which one should I use?</h2><div class="grid" style="grid-template-columns:1fr">
<a class="chip" style="text-decoration:none" href="gross-anatomy-games-practical.html">⏱️ <b>Practical simulator + 🔁 Misses mode</b><br><small>Use DAILY for Thursday. Timed stations from your photo decks; misses get re-served until you nail them twice.</small></a>
<a class="chip" style="text-decoration:none" href="gross-anatomy-games-oia.html">💪 <b>O/I/A games</b><br><small>🦴 Action predictor first (actions = practical + lecture) · 📍 Attachment map for integration Qs · 🕵️ Who am I + 🔗 Match-up for origins/insertions.</small></a>
<a class="chip" style="text-decoration:none" href="gross-anatomy-games-thorax.html">🫁 <b>Thorax games</b><br><small>🗂️ Space vs Structure + 🧱 Layer Stacker for your weak spot (pleura/mediastinum/pericardium) · 💉 Needle game + 🚪 Diaphragm doors for clinical + sequence Qs.</small></a></div></div>'''
open('gross-anatomy-games.html','w').write(page('🎮 Study games','Gross Anatomy I · Exam 2 + Practical 2',hub,'','gross-anatomy.html'))
print(len(B))
