import sys; sys.path.insert(0,'.')
from deck import *; from oia_pelvic import OIA
L11=["Biceps femoris","Semitendinosus","Semimembranosus","Sartorius","Gracilis","Pectineus","Adductor","Tensor fasciae latae","Superficial gluteal","Middle gluteal","Piriformis","Deep gluteal","Internal obturator","Gemelli","Quadratus femoris","External obturator"]
O={k:OIA[k] for k in L11}
D='/home/claude/l11/'
def mk(tag,key,qq,name,clue='',src='q',m=None):
    save_img(D+f'{key}q.jpg',f'site/assets/lab11_{key}q.jpg',1600); save_img(D+f'{key}a.jpg',f'site/assets/lab11_{key}a.jpg',2000)
    return img_card2(qq,f'assets/lab11_{key}q.jpg',name,clue,f'assets/lab11_{key}a.jpg',find_muscles(name,O) if m is None else m,O,tag)
Y='📷 your photo'
yc={'A':mk(Y,'A','Identify the highlighted structure.','Fascia lata (blue)','Deep fascia of the lateral thigh; TFL inserts into it'),
'B':mk(Y,'B','Identify the highlighted muscle.','Biceps femoris (pink)'),
'C':mk(Y,'C','Identify every highlighted structure.','Fascia lata (blue) · tensor fasciae latae · biceps femoris (pink)'),
'D':mk(Y,'D','Identify the structure being palpated.','Popliteal lymph node','Caudal border of biceps femoris, directly caudal to the stifle, covered by fat'),
'P1':mk(Y,'P1','Identify the highlighted muscle and its parts.','Sartorius: a = cranial part · b = caudal part','Dog only: 2 parts'),
'P2':mk(Y,'P2','Identify every highlighted muscle.','Gracilis · pectineus'),
'P3':mk(Y,'P3','Identify every highlighted muscle.','Semimembranosus · adductor'),
'Q1':mk(Y,'Q1','Identify the space and the 3 structures in it (caudal → cranial).','Femoral triangle: femoral vein · femoral artery · saphenous nerve ("VAN" caudal → cranial)','Vessels/nerve are not bold; the femoral triangle is',m=[]),
'Q3':mk(Y,'Q3','Identify every highlighted muscle.','External obturator · adductor'),
'Q4':mk(Y,'Q4','Identify the indicated structure.','Sacrotuberous ligament','Collagenous band, sacrum → lateral angle of the ischiatic tuberosity; superficial gluteal arises from its proximal half'),
'R1':mk(Y,'R1','Identify the muscle, its tendon, and the nerve.','Internal obturator m. + internal obturator tendon · sciatic nerve','Sacrotuberous ligament is cut to expose the tendon over the lesser ischiatic notch')}
S='📚 course slide · Lab 11 Dissection Images'
sl={2:('Identify each labeled fascia.','Fascia regions (see labeled slide)',[]),4:('Identify the highlighted muscle.','Biceps femoris',None),6:('Identify the highlighted muscle.','Semitendinosus',None),8:('Identify the highlighted muscle.','Semimembranosus',None),10:('Identify the highlighted structure.','Popliteal lymph node',None),12:('Identify the highlighted muscle.','Sartorius',None),13:('Identify each part.','Sartorius: cranial part · caudal part',None),15:('Identify the highlighted muscle.','Gracilis',None),17:('Identify the highlighted structure.','Symphysial tendon','[]'),19:('Identify the highlighted space.','Femoral triangle',[]),21:('Identify the highlighted muscle.','Pectineus',None),23:('Identify the highlighted muscle.','Adductor',None),24:('Identify each color.','Adductor (green) · external obturator (blue) · semimembranosus (orange)',None),26:('Identify the highlighted muscle.','Tensor fasciae latae',None),28:('Identify the highlighted structure.','Fascia lata',[]),30:('Identify the highlighted muscle.','Superficial gluteal',None),32:('Identify the highlighted structure.','Sacrotuberous ligament',[]),34:('Identify the highlighted muscle.','Middle gluteal',None),36:('Identify the highlighted muscle.','Piriformis',None),38:('Identify the highlighted muscle.','Deep gluteal',None),40:('Identify the highlighted muscle.','Internal obturator',None),42:('Identify the highlighted muscle.','Gemelli',None),44:('Identify the highlighted muscle.','Quadratus femoris',None),46:('Identify the highlighted muscle.','External obturator',None)}
sc={}
for pn,(qq,name,m) in sl.items():
    if m=='[]': m=[]
    sc[pn]=mk(S,f's{pn}',qq,name,'',m=m)
main=[('Caudal + lateral thigh',[yc[k] for k in 'A B C D'.split()]+[sc[6],yc['Q4']]),('Medial thigh',[yc[k] for k in ['P1','P2','P3','Q1','Q3']]+[sc[17]]),('Hip + gluteal',[sc[30],sc[34],sc[36],sc[38],yc['R1'],sc[42],sc[44]])]
extra=[('Slides · thigh',[sc[k] for k in [2,4,8,10,12,13,15,19,21,23,24,26,28]]),('Slides · hip',[sc[k] for k in [32,40,46]])]
T=[("Name the fascia layers of the trunk (bold).","Superficial fascia of the trunk · thoracolumbar fascia · deep fascia of the trunk"),("Name the gluteal + caudal fasciae (bold).","Superficial gluteal fascia · deep gluteal fascia · superficial caudal fascia · deep caudal fascia"),("Name the thigh + leg fasciae (bold).","Medial femoral fascia · lateral femoral fascia · fascia lata · crural fascia"),("Which muscle inserts into the fascia lata?","Tensor fasciae latae (from the tuber coxae)"),("Which muscles contribute to the common calcanean tendon (Lab 11 ones)?","Biceps femoris · semitendinosus · gracilis (via fascia) — plus gastrocnemius + SDF (Lab 12)"),("Femoral triangle: what is it, and order of contents?","A SPACE (palpate femoral pulse). Caudal → cranial: femoral Vein, Artery, saphenous Nerve (VAN)"),("Symphysial tendon: what arises from it?","Gracilis (and adductor) from the pelvic symphysis"),("Sartorius: 2 parts and their stifle actions?","Cranial part extends the stifle; caudal part flexes it. Both flex the hip"),("Which nerve lies between biceps femoris and adductor?","Sciatic nerve"),("Which ligament must be cut to see the internal obturator tendon?","Sacrotuberous ligament (tendon crosses the lesser ischiatic notch)"),("Piriformis is associated with which gluteal muscle?","Middle gluteal (deep caudal portion)"),("Gemelli: what grooves them?","The tendon of the internal obturator"),("Which muscles insert in the trochanteric fossa?","External obturator · internal obturator · gemelli (quadratus femoris near it)"),("Which muscles insert on the greater trochanter?","Middle gluteal · piriformis · deep gluteal"),("Which gluteal inserts on the third trochanter?","Superficial gluteal"),("Hamstrings (caudal thigh) group action?","Extend the hip (coxal jt); variable at stifle; biceps + semitendinosus also extend the tarsus"),("Medial thigh group action?","Mainly ADDUCT the limb (gracilis, pectineus, adductor)"),("Popliteal lymph node location?","Caudal border of biceps femoris, directly caudal to the stifle, in fat")]
TT=[text_card2(q,a,'🧠 Concept / integration') for q,a in T]; TT[0]=TT[0].replace('class="card"','class="card on"',1)
open('site/gross-anatomy-lab11-terms.html','w').write(page('Lab 11 · No-Image Terms',f'{len(TT)} cards · fascia + concepts',''.join(TT)))
write_lab(11,'Lab 11 · Proximal Pelvic Limb',main,extra,len(TT))
print(sum(len(g) for _,g in main),sum(len(g) for _,g in extra),len(TT))
