import sys; sys.path.insert(0,'.')
from deck import *
D='/home/claude/l10/'
F={
'humeral':[("🦴 Which bones articulate?","Glenoid cavity of the scapula + head of the humerus"),("⚙️ Joint type + movement?","Ball-and-socket; moves in any direction but mainly flexion + extension"),("⭐ Key fact?","NO collateral ligaments; 'active ligaments' = tendons of supraspinatus, infraspinatus, subscapularis, coracobrachialis. Medial + lateral glenohumeral ligs are poorly developed")],
'tvh':[("📍 Where does it attach?","Greater tubercle → lesser tubercle, across the intertubercular groove"),("⚙️ Function?","Holds the tendon of origin of the biceps brachii in the groove")],
'cubital':[("🦴 Which bones articulate?","Humeral condyle + radial head + trochlear notch of the ulna (+ proximal radioulnar articulation, NOT weight bearing)"),("⚙️ Joint type + movement?","Hinge; collaterals restrict it to the sagittal plane (no ab/adduction); rotation happens at the radioulnar jt"),("⭐ Key fact?","All compartments communicate with each other")],
'lcl':[("⭐ Which crus dominates? Strength?","Cranial crus; the LCL is the STRONGER collateral"),("📍 How is it exposed?","Transect/reflect the origin of the lateral digital extensor")],
'mcl':[("⭐ Which crus dominates?","Caudal crus; passes between radius + ulna, attaching to both (especially the radius)"),("📍 What covers it, and what does it cover?","Covered by the biceps + brachialis tendons; it covers the medial coronoid process (osteochondrosis site)")],
'interosseous':[("📍 What does it unite?","Radius + ulna, proximally"),("⭐ Don't confuse with…","Interosseous MEMBRANE = broader sheet (not the bold term)")],
'abc':[("🦴 Which bones articulate?","Radius + ulna ↔ intermedioradial + ulnar carpal bones (proximal row)"),("⭐ Movement + communication?","MOST movement of the carpus; does NOT communicate with the middle carpal jt")],
'mc':[("🦴 Which bones articulate?","Proximal row ↔ distal row of carpal bones"),("⭐ Communication?","DOES communicate with the carpometacarpal jt (through the distal row)")],
'cmc':[("🦴 Which bones articulate?","Distal row of carpal bones ↔ metacarpals"),("⭐ Movement?","LEAST movement of the carpus")],
'pcl':[("📍 Where is it?","Thick fibrous layer on the palmar carpus, firmly attached to the carpal bones"),("⚙️ Function?","Prevents collapse of the carpus in weight bearing; forms the deep (dorsal) wall of the carpal canal")],
'mcp':[("🦴 Which bones articulate?","Metacarpal ↔ proximal phalanx (P1)"),("⭐ Key fact?","2 proximal sesamoids per joint, in the interosseous tendons")],
'pip':[("🦴 Which bones articulate?","Proximal phalanx (P1) ↔ middle phalanx (P2)")],
'dip':[("🦴 Which bones articulate?","Middle phalanx (P2) ↔ distal phalanx (P3)"),("⭐ Clinical?","Laceration of the digital flexors → overextension of the interphalangeal joints")],
'coronoid':[("⭐ Clinical?","Site of osteochondrosis lesions; lies under the MCL")],
}
C=[]
def A(tag,q,a,key,qq,name,fk,clue=''):
    save_img(q,f'site/assets/lab10_{key}q.jpg',1600); save_img(a,f'site/assets/lab10_{key}a.jpg',1600)
    facts=sum([F[k] for k in fk],[])
    C.append(img_card_facts(qq,f'assets/lab10_{key}q.jpg',name,clue,f'assets/lab10_{key}a.jpg',facts,tag))
Y='📷 your photo · Linda\'s Joints'
lin=[("Transverse humeral retinaculum",['tvh']),("Medial collateral ligament (cubital)",['mcl']),("Medial coronoid process of the ulna (under the MCL)",['coronoid']),("Lateral collateral ligament (cubital)",['lcl']),("Interosseous ligament",['interosseous']),("Antebrachiocarpal joint",['abc']),("Middle carpal joint",['mc']),("Carpometacarpal joint",['cmc']),("Flexor manica + palmar carpal ligament (deep to the flexor manica)",['pcl']),("Metacarpophalangeal joints",['mcp']),("Proximal interphalangeal joints",['pip']),("Distal interphalangeal joints",['dip'])]
for k,(n,fk) in enumerate(lin): A(Y,D+f'lq{k}.jpg',D+f'la{k}.jpg',f'l{k}','Identify the indicated structure / joint level.',n,fk)
P='/home/claude/l9/'
A('📷 your photo',P+'c_q30.jpg',P+'c_a30.jpg','p30','Identify the indicated ligament.','Medial collateral ligament (your notes: "not bold term" → carpal)',[])
A('📷 your photo',P+'c_q31.jpg',P+'c_a31.jpg','p31','Identify the indicated ligament.','Lateral collateral ligament (your notes: "not bold term" → carpal)',[])
A('📷 your photo',P+'c_q32.jpg',P+'c_a32.jpg','p32','Identify the opened capsule / joint level.','Antebrachiocarpal joint (capsule opened)',['abc'])
A('📷 your photo',P+'c_q33.jpg',P+'c_a33.jpg','p33','Identify the indicated ligament.','Palmar carpal ligament',['pcl'])
SL={2:("Humeral joint",['humeral']),4:("Transverse humeral retinaculum",['tvh']),5:("Cubital joint",['cubital']),7:("Lateral collateral ligament (cubital)",['lcl']),9:("Medial collateral ligament (cubital)",['mcl']),11:("Interosseous ligament",['interosseous']),12:("Antebrachiocarpal joint",['abc']),13:("Middle carpal joint",['mc']),14:("Carpometacarpal joint",['cmc']),16:("Palmar carpal ligament",['pcl']),17:("Metacarpophalangeal joint",['mcp']),18:("Proximal interphalangeal joint",['pip']),19:("Distal interphalangeal joint",['dip'])}
for pn,(n,fk) in SL.items(): A('📚 course slide · Lab 10 Joints',D+f's{pn}q.jpg',D+f's{pn}a.jpg',f's{pn}','Identify the indicated structure / joint.',n,fk)
FG=[('g0','Left shoulder, LATERAL view: name each line.','Biceps brachii tendon · lateral + medial glenohumeral ligaments',['humeral']),('g1','Left shoulder, MEDIAL view: name each line.','Biceps brachii tendon · glenohumeral ligaments · transverse humeral retinaculum',['tvh']),('g2','Left shoulder capsule, LATERAL view: name each line.','Medial + lateral glenohumeral ligaments · joint capsule',[]),('g3','Left shoulder capsule, MEDIAL view: name each line.','Medial + lateral glenohumeral ligaments · joint capsule',[]),('g230','Left elbow, MEDIAL aspect: name each line.','Humerus · brachialis · biceps brachii · medial collateral ligament · caudal + cranial crura · oblique ligament · biceps + brachialis tendon · ulna · radius',['mcl']),('g231','Left elbow: A = cranial, B = lateral. Name each line.','A: humerus, radial fossa, anconeal process of ulna, inconstant sesamoid (supinator origin), ulna, radius · B: annular lig., lateral collateral lig. (caudal + cranial crura), interosseous membrane, interosseous ligament',['lcl','interosseous'])]
for key,qq,n,fk in FG: A('📖 lab guide figure',D+f'{key}q.jpg',D+f'{key}a.jpg',key,qq,n,fk)
L=C[0:12]; Pn=C[12:16]; Sl=dict(zip([2,4,5,7,9,11,12,13,14,16,17,18,19],C[16:29])); Fg=C[29:35]
main=[('Shoulder + elbow',[L[0],Sl[2],Sl[5],L[1],L[2],L[3],L[4]]),('Carpus + digit',[L[5],L[6],L[7],L[8],Pn[3],L[9],L[10],L[11]])]
extra=[('Course slides',[Sl[k] for k in [2,4,5,7,9,11,12,13,14,16,17,18,19] if k not in (2,5)]),('Your notes + guide figures',Pn[0:3]+Fg)]
T=[("Humeral jt vs glenohumeral ligaments?","Humeral jt = the articulation (bold term; use this name, not 'glenohumeral joint'). Glenohumeral ligs = weak capsular thickenings"),("Transverse humeral retinaculum vs glenohumeral ligament?","Retinaculum: tubercle → tubercle (one bone), over the biceps tendon · Glenohumeral: scapula → humerus, capsular"),("Which collateral ligament is stronger, and which crus dominates in each?","LCL = stronger; cranial crus dominates · MCL: caudal crus dominates (to radius especially)"),("Interosseous LIGAMENT vs MEMBRANE?","Ligament = short, dense, proximal (bold) · Membrane = broader sheet"),("Name the 3 carpal joint levels, proximal → distal.","Antebrachiocarpal · middle carpal · carpometacarpal"),("Which carpal compartments communicate?","Middle carpal ↔ carpometacarpal DO. Antebrachiocarpal does NOT communicate with middle carpal"),("Greatest vs least carpal movement?","Greatest: antebrachiocarpal · Least: carpometacarpal"),("Palmar carpal ligament vs flexor retinaculum?","Palmar carpal lig = deep (dorsal) wall of carpal canal · Flexor retinaculum = superficial (palmar) wall"),("PIP vs DIP?","PIP = P1 + P2 · DIP = P2 + P3 (named for the proximal bone of the pair)"),("How many carpal bones, in how many rows?","7 carpal bones in 2 rows"),("How many articulations per main digit?","3: MCP, PIP, DIP"),("How many proximal sesamoids per MCP joint, and where?","2, in the tendons of the interossei"),("Shoulder 'active ligaments' = which 4 tendons?","Supraspinatus · infraspinatus · subscapularis · coracobrachialis"),("Why can't the elbow abduct/adduct?","Taut collateral ligaments restrict it to the sagittal plane"),("Where does rotation of the forearm occur?","Radioulnar joint (proximal radioulnar articulation, not weight bearing)"),("Medial coronoid process: clinical significance?","Site of osteochondrosis lesions; deep to the MCL"),("Where can you needle the elbow joint?","Through the anconeus, in the groove between the lateral supracondylar crest and the olecranon"),("Where can you needle the antebrachiocarpal joint?","Carpus flexed, on either side of the ECR + CDE tendons"),("Name to use for the elbow on written answers?","Cubital joint")]
TT=[text_card2(q,a,'🧠 Concept') for q,a in T]; TT[0]=TT[0].replace('class="card"','class="card on"',1)
open('site/gross-anatomy-lab10-terms.html','w').write(page('Lab 10 · No-Image Terms',f'{len(TT)} cards · joint rules + confusable pairs',''.join(TT)))
write_lab(10,'Lab 10 · Thoracic Limb Joints',main,extra,len(TT))
print(len(C),len(TT))
