import sys; sys.path.insert(0,'.')
from deck import *; from oia_thoracic import OIA
O5={k:OIA[k] for k in ["Superficial pectoral","Deep pectoral"]}
C=[('📷 your photo','/home/claude/l5/n8q.jpg','/home/claude/l5/n8a.jpg','n8','Identify every highlighted muscle.','Superficial pectoral mm.: descending pectoral (pink) · transverse pectoral (green)','Ventral view, left side'),
('📷 your photo','/home/claude/l5/n9q.jpg','/home/claude/l5/n9a.jpg','n9','Identify every highlighted muscle.','Superficial pectoral mm. (descending = pink, transverse = green) · deep pectoral (purple)','Deep = ascending pectoral'),
('🎥 dissection video','/home/claude/l8/Hq00.jpg','/home/claude/l8/Ha00.jpg','v0','Identify both indicated muscles.','Superficial pectoral mm.: descending pectoral · transverse pectoral','Palpate superficial pectorals from in front of the forelimbs'),
('🎥 dissection video','/home/claude/l8/Hq01.jpg','/home/claude/l8/Ha01.jpg','v1','Identify the indicated muscle.','Cutaneous trunci m.','Attaches to superficial fascia of the trunk + skin; twitches the skin'),
('🎥 dissection video','/home/claude/l8/Hq02.jpg','/home/claude/l8/Ha02.jpg','v2','Identify the indicated muscle group.','Pectoral mm. (video label: "pectoralis")',''),
('🎥 dissection video','/home/claude/l8/Hq03.jpg','/home/claude/l8/Ha03.jpg','v3','What type of muscle is indicated?','Cutaneous muscle (in horses this region = cutaneous omobrachialis)','Cutaneous muscle = thin muscle in the superficial fascia that moves the skin'),
('📚 course slide · Extrinsic Muscles','/home/claude/l8/x3q.jpg','/home/claude/l8/x3a.jpg','x3','Identify the thin muscle between the fingers, and the thicker muscle just deep to it.','Cutaneous trunci m. (superficial, thin) · latissimus dorsi m. (deep, thick)',''),
('📚 course slide · Extrinsic Muscles','/home/claude/l8/x4q.jpg','/home/claude/l8/x4a.jpg','x4','Identify the highlighted muscles.','Superficial pectoral mm.',''),
('📚 course slide · Extrinsic Muscles','/home/claude/l8/x5q.jpg','/home/claude/l8/x5a.jpg','x5','Identify the highlighted muscle.','Deep pectoral m.',''),
('📚 course slide · Extrinsic Muscles','/home/claude/l8/x6q.jpg','/home/claude/l8/x6a.jpg','x6','Identify both transected muscle groups.','Superficial pectoral mm. + deep pectoral m. (after transection)',''),
('📖 lab guide Fig. 2-12','/home/claude/l5/fig5q.jpg','/home/claude/l5/fig5a.jpg','fig12','Ventral view of neck + thorax: name every labeled structure you can.','See labeled figure. Lab 5 targets: descending + transverse pectoral (superficial pectorals), deep pectoral. Also Lab 8: sternocephalicus, cleidocephalicus, sternohyoideus, omotransversarius','Superficial muscles of neck and thorax, ventral view'),
('📖 lab guide Fig. 2-10','/home/claude/l5/fig2q.jpg','/home/claude/l5/fig2a.jpg','fig10','Name each region of the forelimb, and mark every flexor surface.','See labeled figure: brachium, antebrachium (forearm), carpus, metacarpus, digits','Flexor surfaces: shoulder = caudal · elbow = cranial · carpus + digits = palmar')]
cards=[]
for tag,q,a,key,qq,name,clue in C:
    save_img(q,f'site/assets/lab5_{key}q.jpg',1600); save_img(a,f'site/assets/lab5_{key}a.jpg',1600)
    cards.append(img_card2(qq,f'assets/lab5_{key}q.jpg',name,clue,f'assets/lab5_{key}a.jpg',[m for m in find_muscles(name,O5)] if 'fig12' not in key else ["Superficial pectoral","Deep pectoral"],O5,tag))
K=dict(zip(['n8','n9','v0','v1','v2','v3','x3','x4','x5','x6','fig12','fig10'],cards))
main=[('Pectorals + cutaneous muscles',[K[k] for k in ['n8','n9','v0','x5','v1','v3']])]
extra=[('Extra views + guide figures',[K[k] for k in ['v2','x3','x4','x6','fig12','fig10']])]
T=[("Define: common integument","The skin: outer epidermis (thin epithelium) + underlying thicker dermis (connective tissue)"),("Define: epidermis vs dermis","Epidermis = outer thin epithelium · Dermis = thicker connective tissue layer beneath"),("What is a vortex?","A whorl where hair slants toward a point, e.g., the hair around the umbilicus"),("Umbilicus: where is it, and why does it matter?","On the linea alba at about the level of the last pair of ribs; a landmark in abdominal surgery"),("How many pairs of thoracic, abdominal, and inguinal mammae in the dog?","2 thoracic · 2 abdominal · 1 inguinal = 5 pairs (cat: 4 pairs, only 1 abdominal)"),("What forms the costal arch?","Costal cartilages of ribs 10, 11, 12. Rib 13 = floating rib (not attached)"),("Define: cutaneous muscle","Thin muscle in the superficial fascia that moves the skin"),("Define: areolar tissue","Thin, loose, irregularly arranged connective tissue, often with fat; where SQ injections go"),("Superficial fascia vs deep fascia","Superficial: deep to areolar tissue, covers whole body, holds cutaneous muscles + fat · Deep: firmly encloses individual muscles or groups"),("Define: origin vs insertion","Origin = fixed (usually proximal) attachment · Insertion = movable (usually distal) attachment"),("Tendon vs aponeurosis vs ligament","Tendon = cord, muscle→bone · Aponeurosis = flat sheet · Ligament = bone→bone"),("Cutaneous trunci: attachments and action?","Superficial fascia of the trunk + skin · twitches the skin"),("Which cutaneous muscle is in the neck?","Platysma (in the superficial fascia of the neck)"),("Preputial m.: who has it, and what does it do?","Male dogs only; cutaneous muscle that retracts the prepuce. Female equivalent: supramammary m."),("Superficial pectoral mm. = which 2 muscles?","Descending pectoral + transverse pectoral"),("Deep pectoral = also called?","Ascending pectoral m."),("Which pectorals are palpated from in front vs behind the forelimbs?","Superficial pectorals: from in front · Deep pectoral: from behind"),("Which side is dissected in lab?","The LEFT side of the specimen")]
TT=[text_card2(q,a,'🧠 Term / concept') for q,a in T]
TT[0]=TT[0].replace('class="card"','class="card on"',1)
open('site/gross-anatomy-lab5-terms.html','w').write(page('Lab 5 · No-Image Terms',f'{len(TT)} cards · definitions + concepts',''.join(TT)))
write_lab(5,'Lab 5 · Superficial Structures',main,extra,len(TT))
print(len(cards),len(TT))
