import sys; sys.path.insert(0,'.')
from deck import *; from oia_thoracic import OIA
L8=["Brachiocephalicus","Omotransversarius","Trapezius","Rhomboideus","Serratus ventralis","Latissimus dorsi","Sternocephalicus","Sternohyoideus","Sternothyroideus"]
O8={k:OIA[k] for k in L8}
D='/home/claude/l8/'
F={4:"Brachiocephalicus",5:"Clavicular intersection (white line = remnant of the clavicle); cleidobrachialis runs from here to the arm",6:"Cleidocephalicus (part of brachiocephalicus)",7:"Cleidocephalicus, pars cervicalis (brachiocephalicus)",8:"Cleidocephalicus, pars mastoidea (brachiocephalicus)",9:"Sternocephalicus",10:"Sternocephalicus, mastoid part",11:"Sternocephalicus, occipital part",12:"Sternohyoideus + sternothyroideus (together: 'sternothyrohyoideus')",13:"Sternothyroideus (the more lateral one)",14:"Sternohyoideus",15:"Omotransversarius",16:"Superficial cervical lymph nodes",17:"Trapezius",18:"Trapezius, cervical part",19:"Trapezius, thoracic part",20:"Rhomboideus (3 parts: capitis, cervicis, thoracis)",21:"Rhomboideus capitis",22:"Rhomboideus capitis",23:"Rhomboideus cervicis",24:"Rhomboideus thoracis",25:"Latissimus dorsi",26:"Latissimus dorsi",27:"Serratus ventralis",28:"Serratus ventralis cervicis",29:"Serratus ventralis thoracis",30:"Carotid sheath",31:"Lateral overview: trapezius, cleidocephalicus pars cervicalis, sternocephalicus, omotransversarius, clavicular intersection, cleidobrachialis (+ Lab 9: deltoideus, triceps, brachialis)",32:"Thoracolumbar fascia",33:"Linea alba",34:"Nuchal ligament + supraspinous ligament",35:"Nuchal ligament + median raphe of the neck"}
G={0:"Brachiocephalicus: cleidocephalicus (top piece) with pars cervicalis + pars mastoidea · clavicular intersection · cleidobrachialis (bottom piece)",1:"Latissimus dorsi",2:"Brachiocephalicus",4:"Trapezius",5:"Omotransversarius",6:"Sternocephalicus (whole piece): occipital part · mastoid part · manubrium attachment",7:"Sternothyroideus · sternohyoideus",8:"Superficial cervical lymph nodes",9:"Deep fascia of the neck",10:"Carotid sheath (with common carotid artery)",11:"Median raphe of the neck (midline)",12:"Trapezius: cervical part · thoracic part · separated by an aponeurosis",13:"Rhomboideus (3 parts)",14:"Rhomboideus + dorsal border of the scapula (its insertion)",15:"Serratus ventralis",16:"Serratus ventralis"}
X={7:"Brachiocephalicus (cervical part transected)",8:"Superficial cervical lymph nodes (clinically: 'prescapular lnn.')",9:"Sternocephalicus",10:"Sternothyroideus · sternohyoideus",11:"Omotransversarius",12:"Trapezius",14:"Rhomboideus (transected)",15:"Latissimus dorsi",17:"Serratus ventralis",18:"Serrated face of the scapula (serratus ventralis insertion)",19:"Serratus ventralis (limb removed)"}
cards=[]
def add(tag,qsrc,asrc,key,name):
    save_img(qsrc,f'site/assets/lab8_{key}q.jpg',1600); save_img(asrc,f'site/assets/lab8_{key}a.jpg',1600)
    q='Identify every highlighted / labeled structure.' if ('·' in name or '+' in name or 'overview' in name) else 'Identify the highlighted / indicated structure.'
    cards.append(img_card2(q,f'assets/lab8_{key}q.jpg',name,'',f'assets/lab8_{key}a.jpg',find_muscles(name,O8),O8,tag))
for k,n in G.items(): add('📷 your photo',D+f'gq{k:02d}.jpg',D+f'g{k:02d}.jpg',f'g{k:02d}',n)
import os
for k,n in F.items():
    q=D+f'Hq{k:02d}.jpg' if os.path.exists(D+f'Hq{k:02d}.jpg') else D+f'f{k:02d}_q.jpg'
    a=D+f'Ha{k:02d}.jpg' if os.path.exists(D+f'Ha{k:02d}.jpg') else D+f'f{k:02d}_a.jpg'
    add('🎥 dissection video / figure',q,a,f'f{k:02d}',n)
for k,n in X.items(): add('📚 course slide · Extrinsic Muscles',D+f'x{k}q.jpg',D+f'x{k}a.jpg',f'x{k}',n)
G=dict(zip([0,1,2,4,5,6,7,8,9,10,11,12,13,14,15,16],cards[0:16]))
Fd={k:cards[16+(k-4)] for k in F}
Xd=dict(zip([7,8,9,10,11,12,14,15,17,18,19],cards[48:59]))
main=[('Neck',[G[0],G[2],Fd[5],G[5],G[6],G[7],G[8],G[9],G[10]]),('Trapezius + rhomboideus',[G[4],G[12],G[11],G[13],G[14],Fd[21],Fd[23],Fd[24]]),('Latissimus + serratus + ligaments',[G[1],G[15],G[16],Fd[28],Fd[29],Fd[32],Fd[33],Fd[34]])]
used={5,21,23,24,28,29,32,33,34}
en=[Fd[k] for k in [4,6,7,8,9,10,11,12,13,14,15,16,30,31] if k not in used]; et=[Fd[k] for k in [17,18,19,20,22,25,26,27,35] if k not in used]
extra=[('Video frames · neck',en),('Video frames · trunk + scapula',et),('Extrinsic slides',list(Xd.values()))]
INT=[("Which extrinsic muscles ELEVATE the thoracic limb?","Trapezius · rhomboideus"),("Which extrinsic muscles pull the thoracic limb CRANIALLY?","Brachiocephalicus · omotransversarius"),("Which extrinsic muscle draws the limb CAUDALLY?","Latissimus dorsi"),("Which muscle SUPPORTS the trunk (the 'sling')?","Serratus ventralis"),("What inserts on the spine of the scapula?","Trapezius (and omotransversarius on the distal spine)"),("What inserts on the dorsal border of the scapula?","Rhomboideus"),("What inserts on the serrated face of the scapula?","Serratus ventralis"),("Which Lab 8 muscle inserts on the teres major tuberosity?","Latissimus dorsi"),("Which 2 muscle parts reach the mastoid process?","Cleidocephalicus pars mastoidea · sternocephalicus mastoid part"),("Which muscle attaches to the wing of the atlas?","Omotransversarius"),("Which rhomboideus part attaches to the nuchal crest?","Rhomboideus capitis"),("Brachiocephalicus = which 2 parts, divided by what?","Cleidobrachialis + cleidocephalicus, divided by the clavicular intersection"),("Cleidocephalicus = which 2 parts?","Pars cervicalis + pars mastoidea"),("Sternocephalicus = which 2 parts?","Mastoid part + occipital part"),("Trapezius = which 2 parts?","Cervical part + thoracic part (separated by an aponeurosis)"),("Rhomboideus = which 3 parts?","Capitis · cervicis · thoracis"),("Serratus ventralis = which 2 parts?","Cervicis · thoracis"),("TRAP: Are sternocephalicus, sternohyoideus, and sternothyroideus extrinsic limb muscles?","NO. They're neck muscles studied alongside them."),("What 4 structures are in the carotid sheath?","Common carotid artery · internal jugular vein · vagosympathetic trunk · tracheal lymphatic trunk"),("Which vein crosses the lateral surface of the sternocephalicus?","External jugular vein"),("Which is superficial: trapezius or rhomboideus?","Trapezius (on the scapular spine); rhomboideus is deep (dorsal border)"),("What does the supraspinous ligament connect?","Dorsal aspects of the vertebral spines (not the cervical vertebrae); continues cranially as the nuchal ligament"),("What is the nuchal ligament made of?","Yellow elastic fibrous tissue"),("Where do the two thoracolumbar fasciae meet ventrally?","Linea alba"),("Superficial cervical lymph nodes: clinical name?","Prescapular lymph nodes (deep to the omotransversarius)")]
T=[text_card2(q,a,'🧩 Integration / concept') for q,a in INT]
T[0]=T[0].replace('class="card"','class="card on"',1)
open('site/gross-anatomy-lab8-terms.html','w').write(page('Lab 8 · No-Image Terms',f'{len(T)} cards (O/I/A lives with the photos)',''.join(T)))
write_lab(8,'Lab 8 · Extrinsic Thoracic Limb + Neck',main,extra,len(T))
print(len(cards),len(T))
