# (img, prompt, answer, tell, fn, verify)
L1=[
("w1/02","What is the function of the circled lenses?","Objective lenses: magnify the specimen","Rotating nosepiece directly above the stage (scanning → 10× → 40×)","Magnification = objective × eyepiece (ocular) power",0),
("w1/03","Which components adjust the FOCUS (not the magnification)?","D: coarse/fine focus knobs","They raise and lower the stage","The eyepiece (A) has a diopter ring that only fine-tunes for your eye",1),
("w1/04","What is this lens called?","Condenser lens","Sits directly under the stage","Focuses light onto the slide; keep it at the TOP of its range",0),
("w1/05","What should you do if there is too much light on the slide?","A: adjust the light source (rheostat / light-intensity control)","Light intensity is set at the source, not with the objective or condenser","Diaphragm = resolution/contrast; rheostat = brightness",0),
("w1/06","What does this knob do?","Focus: raises/lowers the stage (coarse = big outer knob, fine = inner)","Large knob on the side of the arm at stage level","Coarse focus on scanning/10× only; fine focus at 40×",0),
("w1/07","What happens if the condenser lens is moved too far from the stage?","A: refraction increases; slide looks fuzzy","Light is no longer focused on the specimen → resolution drops","Fix: run the condenser back to the top of its range",0),
(None,"What does the “E” stand for in H&E?","Eosin","Acidic dye → stains acidophilic (eosinophilic) structures pink","H = hematoxylin, a basic dye → basophilic structures blue/purple",0),
("w1/09","Which image shows tissue stained ONLY with hematoxylin?","A","Everything is blue/purple; there is no pink anywhere","Without eosin, cytoplasm and collagen stay pale/unstained",0),
("w1/10","Which cell component stains PINK with H&E?","3: proteins","Proteins are acidophilic → bind eosin","DNA/RNA (phosphates) = basophilic; lipids are dissolved out in processing",0),
("w1/11","What organelle in the cytoplasm stains readily with hematoxylin (arrows)?","Rough endoplasmic reticulum (RER)","Ribosomal RNA is acidic → basophilic cytoplasm","Basophilic cytoplasm = protein-secreting cell (pancreas, chief cells, plasma cells)",0),
("w1/12","Which part of this cell is more eosinophilic?","A: apical part with secretory vesicles","Vesicles are packed with protein → pink","B (basal, RER-rich) is basophilic",0),
("w1/13","What is the general process cells use to release secretory material?","Exocytosis","Vesicle fuses with the apical membrane","Merocrine glands release this way",0),
("w1/14","Describe the cytoplasm of the cell at the arrow. (choose all)","B (eosinophilic) + E (homogeneous)","Parietal cell (stomach): smooth, evenly pink cytoplasm","Pink comes from abundant mitochondria. Eu/heterochromatic describe NUCLEI, not cytoplasm",0),
("w1/15","What is indicated by the arrow?","Nucleus of an adipocyte","Flattened and squeezed to the edge by one huge lipid droplet (“signet ring”)","Lipid itself is washed out → white space",1),
("w1/16","What is the term for loosely coiled chromatin?","Euchromatin","Pale, dispersed nucleus","Euchromatin = actively transcribed DNA",0),
("w1/16","Why is euchromatin loosely coiled?","A: it is being transcribed","Open DNA lets transcription machinery in","Big pale nucleus + prominent nucleolus = very active cell",0),
("w1/18","Which cell has the most heterochromatin in its nucleus?","C","Smallest, darkest, most condensed nucleus","Heterochromatin = tightly coiled, inactive DNA (bone marrow smear)",1),
("w1/19","Which descriptor best fits the NUCLEUS at the arrow?","D: heterochromatic","Dark, dense, condensed","Cuboidal is a cell shape; eosinophilic describes cytoplasm",0),
("w1/20","What are the small dark spots at the arrows?","Nucleoli","Dark dot INSIDE the nucleus","Site of rRNA synthesis/ribosome assembly → prominent in active cells",0),
("w1/21","Which best describes the orientation of the section through this artery?","B: longitudinal section","Vessel runs as a long tube along its length","Cross = ring; oblique = oval; tangential = grazes the wall",0),
("w1/22","Why is there a large white space in this fat cell?","B: lipid dissolved away during slide preparation","Alcohols/xylene extract the lipid","Same reason glycogen often looks empty/vacuolated",0),
("w1/23","What shape are these cells, based on the position and shape of the nuclei?","A: cuboidal","Round, central nuclei evenly spaced in a ring around a lumen","Cell height ≈ width (bile duct in liver)",0),
("w1/24","The arrow points to the location of what cellular feature?","C: nuclear envelope","Boundary of the round nucleus in a motor neuron","Use nucleus spacing to infer cell membranes you can’t see",0),
("w1/25","What stage of mitosis is depicted at the arrow?","Prophase","Chromosomes condensed but NOT lined up","Metaphase = line; anaphase = 2 groups pulling apart; telophase = 2 nuclei reforming",1),
("w1/26","Find a mitotic figure.","Dark bar of condensed chromosomes in a cell in the upper-right acinus","Solid dark linear figure, no nuclear envelope","A line of chromosomes = metaphase",1),
]
L2=[
("w2a/02","Define mesenchyme in 3 words or less.","Embryonic connective tissue","Fetal tissue: loose cells in lots of ground substance","Gives rise to all adult connective tissues",0),
("w2a/03","Which shape best describes the mesenchymal cell at the arrow?","D: stellate (star-shaped)","Cells with multiple thin processes floating in pale ground substance","Few fibers, lots of ground substance",0),
("w2a/04","This nucleus belongs to a/an:","B: fibroblast","Thin, dark, flattened nucleus squeezed between collagen bundles","Fibroblasts make collagen + ground substance",0),
("w2a/05","Classify this tissue of a tendon.","Dense regular connective tissue","Parallel collagen bundles with rows of flattened fibroblast nuclei","Tensile strength in ONE direction (tendons, ligaments)",0),
("w2a/06","Classify this tissue of the tunica albuginea of a penis.","Dense irregular connective tissue","Thick collagen bundles running in many directions, few cells","Resists stress from many directions (dermis, capsules)",0),
("w2a/07","Which cell is an eosinophil?","E","Bilobed nucleus + bright red (eosinophilic) granules","A = mast cells; B = neutrophil in a vessel; D = lymphocyte",0),
("w2a/08","Click on a mast cell.","The cells packed with granules around a round, central nucleus (row in the lower center)","Granules fill the cytoplasm and often hide the nucleus edge","Release histamine + heparin → allergy/inflammation",0),
("w2a/09","What are the red-staining structures in the cytoplasm of this mast cell?","Secretory granules (histamine, heparin)","Coarse granules filling the cytoplasm","Degranulation = type I hypersensitivity (anaphylaxis)",0),
("w2a/10","Click on a macrophage.","Large cell with an oval/kidney-shaped nucleus and pale, foamy cytoplasm","Cytoplasm looks vacuolated or holds ingested material","Phagocytosis; tissue macrophage derived from monocytes",1),
("w2a/11","What organelle causes the clear area next to the nucleus in this plasma cell?","Golgi apparatus","Pale perinuclear halo (“negative Golgi image”)","Golgi packages the antibodies the plasma cell secretes",0),
("w2a/12","Click on a plasma cell.","Cell in the connective tissue between acini: eccentric “clock-face” nucleus + basophilic cytoplasm + pale halo","Clumped chromatin like spokes of a wheel","Antibody factory (lots of RER → basophilic)",1),
("w2a/13","Identify the cells labeled E, N, and L.","E = eosinophil · N = neutrophils · L = lymphocyte","E: red granules · N: multilobed nucleus · L: small round dark nucleus","Blood cells inside a vessel in gallbladder",0),
("w2a/14","Click on a neutrophil in this blood vessel.","Cell with a multilobed (3–5 segments) nucleus and pale cytoplasm","Segmented nucleus, no red granules","First responder in acute inflammation",0),
("w2a/15","Identify the cell.","Lymphocyte","Small round dark nucleus, barely any cytoplasm","Immune cell; common in connective tissue and lymphatic tissue",0),
("w2a/16","What type of surface modification is present on these cells?","B: cilia","Fine hairs on the apical surface of oviduct cells","Cilia MOVE fluid/ova; microvilli/brush border ABSORB",0),
("w2a/17","What type of surface structure contains microtubules?","Cilia (9+2 axoneme, right image)","Ring of 9 doublets + 2 central microtubules","Left image = microvilli (actin core)",0),
("w2a/18","What is the classification of this epithelium (oviduct)?","Simple columnar (ciliated)","One layer of tall cells, all reaching the surface","Don’t confuse with pseudostratified: check if nuclei are in one row",1),
("w2a/19","Which is the apical surface of this duct cell?","C","Faces the lumen","A = basal surface (basement membrane side)",0),
("w2a/20","Where are you most likely to find tight junctions?","C","Apical-most lateral border, next to the lumen","Seal the lumen from the intercellular space",0),
("w2a/21","Where is the basement membrane?","A","Basal side, against the connective tissue","Separates epithelium from connective tissue",0),
("w2b/01","Click on stratified cuboidal epithelium.","The darker-staining sweat gland DUCTS (2 layers of cuboidal cells)","Ducts are smaller and darker than the secretory portion","Stratified cuboidal = classic for sweat gland ducts",0),
("w2b/02","Classify the epithelium containing the cells at the arrows.","Simple squamous","Single layer of flat cells (parietal layer of Bowman’s capsule)","Thin = built for filtration/diffusion",0),
("w2b/03","Classify this epithelium (eye).","Stratified squamous, nonkeratinized","Many layers, flat at the surface, nuclei all the way up","Cornea: moist surface, no dead keratin layer",0),
("w2b/04","What accounts for the difference in appearance between A and B?","Plane of section","A cut perpendicular → simple columnar; B cut obliquely/tangentially → looks stratified","Always check plane before classifying",0),
(None,"What does the root word “pseudo-” mean?","False","Pseudostratified looks layered but is not","Every cell touches the basement membrane; not all reach the surface",0),
("w2b/06","Classify this epithelium (larynx).","Pseudostratified ciliated columnar (respiratory epithelium)","Nuclei at multiple levels + cilia + goblet cells","Mucociliary escalator",0),
("w2b/07","Identify this cell in the stratified columnar epithelium of the conjunctiva.","Goblet cell","Pale, mucus-filled apical cup","Secretes mucus",0),
("w2b/11","Identify the bracketed layer containing adipose tissue.","E: subcutis/hypodermis","Deepest layer, loose CT + fat, below the dermis","Insulation, energy storage, attachment",0),
("w2b/12","What gives the stratum granulosum its dark purple, basophilic look?","C: keratohyalin granules","Thin dark band just below the stratum corneum","Granules help bundle keratin → keratinization",0),
("w2b/13","What is the brown-stained inclusion in the basal layer of this epidermis?","Melanin","Brown pigment in stratum basale","Made by melanocytes, handed to keratinocytes → UV protection/pigmentation",0),
("w2b/14","Which cell adhesions make the “spiny” look in the stratum spinosum?","Desmosomes","Cells shrink in processing but stay pinned at desmosomes → spines","Strong cell–cell adhesion",0),
("w2b/15","Identify the pale-stained area surrounded by the bracket.","D: papilla of the dermis (dermal papilla)","Finger of dermis poking up into the epidermis","Anchors epidermis; brings capillaries close",0),
("w2b/16","Identify this gland found in non-hairy thick skin.","B: merocrine (eccrine) sweat glands","Coiled tubules, small lumens, in the deep dermis of hairless (pad) skin","Apocrine glands go with hair follicles",0),
(None,"What causes this open space in the keratinized layer?","A sweat duct passing through the stratum corneum","Spiral channel through the keratin","Eccrine ducts open directly onto the skin surface",0),
("w2b/18","Identify this skin structure.","Sebaceous gland","Clusters of pale, foamy cells attached to a hair follicle","Holocrine secretion of sebum",0),
(None,"Which of the following describes holocrine secretion?","A: apoptosis and sloughing off of the epithelial cells","Whole cell becomes the product","Sebaceous glands",0),
("w2b/20","“Blebs” at the surface of secretory cells are evidence of what process?","Apocrine secretion","Apical cytoplasm pinches off","Apocrine sweat glands (and glands near the anus)",0),
]
L3=[
("w3/03","Click on a plasma cell.","Eccentric clock-face nucleus + basophilic cytoplasm + pale halo","Clumped chromatin like spokes","Makes antibodies",1),
("w3/04","Click on a fibroblast.","Thin, dark, flattened nucleus lying along collagen","Spindle-shaped, little visible cytoplasm","Makes collagen fibers and ground substance",1),
("w3/05","Click on nerve.","The pale, wavy, oval bundles in the fat (upper left)","Wavy pink fibers wrapped in a thin sheath","Nerves run with vessels in mesentery",0),
("w3/06","Identify this layer of the nerve.","Perineurium","Thin sheath of flattened cells wrapping one fascicle","Blood–nerve barrier",0),
("w3/07","At which position is the endoneurium?","C","Inside the fascicle, around each axon","A = epineurium (outer) · B = perineurium (around the fascicle)",0),
("w3/08","What cell makes myelin in the peripheral nervous system?","Schwann cell","Its nucleus sits right against the myelinated axon","CNS = oligodendrocyte",0),
("w3/09","Which of these is nerve?","A","Wavy fibers, wavy nuclei","B = smooth muscle (straighter, cigar-shaped nuclei)",0),
("w3/10","Identify a cell whose nucleus might be seen in this nerve OTHER than a Schwann cell.","Fibroblast (endoneurial)","Flattened nucleus in the connective tissue between fibers","Endothelial cells of capillaries are another option",0),
("w3/11","Identify the circled nerve structure in the gallbladder.","Ganglion","Contains large neuronal cell bodies (nerves do NOT)","Autonomic ganglion in the organ wall",0),
("w3/12","Dorsal root ganglion: identify the cell whose nucleus is at the arrow.","Satellite cell","Small cells ringing a large neuron cell body","Support/insulate ganglion neurons",0),
("w3/13","Nissl substance is composed of:","C: RER","Basophilic clumps in the neuron cytoplasm","Protein synthesis for the huge neuron",0),
("w3/14","(Digestive system) Identify the structure at the arrow.","Neuron cell body in an enteric (myenteric) ganglion","Big cell, big pale nucleus, prominent nucleolus, between muscle layers","Controls gut motility",0),
("w3/15","Identify the connective tissue layer (bracket).","Perichondrium","Dense CT wrapping the cartilage","Outer fibrous layer + inner chondrogenic layer (appositional growth)",0),
("w3/16","Identify the tissue between the cells (epiglottis).","Extracellular matrix of elastic cartilage","Dark, fibrous-looking matrix around lacunae","Elastic fibers → flexibility",0),
("w3/17","Which is true of this tissue’s extracellular matrix? (choose all)","A, C, D","Acidophilic fibers + water-loving proteoglycans + basophilic ground substance","NOT B: chondroblasts/chondrocytes make it, not fibroblasts",0),
("w3/18","Identify the tissue.","Fibrocartilage","Chondrocytes in lacunae lined up between thick collagen bundles","Intervertebral disc, menisci",0),
("w3/19","What helps identify this as fibrocartilage? (choose all)","B (lacunae) + C (large collagen fibers)","Lacunae = cartilage; big collagen = fibro-","Tendon has collagen but NO lacunae",0),
("w3/20","What differentiates hyaline (trachea) from elastic (epiglottis) cartilage on H&E?","B: staining of the extracellular matrix","Elastic: dark, fibrous matrix · Hyaline: smooth, glassy","Both have perichondrium; both have isogenous groups",0),
("w3/21","Which of these is bone?","A","Cells sit in lacunae inside solid, layered matrix","B = dense regular CT",0),
("w3/22","Identify the circled structure.","Osteon (Haversian system)","Concentric lamellae around a central canal","Functional unit of compact bone",0),
("w3/23","Identify the space.","C: lacuna","Dark dot between lamellae","Holds an osteocyte",0),
("w3/24","Tissue fluid can reach this space. True or false?","True","Canaliculi connect each lacuna to the central canal","How osteocytes survive in mineralized bone",0),
("w3/25","Which layer forms FIRST during osteon formation?","A: the outer lamella","Osteons fill in from the outside → inward","Central canal is the last space left",0),
("w3/26","What occupies the spaces at the arrows?","Canaliculi: tissue fluid + an osteocyte process","Tiny channels radiating from lacunae","Osteocytes talk via gap junctions (mechanosensing)",0),
("w3/27","Which of the following is a component of this tissue?","B: collagen fibers (type I)","Ground bone: mineralized collagen matrix","No elastic fibers, no contractile proteins",0),
("w3/28","Identify this cell in developing bone of a fetal face.","Osteoclast","Large, multinucleated, eosinophilic, on the bone surface","Resorbs bone (in a resorption pit / Howship’s lacuna)",0),
("w3/29","Which shows intramembranous bone formation?","A","Bone spicules forming directly in mesenchyme, NO cartilage model","B = endochondral (cartilage model)",0),
("w3/34","What is circled in red?","Bone collar","Thin shell of bone around the middle of the cartilage model","Forms by intramembranous ossification from periosteum",0),
("w3/35","In this developing long bone, what is indicated by the rectangle?","C: primary center of ossification","Middle of the diaphysis where cartilage is being replaced","Secondary centers appear later in the epiphyses",0),
("w3/36","Which part of this developing bone is differentiating to a growth plate?","1","The cartilage at the end of the model, next to the ossifying zone","2 = periosteum/bone collar region",0),
("w3/37","Identify the entire bracketed layer.","Periosteum","Outer fibrous layer + inner cellular (osteogenic) layer","Appositional bone growth; anchors tendons",0),
("w3/39","Which type of growth happens in the circled zone (proliferation)?","B: interstitial growth","Stacked columns of flattened chondrocytes dividing","Interstitial growth lengthens the bone",0),
("w3/40","In which zone does the cartilage matrix get mineralized?","D: calcification","Zone just before bone is laid down","Order: resting → proliferation → hypertrophy → calcification → ossification",0),
("w3/41","The space containing a cartilage cell is called a:","Lacuna","Hollow around each chondrocyte","Same term as in bone",0),
("w3/42","Click on cartilage extracellular matrix.","The intensely basophilic (dark purple) cores under the pink bone","Calcified cartilage spicules","Bone is laid down on these cartilage remnants",0),
("w3/43","Click on an osteocyte.","Cells inside lacunae within the pink bone trabeculae","Trapped in matrix, not lining the surface","Osteoblasts line the surface; osteocytes are surrounded",0),
("w3/44","Identify this membrane that contains osteoblasts.","Endosteum","Thin cell layer lining the marrow side of bone","Periosteum = outer surface",0),
]
L4=[
(None,"Which muscle cell type is the smallest in diameter?","Smooth muscle","Small spindle cells, single central nucleus","Skeletal = largest (multinucleated fibers)",0),
("w4/03","Which is true regarding skeletal muscle organization?","B: fascicles are surrounded by perimysium","Epimysium = whole muscle · perimysium = fascicle · endomysium = each fiber","Myofibrils (not sarcomeres) make up a fiber",0),
("w4/04","What causes the grainy look of skeletal muscle in cross section?","C: myofibrils","Dots = myofibrils cut across","Fascicle = bundle of fibers; myofiber = the whole cell",0),
("w4/05","What cell produced the endomysium?","Fibroblast","Thin CT around each fiber","All CT layers are made by fibroblasts",0),
("w4/06","What is indicated by the arrows?","Peripheral nuclei of skeletal muscle fibers","Nuclei pushed to the edge under the sarcolemma","Peripheral nuclei = skeletal; central = cardiac/smooth",1),
("w4/07","What is joined together at the Z-line?","Adjacent sarcomeres (thin/actin filaments anchor here)","Z-line = border between sarcomeres","Sarcomere = Z-line to Z-line",0),
("w4/08","What is the purpose of a muscle spindle?","D: to send muscle stretch information to the CNS","Encapsulated intrafusal fibers + sensory nerve endings","Stretch reflex / proprioception",0),
("w4/09","Identify this cell within a muscle spindle.","Intrafusal muscle fiber","Small fibers inside a CT capsule","Extrafusal fibers = regular contractile fibers outside",0),
("w4/10","Click on cardiac muscle.","The right two panels","Branching fibers, central nuclei","Left two = skeletal (peripheral nuclei, unbranched)",1),
("w4/11","Which apply to cardiac muscle? (choose all)","B, C, D: branched, 1–2 nuclei, striated","Central nuclei, branching, intercalated discs","NOT voluntary; cytoplasm is eosinophilic",0),
("w4/12","Identify the structures at the arrows.","Intercalated discs","Dark lines crossing cardiac fibers, step-like","Gap junctions (electrical) + desmosomes (mechanical)",0),
("w4/13","How can you tell this is NOT smooth muscle? (choose all)","A (stippled/grainy cytoplasm) + B (irregular cell outlines)","Myofibrils + branching = cardiac","Central nuclei and nucleus-free profiles happen in smooth muscle too",0),
("w4/14","Click on endocardium.","Thin inner lining facing the chamber","Endothelium + subendothelial CT","Inner layer of the heart wall",0),
("w4/15","Click on Purkinje fibers.","Large, pale cells just under the endocardium","Bigger and paler than myocardium, few myofibrils","Conduction system (not cerebellar Purkinje cells!)",0),
("w4/16","Click on the smooth muscle layer cut longitudinally.","The lower layer with long, cigar-shaped nuclei","Nuclei stretched out parallel","Upper layer = cross-cut (round profiles)",1),
("w4/17","Why are some smooth muscle cells apparently lacking a nucleus?","B: plane of section","Cut through the tapered end of the cell, missing the central nucleus","Not an artifact",0),
("w4/18","This esophagus has smooth and skeletal muscle. Click on smooth muscle.","Bundles of small cells with central nuclei and NO striations","Skeletal = large fibers, peripheral nuclei","Esophagus switches skeletal → smooth along its length (varies by species)",1),
("w4/19","Identify the type of blood vessel.","A: elastic artery","Many wavy elastic lamellae in a thick tunica media","Carotid / aorta: stretch and recoil",0),
("w4/20","In what layer are these vasa vasorum of this muscular artery?","Tunica adventitia","Small vessels in the outer CT layer","Feed the outer wall of big vessels",0),
("w4/21","Identify the indicated layer of this artery.","Tunica media","Thick circular smooth muscle layer","Thickest layer in arteries",0),
("w4/22","Which layer is the tunica intima?","C","Innermost: endothelium + thin subendothelial CT","A = adventitia · B = media",0),
("w4/23","Name the cell.","Endothelial cell","Flat nucleus bulging into the lumen","Lines all vessels (simple squamous)",0),
("w4/24","Identify this cell in this arteriole.","Endothelial cell","Elongated nucleus along the lumen, parallel to the vessel","Lines the lumen",1),
("w4/25","Identify this cell in this arteriole.","Smooth muscle cell","Nuclei stacked crosswise (circular cells seen in longitudinal section)","Arteriole = 1–2 layers of smooth muscle",0),
("w4/26","Identify this cell in this arteriole.","Fibroblast (adventitia)","Elongated nucleus on the OUTER edge of the wall","Endothelium is inside; smooth muscle in the middle",1),
("w4/28","Click on a venule.","The lower, flattened, thin-walled vessel","Large, irregular lumen with a thin wall","Upper vessel = arteriole (thicker media, round lumen)",1),
("w4/31","Click on a sinusoid.","The wide, irregular blood-filled spaces","Much wider than a capillary, irregular outline","Discontinuous/leaky capillaries (liver, marrow, spleen)",1),
("w4/32","Click on a valve in a lymph vessel.","Thin flap projecting into the pale lymph vessel lumen","Very thin wall, pale lymph, few/no RBCs","Valves keep lymph flowing one way",1),
]
L7=[
("w7/16","Identify the organ.","C: thymus","Lobules with dark cortex + pale medulla; thymic (Hassall’s) corpuscle","No nodules, no germinal centers",0),
("w7/17","Identify the organ.","B: spleen","White pulp nodules with central arterioles scattered in red pulp","No cortex/medulla",0),
("w7/18","Identify the organ.","A: lymph node","Capsule + subcapsular sinus + nodules in the cortex","Lymph node = only one with sinuses under the capsule",1),
("w7/19","Identify the organ.","D: tonsil","Epithelium-lined crypts + nodules, NO capsule","Stratified squamous epithelium on the surface",1),
("w7/20","Identify the collection of lymph nodules.","E: Peyer’s patch","Cluster of nodules in the small intestine wall","Ileum; part of MALT",0),
(None,"What is a primary lymphoid organ?","B: where lymphocytes mature and become immunocompetent","Thymus (T cells) + bone marrow (B cells)","Secondary = lymph node, spleen, tonsil, MALT",0),
(None,"What does MALT stand for?","Mucosa-associated lymphoid tissue","Nodules/diffuse lymphocytes in mucosae","Tonsils and Peyer’s patches are MALT",0),
("w7/23","In what layer is this MALT?","A: tunica mucosa","Lamina propria under the epithelium (can extend into submucosa)","",0),
("w7/24","Identify the circled structure.","Lymphatic nodule (solitary)","Round, dense cluster of lymphocytes","B-cell area",0),
("w7/25","Click on the germinal center.","Paler center of the nodule","Pale = activated, larger B cells","Mantle zone/corona = dark rim around it",0),
("w7/26","Classify the lymphatic tissue at the arrow.","A: diffuse","Scattered lymphocytes, no round nodule","Nodular = organized round follicles",0),
("w7/27","Why is this called a high endothelial venule?","Its endothelium is tall cuboidal, not flat","Plump endothelial cells with lymphocytes squeezing through","Where lymphocytes leave blood to enter the node (paracortex)",0),
("w7/28","Identify the specific space at the arrow.","Subcapsular sinus","Space directly under the capsule","First stop for lymph from afferent vessels",0),
(None,"Lymph flows from the subcapsular sinus to the medullary sinuses through which spaces?","Trabecular sinuses","Run along the trabeculae through the cortex","Full path: afferent → subcapsular → trabecular → medullary → efferent",0),
("w7/30","Identify the solid structure.","Medullary cord","Dense cords of cells between pale medullary sinuses","Plasma cells, macrophages, lymphocytes",0),
("w7/31","Assuming this is a dog lymph node, the lymph here is:","B: leaving the node","Large vessel at the hilus = efferent","Pig nodes are “inverted”",0),
("w7/32","Lymphocytes populating the deep cortex arrive mainly in what fluid?","A: blood","Enter via high endothelial venules","Deep cortex/paracortex = T-cell zone",0),
("w7/33","Which distinguishing tonsil feature is shown?","D: many lymphocytes invading the epithelium","Epithelium is blurred by infiltrating lymphocytes","Germinal centers/nodules occur in other organs too",0),
("w7/34","Classify this epithelium (tonsil).","Stratified squamous (nonkeratinized)","Many layers, flattened at the surface","Covers palatine tonsils and lines crypts",0),
("w7/35","Identify this cell in the epithelium.","Lymphocyte","Small round dark nucleus wandering in the epithelium","Hallmark of tonsils",0),
("w7/36","Which best describes the circled structure in this thymus?","A: cortex","Dark, dense, lymphocyte-packed outer part of the lobule","Medulla = paler center, continuous between lobules",0),
("w7/37","Identify the structure.","Thymic (Hassall’s) corpuscle","Concentric whorl of epithelial reticular cells in the medulla","Unique to thymus",0),
("w7/38","Identify the circled cell.","B: macrophage","Larger cell with paler cytoplasm holding debris","Clears T cells that fail selection",1),
("w7/39","Identify the cell with the oval nucleus and red granules.","C: mast cell","Oval nucleus + granular cytoplasm","Neutrophil = segmented nucleus",1),
("w7/40","Which vessel is encountered FIRST when blood enters the spleen (of these)?","A: central arteriole","Runs inside white pulp, wrapped by the PALS","Then penicillar arterioles → sinuses",0),
("w7/41","Identify this layer of this spleen.","Capsule","Dense CT on the outside","Sends trabeculae inward",0),
("w7/42","Identify this solid structure.","Trabecula","Pink CT band running into the pulp","Carries trabecular vessels",0),
("w7/43","Which lymphocytes surround this arteriole?","B: T cells","Periarteriolar lymphoid sheath (PALS)","Nodules = B cells",0),
("w7/44","Click on an area of primarily B lymphocytes.","The round lymphatic nodules (follicles) in the white pulp","Round, with germinal centers","PALS around the central arteriole = T cells",0),
("w7/45","Identify the specific part of the organ at the arrow.","B: red pulp","Blood-filled cords and sinuses between white pulp","Filters blood; removes old RBCs",0),
]
DECKS=[
("lab1","Lab 1 · Microscopy & Cytology","🔬",L1),
("lab2","Lab 2 · Connective Tissue, Epithelium & Skin","🧫",L2),
("lab3","Lab 3 · Nerve, Cartilage & Bone","🦴",L3),
("lab4","Lab 4 · Muscle, Heart & Circulation","🫀",L4),
("lab7","Lab 7 · Lymphatic Tissues & Organs","🛡️",L7),
]

# no-image recall cards per lab (🧠 terms decks)
TERMS={
"lab1":[("Acidophilic vs basophilic: what stains each?","Acidophilic/eosinophilic (pink) = proteins, mitochondria, secretory granules · Basophilic (blue/purple) = DNA, RNA/ribosomes/RER, sulfated GAGs"),
("4 planes of section","Transverse/cross · longitudinal · oblique · tangential (grazes the surface)"),
("Cytoplasmic inclusions to recognize","Lipid (empty white), glycogen (pale/vacuolated), pigment (e.g., brown melanin)"),
("Stages of mitosis in order + the tell for each","Prophase (condensed) → metaphase (line) → anaphase (2 groups pulling apart) → telophase (2 nuclei reforming)"),
("No visible cell membrane: how do you find the cell boundary?","Use nucleus spacing + cytoplasm staining; the border sits halfway between neighboring nuclei"),
("Microscope part → job","Objectives = magnify · stage controls = move slide · condenser = focus light · diaphragm = contrast/resolution · focus knobs = sharpness · rheostat = brightness")],
"lab2":[("Connective tissue types to classify","Mesenchyme · loose · dense irregular · dense regular · dense regular elastic · adipose"),
("Collagen vs elastic fibers on H&E","Collagen = thick, pink, wavy bundles · elastic = thin, darker, refractile; best seen as lamellae in the elastic-artery media"),
("Epithelium naming: 2 parts","Layers (simple, stratified, pseudostratified, transitional) + surface cell shape (squamous, cuboidal, columnar)"),
("Epidermis layers, deep → superficial","Stratum basale → spinosum → granulosum → lucidum (thick skin only) → corneum"),
("3 major skin layers","Epidermis → dermis → hypodermis/subcutis"),
("Dermis connective tissue","Papillary = loose CT · reticular = dense irregular CT"),
("Sebaceous vs apocrine vs merocrine glands","Sebaceous = holocrine, foamy cells, into the follicle · apocrine = big lumen, blebs, into the follicle · merocrine/eccrine = small lumen, onto the skin (pads)"),
("Sweat gland duct epithelium","Stratified cuboidal (2 layers)"),
("Myoepithelial cells","Flat contractile cells between gland cells and basement membrane; squeeze secretions out"),
("Arrector pili muscle","Smooth muscle from dermis to hair follicle; raises hair"),
("Defensive cells in CT","Macrophage · eosinophil · neutrophil · lymphocyte · mast cell · plasma cell")],
"lab3":[("Nerve vs ganglion","Ganglion HAS neuron cell bodies; nerve has only axons + Schwann cells"),
("3 CT layers of a peripheral nerve (inner → outer)","Endoneurium (each axon) → perineurium (fascicle) → epineurium (whole nerve)"),
("Node of Ranvier","Gap between Schwann cells along a myelinated axon (longitudinal section)"),
("Supporting cells of PNS","Schwann cells (nerve) · satellite cells (ganglion) · fibroblasts (CT)"),
("Hyaline vs elastic vs fibrocartilage","Hyaline = glassy, perichondrium · elastic = dark fibers, perichondrium · fibro = collagen bundles, rows of cells, NO perichondrium"),
("Fibrocartilage vs tendon","Fibrocartilage has chondrocytes IN LACUNAE; tendon has flat fibroblasts"),
("Perichondrium: 2 layers","Outer fibrous + inner chondrogenic"),
("Interstitial vs appositional cartilage growth","Interstitial = isogenous groups dividing inside matrix · appositional = new cartilage added at the perichondrium"),
("Why is cartilage matrix basophilic?","Sulfated GAGs/proteoglycans (negative charge)"),
("3 bone cells + job","Osteoblast = builds · osteocyte = maintains/senses (in lacuna) · osteoclast = resorbs (multinucleated)"),
("Endochondral vs intramembranous","Endochondral = cartilage model first · intramembranous = directly in mesenchyme (flat bones)"),
("Growth plate zones (epiphysis → diaphysis)","Resting/reserve → proliferative → hypertrophic → calcified → ossification/resorption"),
("Central vs perforating canals","Central (Haversian) = long axis of osteon · perforating (Volkmann) = cross-connect, perpendicular"),
("Articular cartilage surface cells","Flattened chondrocytes at the articular surface; no perichondrium")],
"lab4":[("Skeletal vs cardiac vs smooth: nuclei","Skeletal = many, peripheral · cardiac = 1–2, central · smooth = 1, central"),
("Which muscle has intercalated discs + branching?","Cardiac"),
("3 CT layers of skeletal muscle (inner → outer)","Endomysium (fiber) → perimysium (fascicle) → epimysium (whole muscle)"),
("3 layers of the heart (inner → outer)","Endocardium → myocardium → epicardium"),
("Purkinje fibers vs Purkinje cells","Fibers = cardiac conduction cells under the endocardium · cells = neurons in the cerebellum"),
("Vessel wall layers + parts","Tunica intima (endothelium, subendothelial CT, internal elastic lamina) · tunica media (smooth muscle, external elastic lamina) · tunica adventitia"),
("Elastic vs muscular artery","Elastic = many elastic lamellae in media · muscular = mostly smooth muscle + clear internal elastic lamina"),
("Artery vs vein","Artery: thick media, round lumen · vein: thin wall, big collapsed lumen, thick adventitia"),
("Arteriole vs capillary","Arteriole = 1–2 smooth muscle layers · capillary = just endothelium, about 1 RBC wide")],
"lab7":[("Lymph flow through a lymph node","Afferent vessels → subcapsular sinus → trabecular sinuses → medullary sinuses → efferent vessels (hilus)"),
("Blood flow / lymphocyte entry in a lymph node","Artery in at hilus → capillaries → high endothelial venules (paracortex) where lymphocytes exit blood"),
("Lymph node regions","Capsule · trabeculae · cortex (nodules) · paracortex/deep cortex (T cells) · medulla (cords + sinuses) · hilus"),
("Lymphatic nodule parts","Germinal center (pale) + mantle zone/corona (dark rim)"),
("Tonsil distinguishing features","Stratified squamous epithelium · lymphocytes infiltrating epithelium · crypts · nodules · diffuse tissue · NO capsule"),
("Spleen vs lymph node","Spleen: red + white pulp, trabecular vessels, NO cortex/medulla, no sinuses under capsule"),
("White pulp parts","Central arteriole · PALS (T cells) · nodules (B cells) · germinal centers · marginal zone"),
("Red pulp parts","Splenic cords (macrophages, lymphocytes, plasma cells) · splenic sinuses · pulp + sheathed arterioles"),
("White pulp vs red pulp function","White = immune response to blood-borne antigens · red = filters blood, removes old RBCs"),
("Thymus organization","Capsule · lobules · cortex · medulla continuous between lobules · thymic corpuscles"),
("Why is the thymus unique?","Stroma = epithelial reticular cells, NOT reticular connective tissue"),
("Compare 4 lymphatic organs, one tell each","Tonsil = epithelium + crypts · lymph node = capsule + sinuses + cortex/medulla · spleen = red/white pulp · thymus = lobules, no nodules, corpuscles")],
}
OBJ={
"lab1":["objective","condenser","diaphragm","focus","light","acidophil","basophil","nucleus","nucleolus","cytoplasm","cell membrane","cross","longitudinal","oblique","tangential","parietal","mitochondria","rer","secretory vesicle","macrophage","lipid","glycogen","pigment","prophase","metaphase","anaphase","telophase"],
"lab2":["mesenchyme","loose connective","dense irregular","dense regular","elastic","adipo","collagen","fibroblast","macrophage","eosinophil","neutrophil","lymphocyte","mast cell","plasma cell","simple","stratified","pseudostratified","transitional","squamous","cuboidal","columnar","basement membrane","goblet","brush border","cilia","kerat","sebaceous","sweat","duct","epidermis","dermis","hypodermis","stratum basale","stratum spinosum","stratum granulosum","stratum lucidum","stratum corneum","melanin","keratohyalin","hair follicle","arrector pili","apocrine","merocrine","myoepithelial"],
"lab3":["nerve","ganglion","neuron","schwann","satellite","fibroblast","axon","endoneurium","perineurium","epineurium","node of ranvier","hyaline","elastic cartilage","fibrocartilage","chondrocyte","lacuna","chondroblast","perichondrium","fibrous","chondrogenic","matrix","ground substance","collagen","proteoglycan","interstitial","appositional","isogenous","articular","osteoblast","osteocyte","osteoclast","osteon","canalicul","central canal","perforating","endosteum","periosteum","marrow","endochondral","intramembranous","bone collar","primary center","secondary center","epiphysis","diaphysis","growth plate","resting","proliferat","hypertroph","calcifi","ossification"],
"lab4":["smooth muscle","cardiac","skeletal","striat","intercalated","branch","peripheral nuclei","endomysium","perimysium","epimysium","muscle spindle","epicardium","myocardium","endocardium","purkinje","elastic artery","muscular artery","arteriole","capillary","vein","tunica intima","endothelium","subendothelial","internal elastic lamina","tunica media","external elastic lamina","tunica adventitia","elastic lamellae"],
"lab7":["diffuse","nodule","peyer","germinal center","mantle","tonsil","crypt","stratified squamous","lymph node","capsule","trabecula","cortex","paracortex","medulla","hilus","subcapsular sinus","trabecular sinus","medullary cord","medullary sinus","afferent","efferent","high endothelial venule","spleen","red pulp","white pulp","central arteriole","pals","marginal zone","splenic cord","splenic sinus","sheathed","thymus","lobule","epithelial reticular"],
}

# --- added from lecture PDFs (LC19, Circulatory overview, LC36, LC37, Week 7 orientation); labels erased, numbered
L4 += [
("lec/L19_4","Name the 3 heart-wall layers, left (inner surface) → right (outer surface).","Endocardium → myocardium → epicardium","Thin inner lining · thick cardiac muscle · thin outer CT layer","Epicardium = mesothelium + CT + fat; coronary vessels run here",0),
("lec/L19_13","Identify the wavy pink band. What lines the lumen at 1?","Internal elastic lamina · 1 = endothelium","Wavy sheet right under the endothelium; subendothelial CT sits between","Distinct in arteries, faint or absent in veins",0),
("lec/L19_18a","What are the dark wavy lines at the arrows (tunica media)?","Elastic lamellae","Many concentric wavy sheets between smooth muscle","Elastic artery (aorta): stretch + recoil (Windkessel effect)",0),
("lec/L19_18b","Name the 3 bracketed layers, left → right (elastic artery).","Tunica adventitia → tunica media → tunica intima","Outer CT → thick media full of lamellae → thin inner layer","Elastic artery: media is the thickest layer",0),
("lec/L19_19","Identify the type of vessel.","Muscular artery","Thick smooth-muscle media, round lumen, prominent internal elastic lamina","External elastic lamina separates media from adventitia",0),
("lec/L19_20","Identify this type of vessel (all 4 panels).","Arteriole","Small round lumen ringed by 1–3 layers of smooth muscle","Main resistance vessels",0),
("lec/L19_22","Classify the vessels at the teal arrows.","Arterioles (round, thick muscle ring) · venules (larger, thin wall, irregular) · capillary with pericyte (1 cell thick)","Compare wall thickness to lumen size","Venules = main site of leukocyte diapedesis",0),
("lec/L19_23a","Which vessel is the artery and which is the vein?","1 = artery · 2 = vein","Artery: thick wall, round lumen · vein: thin wall, big flattened lumen","Veins have the thickest adventitia",0),
("lec/L19_23b","Identify the structure at the teal arrow (vein, trichrome).","Valve","Fold of tunica intima projecting into the lumen","Prevents backflow in medium/large veins",0),
("lec/CIR_3","Neurovascular bundle: which is the artery, A or B?","A","Thick round muscular wall, round lumen","B = vein (thin wall, collapsed); arteries, veins, nerves travel together",0),
]
L7 += [
("lec/L36_11","Identify the collection of nodules.","Peyer's patch","Group of lymphatic nodules in the small intestine wall (ileum)","M cells in the epithelium sample antigens; B-cell maturation site",0),
("lec/L36_21","Lymph node paracortex: what are the vessels at the arrows?","High endothelial venules (HEV)","Plump cuboidal endothelium; lymphocytes squeezing through","T cells enter the paracortex here",0),
("lec/W7_6","Identify the organ, then find the cortex, paracortex, and medulla.","Lymph node · cortex = outer nodules · paracortex = dense zone under the nodules · medulla = paler center of cords + sinuses","Capsule + nodules around the edge","Paracortex = T cells (thymus-dependent zone)",0),
("lec/W7_8","What space is this, and what cells sit in it (arrows)?","Subcapsular sinus · macrophages","Pale space right under the capsule","First stop for lymph from afferent vessels",0),
("lec/L37_13","Identify this region of the spleen and name its 5 parts.","White pulp: nodule (B cells), germinal center, central artery, PALS (T cells), marginal zone","Dense purple lymphocytes around a central artery, red pulp around it","Marginal zone = border with red pulp, where blood antigens are sampled",0),
("lec/L37_18","Red pulp: name structures 1, 2, and 3.","1 = splenic sinusoid · 2 = splenic cord · 3 = macrophage-lined arteriole/capillary","Sinusoids = open channels · cords = cell-filled strips between them","Rod-shaped sinusoid endothelium filters out old RBCs",0),
]

# --- fold every no-image question into the image card it belongs to (no separate terms decks)
ATTACH={
"lab1":[("w1/09","What does the “E” stand for"),("w1/10","Acidophilic vs basophilic"),("w1/21","4 planes of section"),("w1/22","Cytoplasmic inclusions"),("w1/25","Stages of mitosis"),("w1/23","No visible cell membrane"),("w1/02","Microscope part")],
"lab2":[("w2b/06","What does the root word"),("w2a/05","Connective tissue types"),("w2a/06","Collagen vs elastic"),("w2b/02","Epithelium naming"),("w2b/12","Epidermis layers"),("w2b/11","3 major skin layers"),("w2b/15","Dermis connective tissue"),("w2b/18","Sebaceous vs apocrine"),("w2b/01","Sweat gland duct epithelium"),("w2b/16","Myoepithelial cells"),("w2b/18","Arrector pili muscle"),("w2a/07","Defensive cells in CT"),("w2b/16","What causes this open space"),("w2b/18","Which of the following describes holocrine")],
"lab3":[("w3/11","Nerve vs ganglion"),("w3/07","3 CT layers of a peripheral nerve"),("w3/09","Node of Ranvier"),("w3/12","Supporting cells of PNS"),("w3/20","Hyaline vs elastic vs fibrocartilage"),("w3/19","Fibrocartilage vs tendon"),("w3/15","Perichondrium: 2 layers"),("w3/39","Interstitial vs appositional"),("w3/17","Why is cartilage matrix basophilic"),("w3/28","3 bone cells"),("w3/29","Endochondral vs intramembranous"),("w3/40","Growth plate zones"),("w3/22","Central vs perforating"),("w3/36","Articular cartilage surface")],
"lab4":[("w4/17","Which muscle cell type is the smallest"),("w4/10","Skeletal vs cardiac vs smooth"),("w4/12","Which muscle has intercalated"),("w4/03","3 CT layers of skeletal muscle"),("lec/L19_4","3 layers of the heart"),("w4/15","Purkinje fibers vs Purkinje cells"),("w4/22","Vessel wall layers"),("w4/19","Elastic vs muscular artery"),("lec/L19_23a","Artery vs vein"),("lec/L19_22","Arteriole vs capillary")],
"lab7":[("w7/16","What is a primary lymphoid organ"),("w7/23","What does MALT stand for"),("w7/28","Lymph flows from the subcapsular"),("w7/28","Lymph flow through a lymph node"),("lec/L36_21","Blood flow / lymphocyte entry"),("lec/W7_6","Lymph node regions"),("w7/25","Lymphatic nodule parts"),("w7/19","Tonsil distinguishing features"),("w7/17","Spleen vs lymph node"),("w7/43","White pulp parts"),("lec/L37_18","Red pulp parts"),("w7/45","White pulp vs red pulp function"),("w7/36","Thymus organization"),("w7/37","Why is the thymus unique"),("w7/18","Compare 4 lymphatic organs")],
}

# --- 📷 Bethany's screenshots
L1 += [
("user/lab1_prophase1","📷 What stage of mitosis are these cells in?","Prophase","Chromatin condensing into dark threads/clumps INSIDE an intact nuclear envelope; no line, no separation","Next: metaphase (chromosomes line up at the middle)",0),
]
L1 += [
("user/lab1_metaphase1","📷 What stage of mitosis is the center cell in?","Metaphase","Chromosomes lined up in one dark band across the middle (metaphase plate); spindle fibers radiate to each side; no nuclear envelope","Next: anaphase (chromatids pull apart to opposite poles)",0),
]
L1 += [
("user/lab1_anaphase1","📷 What stage of mitosis is the center cell in?","Anaphase","Two dark groups of chromosomes pulled to OPPOSITE ends of one cell, spindle fibers stretched between them; no nuclear envelope","Next: telophase (two nuclei reform, cell pinches in the middle)",0),
]
L1 += [
("user/lab1_telophase1","📷 What stage of mitosis is shown?","Telophase","Chromosome groups at opposite ends, cell pinched almost in two by the cleavage furrow, two daughter cells forming","Nuclear envelopes reform; cytokinesis finishes the split",0),
]
L1 += [
("user/lab1_plane_xs","📷 What plane of section are these muscle fibers cut in?","Cross (transverse) section","Round/polygonal profiles, each fiber cut straight across","Cut perpendicular to the long axis",0),
("user/lab1_plane_long","📷 What plane of section is this?","Longitudinal section","Long parallel fibers running the length of the image, striations visible","Cut parallel to the long axis",0),
("user/lab1_plane_long2","📷 What plane of section is this skeletal muscle cut in?","Longitudinal section","Fibers run as long strips with cross-striations","Compare: cross = round profiles; oblique = ovals",0),
("user/lab1_plane_obl","📷 What plane of section are these fibers cut in (arrows = long axis of the profile)?","Oblique section","Profiles are OVALS (stretched circles), not round","Cut at an angle between cross and longitudinal",0),
("user/lab1_plane_tang","📷 What plane of section is this?","Tangential section","Cut just grazes the surface of the structure, so you see a thin slice of its outer edge","Shows the surface, not the center/lumen",1),
("user/lab1_plane_xslong","📷 Name the plane of section at 1 and at 2.","1 = cross section · 2 = longitudinal section","1: round profiles · 2: long parallel fibers","Same muscle, two cuts",0),
]
L1 += [
("user/lab1_plane_plant_xs","📷 (Plant wood) What plane of section is this?","Cross section","Tubes (vessels) cut straight across → round holes","Same rule as animal tissue: round profiles = cross",0),
("user/lab1_plane_plant_tang","📷 (Plant wood) What plane of section is this?","Tangential section","Cut grazes the side of the log: long streaks, no round openings, a lens-shaped band of cut-across cells in the middle","Tangential = slicing off the outer surface, not through the center",0),
]

# --- 📷 Bethany's Lab 7 screenshots (Dr. Basel lab recording, 10/6)
L7 += [
("user/lab7_diffuse","📷 Classify the lymphatic tissue under the epithelium.","Diffuse lymphatic tissue","Scattered lymphocytes in the lamina propria with NO round, organized nodule","Part of MALT (mucosa-associated lymphoid tissue)",0),
("user/lab7_secnodule","📷 What type of lymphatic nodule is this?","Secondary lymphatic nodule","Round nodule with a paler germinal center inside a darker rim (corona/mantle zone)","Secondary = has a germinal center = B cells actively responding to antigen. Primary = uniform dark, no germinal center",0),
("user/lab7_peyer","📷 Identify the circled collection of nodules in the small intestine.","Peyer's patch","Several lymphatic nodules lined up in the wall of the ileum","Gut-associated lymphoid tissue (GALT); M cells in the epithelium sample antigens",0),
("user/lab7_crypt","📷 Identify the space at the arrow in this tonsil.","Tonsillar crypt","Deep epithelium-lined pit folding into the tonsil","Crypts trap antigens and bring them close to the nodules",0),
("user/lab7_tonsilepi","📷 Classify the outlined epithelium lining this tonsil crypt.","Stratified squamous epithelium (nonkeratinized)","Many layers of cells, flattened toward the surface","Hallmark of the tonsil: lymphocytes invade (infiltrate) this epithelium",0),
("user/lab7_germinal","📷 Identify the pale center and the dark rim around it.","Pale center = germinal center · dark rim = corona (mantle zone)","Germinal center = larger, paler activated B cells · corona = small, tightly packed resting lymphocytes","A germinal center means this is a secondary nodule",0),
("user/lab7_tonsildiffuse","📷 Classify the lymphatic tissue in the green circle (tonsil).","Diffuse lymphatic tissue","Scattered lymphocytes BETWEEN the round nodules, no organized circle","Nodular = round follicles; diffuse = the loose tissue between them",0),
("user/lab7_hev","📷 Identify the circled vessel in the lymph node paracortex.","High endothelial venule","Plump, tall cuboidal endothelial cells instead of flat ones","Lymphocytes leave the BLOOD here to enter the lymph node",0),
("user/lab7_lncapsule","📷 Identify the thin pink layer at the gray arrows (lymph node).","Capsule","Thin dense connective tissue wrapping the outside (convex side) of the node","AFFERENT lymphatic vessels pierce the capsule → lymph ARRIVES",0),
("user/lab7_outercortex","📷 Identify the region at the arrows (ring of dark round bumps).","Outer cortex (cortex)","Ring of round lymphatic nodules just under the capsule","Nodules = B-cell area",0),
("user/lab7_paracortex","📷 Name the zone between the blue and green lines, and the zone inside the green line.","Between blue and green = paracortex · inside green = medulla","Paracortex = solid dark band with no round nodules · medulla = pale, lacy center (cords + sinuses)","Paracortex = T-cell zone (thymus-dependent); high endothelial venules live here",0),
("user/lab7_hilus","📷 Identify the circled region (the indentation of the node). What are the big round open circles in it?","Hilus · big circles = efferent lymphatic vessels","Indented (concave) side facing connective tissue and blood vessels; nodules are on the opposite side","EFFERENT lymphatic vessels EXIT at the hilus; AFFERENT lymphatic vessels ENTER through the capsule. Artery in, vein out also at the hilus",0),
("user/lab7_lntrabecula","📷 Identify the outlined pink band running inward from the capsule (lymph node).","Trabecula","Connective tissue band extending from the capsule into the node","Carries blood vessels; trabecular sinuses run alongside it",0),
("user/lab7_medcords","📷 Lymph node medulla: what are the pale lacy spaces vs the dark branching strands?","Pale spaces = medullary sinuses · dark strands = medullary cords","Sinus = open space (lymph flows) · cord = packed cells","Cords hold plasma cells, macrophages, lymphocytes. Sinus = SPACE (pale), cord = CELLS (dark)",0),
("user/lab7_pulp","📷 Which part is white pulp and which is red pulp?","Dark blue/purple spots = white pulp · pink everywhere else = red pulp","White pulp = lymphocytes · red pulp = blood-filled cords and sinusoids","Named from the FRESH spleen; on H&E the white pulp looks dark blue",0),
("user/lab7_pals","📷 Identify the structures inside the green outlines and the sleeve inside the blue outline.","Green = central arterioles · blue = periarteriolar lymphoid sheath (PALS)","Small vessel sitting INSIDE a sleeve of lymphocytes in the white pulp","PALS = T cells. A 4th central arteriole on the right side of the blue is unmarked: find it",0),
("user/lab7_spnodule","📷 Identify the circled white pulp structure (spleen).","Secondary lymphatic nodule","Round patch with a paler germinal center and a dark corona","B-cell area; the central arteriole often sits off-center in it",0),
("user/lab7_cordsinus","📷 Red pulp: what is in the green outline vs the blue outline?","Green = splenic sinusoid · blue = splenic cord","Sinusoid = pale, open space · cord = packed dark cells","Same rule as the lymph node: sinus = SPACE, cord = CELLS",0),
("user/lab7_spcapsule","📷 Identify the thick pink layer at the arrows (spleen).","Capsule","Thick, smooth band of dense connective tissue on the outside","Much thicker than the thymus capsule; contains fibroblasts and smooth muscle cells",0),
("user/lab7_sptrabecula","📷 Identify the structure at the gray arrow and at the black arrows (spleen).","Gray = trabecular vessel · black = trabeculae","Big open vessel wrapped in a thick pink sleeve · small pink bands scattered in the red pulp","The thick pink wall around the gray-arrow vessel is also trabecula; the vessel runs INSIDE it",0),
("user/lab7_sptrabsm","📷 Identify the pink band in the center (spleen, high power).","Trabecula","Smooth pink band with long, wavy, cigar-shaped nuclei = smooth muscle","Smooth muscle lets the spleen contract and release stored blood",0),
("user/lab7_thycortmed","📷 Thymus: name the dark outer zone (left arrow) and the pale inner zone (right arrow).","Dark outer = cortex · pale inner = medulla","Cortex packed with immature T cells (thymocytes); medulla has fewer cells","⚠️ Don't flip it: DARK = CORTEX. Same as lymph node: outside dark and crowded, inside pale",0),
("user/lab7_thycorpuscle","📷 What are the small pink circles in the pale center?","Thymic (Hassall's) corpuscles","Pink, layered, onion-like rings found only in the medulla","Made of epithelial reticular cells; only the thymus has them",0),
("user/lab7_thycorpclose","📷 Identify the pink swirled structures (close-up).","Thymic (Hassall's) corpuscles","Concentric pink layers, some with a keratinized pink core","Seeing them = it's the thymus",0),
("user/lab7_thycapsule","📷 Identify the thin pink layer at the arrows (thymus).","Capsule","Thin connective tissue on the outer edge of the lobule","Much thinner than the spleen capsule; sends septa inward",0),
("user/lab7_thylobule","📷 What is outlined in green?","Thymic lobule","One unit bounded by septa (white lines) and the capsule, with its own cortex","This lobule is cut near its edge, so it looks mostly like dark cortex",0),
("user/lab7_thysepta","📷 What are the thin white lines dividing this into sections?","Septa (interlobular septa)","Connective tissue lines extending in from the capsule","Each section between septa is one lobule; the medulla is shared across lobules",0),
]
EXTRA={
"user/lab7_peyer":[("What kind of nodules are these?","Lymphatic nodules (primary and secondary)")],
"user/lab7_crypt":[("What organ is this?","Tonsil")],
"user/lab7_tonsilepi":[("What cells are invading this epithelium?","Lymphocytes")],
"user/lab7_hev":[("What region of the lymph node is this?","Paracortex"),("What leaves the blood here?","Lymphocytes")],
"user/lab7_lncapsule":[("What big pale vessels are at the hilus?","Efferent lymphatic vessels")],
"user/lab7_outercortex":[("What cells fill the nodules?","B cells")],
"user/lab7_paracortex":[("What cells fill the paracortex?","T cells")],
"user/lab7_lntrabecula":[("What are the pale bubbly cells outside the capsule?","Adipose tissue (adipocytes)"),("What runs inside a trabecula?","Blood vessels")],
"user/lab7_pulp":[("What is the tiny white dot in the center of many blue spots?","Central arteriole")],
"user/lab7_pals":[("What is outside the blue line (pink)?","Red pulp")],
"user/lab7_sptrabsm":[("What type of muscle is in the trabecula?","Smooth muscle")],
"user/lab7_thycortmed":[("The pale center runs between lobules: what is that called?","Shared medulla")],
"user/lab7_thycorpuscle":[("Pale center vs dark rims?","Medulla vs cortex"),("Thin white lines between lobules?","Septa (interlobular septa)")],
"user/lab7_thycapsule":[("Thymus capsule vs spleen capsule?","Thymus = thin · spleen = thick")],
}

# --- 📝 VAP807 Lab 3a Exam 2025 (last year's practical) — answers reviewed with Bethany 10/6
EXAM25=[
("Auxiliary (condenser)","Knob under the stage moves the condenser up and down","Condenser focuses light onto the slide"),
("Rough endoplasmic reticulum (ribosomes)","Ribosomal RNA is acidic → binds hematoxylin","Basophilic cytoplasm = protein-making cell"),
("Nucleolus","Small dark dot inside the nucleus","Makes ribosomal RNA"),
("C","C is a round profile cut straight across","A and B are longitudinal/oblique tubes"),
("D","Chromatin condensing into threads inside an intact nucleus","A = anaphase · B = telophase · C = metaphase"),
("White (unilocular) adipose tissue","Big empty cells, nucleus squeezed to the edge","Lipid dissolves during processing → white space"),
("Collagen fibers","Pink bundles with NO nuclei inside; few flat fibroblast nuclei between","Question asks for STRUCTURES, not tissue (tissue = dense irregular connective tissue)"),
("B","Two-lobed nucleus + bright red-orange granules = eosinophil","A (round nucleus, purple granules) = mast cell"),
("B","",""),
("Collagen fibers (fibrocartilage)","Pink fiber bundles between rows of chondrocytes","Fibrocartilage = collagen + chondrocytes in lacunae"),
("Proteoglycans / glycosaminoglycans","Negatively charged sulfate groups bind hematoxylin","Why cartilage matrix stains blue/basophilic"),
("A · Appositional","New cartilage added at the surface, near the perichondrium","Interstitial = from inside (isogenous groups)"),
("Osteoblasts","Row of cuboidal cells lining the bone surface","Make osteoid (unmineralized bone matrix)"),
("Hypertrophic chondrocyte","Big, pale, swollen cells in large lacunae","Hypertrophic zone of the growth plate; 'chondrocyte' alone also fits"),
("Lacuna","Small space in the matrix that holds the cell","Both cartilage and bone have lacunae"),
("B","",""),
("Bone","Bright pink matrix with osteocytes in lacunae, lined by osteoblasts","Question asks for the TISSUE"),
("Fibrous layer (of the periosteum)","Outer dense connective tissue layer","Inner layer = cellular (osteogenic) layer"),
("Satellite cell","Small nuclei ringing a big neuron cell body in a ganglion","Support cells of ganglion neurons"),
("Myelinated axon (nerve fiber)","Small pale center = axon · spoke-like ring = myelin sheath","Wheel-spoke look = leftover protein after the myelin fat dissolved"),
("Node of Ranvier","Gap between two Schwann cells along a nerve fiber (longitudinal nerve)","⚠️ Check tissue first: dark line in a NERVE = node of Ranvier; in HEART = intercalated disc"),
("A","",""),
("Perineurium","Connective tissue sheath around one fascicle","Endoneurium = around each axon · epineurium = around the whole nerve"),
("Neuron cell body (ganglion cell)","Large round cell with a big nucleus and nucleolus","Surrounded by satellite cells"),
("Cardiac muscle","Branching striated fibers, central nuclei","Intercalated discs when visible"),
("Muscle spindle","Small capsule with thin intrafusal fibers inside skeletal muscle","Stretch receptor"),
("B · inner surface of the ventricle","The circled cells are Purkinje fibers","Purkinje fibers run in the subendocardium of the ventricles"),
("Simple columnar","One layer of tall cells","Goblet cells often mixed in"),
("Goblet cells","Pale, cup-shaped mucus cells between columnar cells","Secrete mucus"),
("Papillary layer of the dermis","Loose connective tissue poking up between the epidermal ridges","Reticular layer below = dense irregular connective tissue"),
("Melanin protects nuclei from ultraviolet light","Brown pigment capping the nuclei","Made by melanocytes, passed to keratinocytes"),
("Sebaceous gland","Pale, bubbly cells that fill the whole gland","Holocrine secretion"),
("A","Cells with bulging blebs (snouts) pinching off into a wide lumen = apocrine","B = eccrine (merocrine)"),
("Sweat gland duct","Darker, narrower tube with two layers of cuboidal cells","Secretory portion = paler, wider"),
("Epicardium (visceral pericardium)","Outer layer: mesothelium + connective tissue + fat","Coronary vessels run here"),
("Vein","Wall a few cell layers thick; travels next to an artery","Lymphatic vessel = endothelium only, no red blood cells"),
("Endothelial cell","Flat nucleus lining the lumen","Simple squamous epithelium of vessels"),
("Purkinje fibers","Big pale cells with myofibrils pushed to the edges","Subendocardium of the ventricles"),
("Vein (oblique section)","No wavy internal elastic lamina; big lumen packed with blood; irregular outline","⚠️ Smooth muscle alone ≠ artery (veins have some too); white blood cells are in all vessels"),
("B","",""),
("Secondary lymphatic nodule","Pale germinal center inside a dark corona","Secondary = germinal center present"),
("Spleen","White pulp scattered through red pulp, central arterioles, thick capsule","No cortex/medulla, no sinuses under the capsule"),
("Stratified squamous (nonkeratinized)","Many layers, flattened at the surface (tonsil crypt)","Lymphocytes infiltrate it"),
("High endothelial venule","Plump cuboidal endothelium in the paracortex","Lymphocytes leave the blood here"),
("Trabecula","Pink connective tissue band in the spleen","Carries trabecular vessels; contains smooth muscle"),
("Periarteriolar lymphoid sheath (PALS)","Lymphocyte sleeve around the central arteriole","T cells"),
("Splenic cord","Strand of cells between open sinusoids in the red pulp","Cord = CELLS · sinusoid = SPACE"),
("Cortex (of the thymus)","Dark, dense outer zone of the lobule","Medulla = pale center"),
("Tingible body macrophage","Macrophage with dark (pyknotic) nuclear debris in its cytoplasm","Eats B cells that fail selection in germinal centers"),
("Thymic (Hassall's) corpuscle","Pink onion-like whorl in the medulla","Only in the thymus"),
("Nerve (small nerve fascicle)","Small bundle with wavy, elongated nuclei","The big round cells beside it = ganglion"),
]

# --- 🧅 All the layers (cross-lab drill, reuses existing images)
LAYERS=[
# block A: nerve + skeletal muscle (same pattern: endo → peri → epi)
(None,"🧅 Say the 3 connective tissue layers of a NERVE, inner → outer.","Endoneurium → perineurium → epineurium","Endo = around each axon · peri = around one fascicle · epi = around the whole nerve","Same pattern as skeletal muscle: endo → peri → epi",0),
("w3/07","🧅 Nerve: which letter is the endoneurium? Name A and B too.","C = endoneurium · A = epineurium · B = perineurium","Endoneurium is INSIDE the fascicle, around each axon","Outer → inner: A epi → B peri → C endo",0),
("w3/06","🧅 Identify this thin sheath around one fascicle.","Perineurium","Flattened cells wrapping ONE bundle of axons","Blood–nerve barrier",0),
("exam25/q23","🧅 (2025 exam) Answer the question in the image.","Perineurium","Sheath around one fascicle","Endoneurium = each axon · epineurium = whole nerve",0),
(None,"🧅 Say the 3 connective tissue layers of SKELETAL MUSCLE, inner → outer.","Endomysium → perimysium → epimysium","Endo = each fiber · peri = each fascicle · epi = whole muscle","All made by fibroblasts",0),
("w4/03","🧅 Skeletal muscle: which layer surrounds each fascicle?","Perimysium","Thicker connective tissue between bundles of fibers","Endomysium = each fiber · epimysium = whole muscle",0),
("w4/05","🧅 What layer is around EACH muscle fiber here, and what cell made it?","Endomysium · fibroblast","Thinnest connective tissue, between individual fibers","",0),
# block B: heart + vessels
(None,"🧅 Say the 3 layers of the HEART wall, inner → outer.","Endocardium → myocardium → epicardium","Endo = endothelium + thin CT · myo = cardiac muscle · epi = mesothelium + CT + fat","Purkinje fibers sit in the subendocardium; coronary vessels run in the epicardium",0),
("lec/L19_4","🧅 Name the 3 heart layers, left → right.","Endocardium → myocardium → epicardium","Thin lining · thick muscle · thin outer CT","",0),
("w4/14","🧅 Click on the endocardium.","Thin inner lining facing the chamber","Endothelium + subendothelial connective tissue","Innermost heart layer",0),
("exam25/q35","🧅 (2025 exam) Answer the question in the image.","Epicardium (visceral pericardium)","Outer layer: mesothelium + connective tissue + fat","",0),
(None,"🧅 Say the 3 layers of a BLOOD VESSEL wall, inner → outer, plus the 2 elastic laminae.","Tunica intima → (internal elastic lamina) → tunica media → (external elastic lamina) → tunica adventitia","Intima = endothelium + subendothelial CT · media = smooth muscle · adventitia = outer CT","Internal elastic lamina = THIN WAVY PINK LINE, not a thick layer",0),
("w4/22","🧅 Which letter is the tunica intima? Name A and B.","C = tunica intima · A = tunica adventitia · B = tunica media","Intima = innermost, thinnest","",0),
("w4/21","🧅 Identify the indicated layer of this artery.","Tunica media","Thick circular smooth muscle","Thickest layer in arteries; adventitia is thickest in veins",0),
("lec/L19_13","🧅 Identify the wavy pink line. What lines the lumen at 1?","Internal elastic lamina · 1 = endothelium","Thin wavy line between intima and media","Clear in arteries, faint or absent in veins",0),
("w4/20","🧅 Which layer holds these vasa vasorum?","Tunica adventitia","Small vessels in the outer connective tissue","Feed the outer wall of big vessels",0),
# block C: skin
(None,"🧅 Say the 3 skin layers, then the 5 epidermis layers deep → superficial.","Epidermis → dermis → hypodermis · basale → spinosum → granulosum → lucidum (thick skin only) → corneum","🌿 'Brittany Spears Gives Little Concerts' = basale, spinosum, granulosum, lucidum, corneum","Dermis = papillary (loose) on top + reticular (dense irregular) below",0),
("w2b/11","🧅 Identify the bracketed layer containing adipose tissue.","Hypodermis (subcutis)","Deepest layer: loose CT + fat","",0),
("w2b/12","🧅 Which epidermis layer is the thin dark purple band, and why is it dark?","Stratum granulosum · keratohyalin granules","Just below the stratum corneum","",0),
("w2b/14","🧅 Which epidermis layer looks 'spiny'?","Stratum spinosum","Desmosomes hold cells together as they shrink → spines","",0),
("exam25/q30","🧅 (2025 exam) Answer the question in the image.","Papillary layer of the dermis","Loose CT poking up between epidermal ridges","Reticular layer below = dense irregular CT",0),
# block D: cartilage + bone + lymph organs
(None,"🧅 Say the 2 layers of the perichondrium AND of the periosteum.","Both = outer fibrous layer + inner cellular layer (chondrogenic for cartilage, osteogenic for bone)","Fibrous = dense CT outside · cellular = makes new cartilage/bone","Endosteum = thin cell layer lining the MARROW side of bone",0),
("w3/15","🧅 Identify the bracketed connective tissue layer around the cartilage.","Perichondrium","Dense CT wrapping hyaline or elastic cartilage","Fibrocartilage has NO perichondrium",0),
("w3/37","🧅 Identify the entire bracketed layer around the bone.","Periosteum","Outer fibrous + inner cellular (osteogenic) layer","",0),
("exam25/q18","🧅 (2025 exam) Answer the question in the image.","Fibrous layer (of the periosteum)","Outer dense CT part","Inner = cellular (osteogenic) layer",0),
("w3/44","🧅 Identify this membrane that contains osteoblasts.","Endosteum","Thin cell layer lining the marrow side","Periosteum = outer surface",0),
(None,"🧅 Say the lymph node regions, outer → inner, and the thymus regions.","Lymph node: capsule → cortex (nodules) → paracortex → medulla (cords + sinuses) · Thymus: capsule → cortex (dark) → medulla (pale, Hassall's corpuscles)","Both: outside dark, inside pale","Spleen has NO cortex/medulla: white pulp vs red pulp",0),
("lec/W7_6","🧅 Find the cortex, paracortex, and medulla.","Cortex = outer nodules · paracortex = dense zone under them · medulla = pale center","","Paracortex = T cells",0),
("user/lab7_thycortmed","🧅 Thymus: dark outer vs pale inner zone?","Dark outer = cortex · pale inner = medulla","","⚠️ DARK = CORTEX",0),
]
