OIA={
"Tensor fasciae latae":("Tuber coxae","Fascia lata","Tense the fascia lata (flex the coxal joint and extend the genual joint)"),
"Superficial gluteal":("Sacrotuberous ligament","Third trochanter of the femur","Abduct the limb (minor extensor action on the coxal joint)"),
"Middle gluteal":("Gluteal surface of the ilium","Greater trochanter","Extend the coxal joint; abduct the limb; rotate pelvic limb medially"),
"Piriformis":("Sacrum + first caudal vertebra","Greater trochanter","Extend the coxal joint"),
"Deep gluteal":("Body of ilium + ischiatic spine","Greater trochanter (deep to middle gluteal)","Abduct the limb and extend the coxal joint"),
"External obturator":("Ventral os coxae around the obturator foramen","Trochanteric fossa","Adduct and/or rotate the limb laterally at the coxal joint"),
"Internal obturator":("Dorsal os coxae around the obturator foramen","Trochanteric fossa","Rotate the limb laterally at the coxal joint"),
"Gemelli":("Lateral aspect of ischium","Trochanteric fossa","Rotate the limb laterally at the coxal joint"),
"Quadratus femoris":("Ventral aspect of ischium","Caudal femur near the trochanteric fossa","Extend coxal joint; adduct and/or rotate the limb laterally at the coxal joint"),
"Biceps femoris":("Ischiatic tuberosity + sacrotuberous ligament","Patella, tibia, and tuber calcanei","Extend the coxal joint; variable action on the genual joint; extend the tarsocrural joint"),
"Semitendinosus":("Ischiatic tuberosity","Tibia + tuber calcanei","Extend the coxal joint; variable action on the genual joint; extend the tarsocrural joint"),
"Semimembranosus":("On or near the ischiatic tuberosity","Distal femur + proximal tibia","Extend coxal joint; variable action on the genual joint"),
"Sartorius":("Crest of ilium","Medial aspect of the genual region","Flex the coxal joint; cranial part extends / caudal part flexes the genual joint"),
"Gracilis":("Pelvic symphysis","Medial aspect of the genual region","Adduct the limb, extend the coxal joint, flex the genual joint, extend the tarsocrural joint"),
"Pectineus":("Iliopubic eminence (prepubic tendon + cranial border of pubis)","Distal body of femur","Adduct the limb"),
"Adductor":("Ventral surface of os coxae","Caudal surface of femur","Adduct the limb and extend the coxal joint"),
"Quadriceps femoris":("Rectus femoris: ilium · other 3 heads: proximal femur","Tibial tuberosity (via patella + patellar ligament)","Flex the coxal joint (rectus femoris); extend the genual joint (all heads)"),
"Iliopsoas":("Ilium (iliacus) + lumbar vertebrae (psoas major)","Lesser trochanter","Flex the coxal joint"),
"Cranial tibial":("Lateral proximal tibia","Plantar base of MT 1 + 2","Flex the tarsocrural joint and rotate the paw laterally"),
"Long digital extensor":("Extensor fossa of femur","Extensor processes of the distal phalanges","Extend the genual joint; flex the tarsocrural joint; extend the digital joints"),
"Lateral digital extensor":("On/near proximal fibula","Lateral digits","Flex the tarsocrural joint; extend the digital joints"),
"Fibularis longus":("On/near the lateral collateral ligament of the genual joint","4th tarsal bone + plantar base of metatarsals","Flex the tarsocrural joint and rotate the paw medially"),
"Gastrocnemius":("Distal caudal femur (medial + lateral heads)","Tuber calcanei","Flex the genual joint; extend the tarsocrural joint"),
"Superficial digital flexor":("Lateral supracondylar tuberosity of femur","Tuber calcanei + bases of middle phalanges","Flex the genual joint; extend the tarsocrural joint; flex the MTP + PIP joints"),
"Deep digital flexor":("Proximal caudal tibia + fibula","Flexor tubercles of distal phalanges","Extend the tarsocrural joint; flex the digital joints"),
"Popliteus":("Popliteal fossa of femur","Proximal caudal tibia","Flex the genual joint; rotate leg medially"),
}
