OIA={
"Superficial pectoral":("Sternum","Crest of greater tubercle + cranial humeral border","Adduct the thoracic limb"),
"Deep pectoral":("Sternum","Greater + lesser tubercles of humerus","Adduct the thoracic limb and pull it caudally"),
"Brachiocephalicus":("Clavicular intersection","Cleidobrachialis: distal cranial humerus · Cleidocephalicus: mastoid part → mastoid process; cervical part → dorsal midline of neck","Pull thoracic limb cranially and/or depress + pull head and neck laterally"),
"Omotransversarius":("Wing of the atlas (cranial-most)","Distal spine of scapula (caudal-most)","Pull thoracic limb cranially and/or depress + pull head and neck laterally"),
"Trapezius":("Cervical part: dorsal neck · Thoracic part: dorsal thorax","Spine of the scapula","Elevate the thoracic limb"),
"Rhomboideus":("Thoracis: dorsal thorax · Cervicis: dorsal neck · Capitis: nuchal crest of occipital bone","Dorsal border of scapula and/or scapular cartilage","Elevate the thoracic limb"),
"Serratus ventralis":("Cervicis: cervical vertebrae · Thoracis: thoracic wall (ribs)","Serrated face of scapula","Support and/or elevate the trunk"),
"Latissimus dorsi":("Thoracolumbar fascia","Teres major tuberosity","Draw thoracic limb caudally; flex or extend the humeral joint"),
"Sternocephalicus":("Sternum","Mastoid part → mastoid process · Occipital part → occipital bone","Depress head and neck; draw head and neck laterally"),
"Sternohyoideus":("Sternum","Basihyoid bone","Pull tongue and larynx caudally"),
"Sternothyroideus":("Cranial sternum or ribcage","Thyroid cartilage","Pull tongue and larynx caudally"),
"Deltoideus":("Spine of scapula + acromion","Deltoid tuberosity","Flex the humeral joint"),
"Supraspinatus":("Supraspinous fossa","Greater tubercle","Extend the humeral joint"),
"Infraspinatus":("Infraspinous fossa","Greater tubercle","Flex the humeral joint (varies); abduct limb at humeral joint"),
"Teres minor":("Caudal border of scapula","Teres minor tuberosity","Flex the humeral joint"),
"Subscapularis":("Subscapular fossa","Lesser tubercle","Adduct limb at humeral joint"),
"Teres major":("Caudal border of scapula","Teres major tuberosity","Flex the humeral joint"),
"Coracobrachialis":("Coracoid process","Crest of the lesser tubercle","Adduct limb at humeral joint"),
"Biceps brachii":("Supraglenoid tubercle","Radial + ulnar tuberosities","Flex the cubital joint and extend the humeral joint"),
"Brachialis":("Brachial groove of humerus","Proximal radius and/or ulna","Flex the cubital joint"),
"Triceps brachii":("Long head: caudal border of scapula · Other heads: proximal humerus","Tuber olecrani","All heads: extend the cubital joint · Long head: also flex the humeral joint"),
"Tensor fasciae antebrachii":("Latissimus dorsi + its fascia","Tuber olecrani","Extend the cubital joint (+ tense deep antebrachial fascia)"),
"Anconeus":("Caudal aspect of distal humerus","Tuber olecrani","Extend the cubital joint"),
"Extensor carpi radialis":("Lateral epicondyle (+ its crest)","Dorsal base of MC 2 + 3","Extend the carpal joints"),
"Common digital extensor":("Lateral epicondyle","Extensor processes of distal phalanges","Extend the carpal and digital joints"),
"Lateral digital extensor":("Lateral epicondyle","Distal phalanges (± proximal/middle) of lateral digits","Extend the carpal and digital joints of the lateral digits"),
"Ulnaris lateralis":("Lateral epicondyle","Accessory carpal bone + lateral base of MC 5","FLEX the carpal joints; abduct the manus"),
"Supinator":("Lateral epicondyle","Body of radius","Supinate the manus"),
"Abductor digiti I longus":("Body of the ulna","Medial metacarpus","Abduct the first digit"),
"Brachioradialis":("Lateral epicondyle","Fascia near the carpus","Flex the cubital joint and supinate the manus"),
"Flexor carpi radialis":("Medial epicondyle","Palmar base of MC 2 + 3","Flex the carpal joints"),
"Flexor carpi ulnaris":("Medial epicondyle (humeral head) + olecranon (ulnar head)","Accessory carpal bone","Flex the carpal joints"),
"Superficial digital flexor":("Medial epicondyle","Middle phalanges (palmar)","Flex the carpal, MCP and PIP joints"),
"Deep digital flexor":("Humeral head: medial epicondyle · Radial head: radius · Ulnar head: ulna","Flexor tubercles of distal phalanges","Flex the carpal and digital joints"),
"Pronator teres":("Medial epicondyle","Medial body of radius","Weak elbow flexion + weak pronation"),
"Pronator quadratus":("Apposed surfaces of radius + ulna","(same: between radius + ulna)","Pronate the manus"),
"Interossei":("Palmar base of respective metacarpal","Palmar base of proximal phalanx (+ CDE tendon dorsally)","Flex and support the MCP joint"),
}
