# Practical 3 bold terms (professor's Notes-for-Lab lists, same order) + staged-reveal facts.
# Each entry: (term, [aliases], [(prompt, answer), ...]). Alias '=x' = exact label match only.
A='📍 Attachments?'; F='⚙️ Function?'; K='⭐ Key fact?'; FR='📍 Arises from?'; SU='🎯 Supplies / drains?'; W='📍 Where?'; CL='🩺 Clinical?'
L16=[
('Atlanto-axial joint',['atlantoaxial joint capsule','atlantoaxial joint'],[('🦴 Bones?','Atlas (C1) + axis (C2): dens sits in the fovea dentis of the atlas'),(F,'Rotation (the "no" joint)')]),
('Atlanto-occipital joint',['atlanto-occipital joint capsule','atlanto occipital joint capsule'],[('🦴 Bones?','Occipital condyles + cranial articular foveae of the atlas'),(F,'Flexion + extension (the "yes" joint); continuous with the atlantoaxial joint')]),
('Transverse ligament of the atlas',['transverse ligament of atlas'],[(A,'Side to side across the atlas, dorsal to the dens'),(F,'Holds the dens against the fovea dentis (off the spinal cord)')]),
('Apical ligament',['apical ligament of dens'],[(A,'Apex of the dens → basioccipital bone, between the occipital condyles'),(K,'Single, midline (alar ligaments are the paired lateral ones)')]),
('Alar ligament',['alar ligaments'],[(A,'Cranial end of the dens → occipital bone (paired, lateral to the apical lig.)'),(F,'Limit rotation at the atlantoaxial joint')]),
('Dorsal atlanto-axial ligament',['dorsal atlantoaxial ligament'],[(A,'Spine of the axis → dorsal arch of the atlas'),(K,'Thick; the dorsal tie between C1 and C2')]),
('Intervertebral disc',[],[(W,'Between vertebral bodies (fibrous joints)'),('🧩 Parts?','Anulus fibrosus (outer collagen rings) + nucleus pulposus (gel core)')]),
('Annulus fibrosus',['anulus fibrosus'],[]),
('Nucleus pulposus',[],[('🧩 What is it?','Inner gelatinous core of the intervertebral disc'),(CL,'Anulus is thicker VENTRALLY, so herniation goes dorsally into the vertebral canal')]),
('Ventral longitudinal ligament',[],[(W,'Ventral surface of the vertebral bodies, sacrum → axis'),(K,'Best developed in the caudal thoracic + lumbar regions')]),
('Dorsal longitudinal ligament',[],[(W,'Floor of the vertebral canal, ventral to the spinal cord, caudal → axis'),(K,'Widens + attaches over each anulus fibrosus; thicker than the ventral one')]),
('Yellow ligament',[],[(A,'Between adjacent vertebral arches'),(K,'Covers the epidural interarcuate space (between the articular processes)')]),
('Interspinous ligament',[],[(A,'Adjacent spinous processes, above the arches')]),
('Supraspinous ligament',[],[(A,'Apices of the spinous processes, Cd3 → T1'),(K,'Continues cranially as the nuchal ligament')]),
('Nuchal ligament',[],[(A,'Apex of the T1 spine → spine of the axis'),(K,'Paired + elastic; cranial continuation of the supraspinous lig.')]),
('Cranial costal foveae',[],[]),
('Caudal costal foveae',[],[]),
('Intercapital ligament',[],[(A,'Right rib head → across the dorsal anulus (ventral to the dorsal longitudinal lig.) → left rib head; ribs 2–10'),(F,'Holds the rib heads in their joints + adds disc containment → fewer disc extrusions T2–T10')]),
('Second cervical spinal nerve',['=c2','c2 ventral branch'],[('📍 Emerges?','Between the cleidomastoideus and omotransversarius, near the caudoventral border of the platysma'),('🌿 Branches?','Great auricular n. + transverse cervical n.')]),
('Great auricular nerve',[],[(FR,'Ventral branch of C2'),(SU,'Sensory: skin of the neck, ear, back of the head')]),
('Transverse cervical nerve',[],[(FR,'Ventral branch of C2'),(SU,'Sensory: skin of the ventral neck')]),
('External jugular vein',['right external jugular vein','=external jugular'],[('🩸 Formed by?','Linguofacial v. + maxillary v.'),('➡️ Drains into?','Joins the subclavian v. → brachiocephalic v.')]),
('Linguofacial vein',['=linguofacial'],[('➡️ Joins?','Maxillary v. → external jugular v.'),(K,'The confluence marks the caudal edge of the mandibular salivary gland')]),
('Maxillary vein',['=maxillary'],[('➡️ Joins?','Linguofacial v. → external jugular v.')]),
('Mandibular salivary gland',['mandibular gland'],[(W,'At the confluence of the linguofacial + maxillary vv.'),('👀 Look-alike?','Mandibular lymph nodes sit rostral to it')]),
('Mandibular lymph nodes',['mandibular lymph node'],[(W,'Rostral to the mandibular salivary gland, at the angle of the jaw'),(CL,'Palpable on physical exam')]),
('Superficial cervical lymph nodes',['superficial cervical lymph'],[(W,'Cranial to the shoulder, deep to the omotransversarius + cleidocephalicus'),(CL,'Palpable ("prescapular" nodes)')]),
('Accessory nerve (cranial nerve XI)',['accessory nerve','=xi'],[(SU,'Motor: trapezius (only nerve to it), omotransversarius, cleidocephalicus, sternocephalicus'),(W,'Deep to the sternocephalicus + cleidocephalicus; crosses C2; ends in the thoracic trapezius')]),
('Third cervical spinal nerve',['=c3','c3 ventral branch'],[(K,'Ventral branch passes through the omotransversarius to segmental neck muscles + skin')]),
('Fourth cervical spinal nerve',['=c4','c4 ventral branch'],[(K,'Ventral branch: segmental neck muscles + skin')]),
('Fifth cervical spinal nerve',['=c5','c5 ventral branch'],[(K,'Its deep branch hugs the scalenus = most cranial root of the phrenic n. (C5–C7)')]),
('Vagosympathetic nerve trunk',['vagosympathetic trunk'],[(W,'Carotid sheath, bound to the medial side of the common carotid a.'),('🧩 Contains?','Vagus n. + cervical sympathetic trunk in one sheath')]),
('Medial retropharyngeal lymph node',['medial retropharyngeal lymph node'],[(W,'Opposite the larynx, ventrolateral to the carotid sheath'),(SU,'Main collecting node of the head + cranial neck')]),
('Dorsal intercostal arteries',['dorsal intercostal artery','=intercostal artery','=intercostal'],[(FR,'First 3: costocervical trunk · remaining 9: aorta'),('🧭 Course?','Caudal border of each rib with the intercostal v. + n.; anastomose with ventral intercostal brr.')]),
('Ventral intercostal branches (internal thoracic a. + v.)',['ventral intercostal branch','ventral intercostal branches'],[(FR,'Internal thoracic a. + v.'),(CL,'DOUBLE at the sternal ribs (one cranial + one caudal to the cartilage) → mind both when entering the thorax')]),
('Intercostal nerves',['intercostal nerve'],[('🧩 Are?','Ventral branches of the thoracic spinal nerves'),(SU,'Intercostal muscles; sensory to the thoracic wall')]),
('Cranial thoracic mamma',[],[]),
('Caudal thoracic mamma',[],[]),
('Axilla',[],[]),
('Lateral thoracic artery',['lateral thoracic artery vein and nerve'],[(FR,'Axillary a.'),('🧭 Course?','Emerges from the axilla between latissimus dorsi + deep pectoral; supplies skin + cranial thoracic mamma')]),
('Lateral thoracic vein',['lateral thoracic artery vein and nerve'],[('➡️ Drains into?','Axillary v.')]),
('Lateral thoracic nerve',['lateral thoracic artery vein and nerve'],[('🧬 Spinal nerves?','Ventral branches of C8 + T1'),(SU,'Motor to the cutaneous trunci (find it on its ventral border)')]),
('Axillary lymph node',[],[(W,'Dorsal to the deep pectoral, caudal to the large axillary v.'),(SU,'Thoracic wall, deep thoracic limb, thoracic mammae')]),
]
T16=[("Annulus fibrosus (anulus)?","Outer circumferential collagen fibers of the intervertebral disc; thicker VENTRALLY → disc material herniates dorsally"),
("Cranial costal foveae vs caudal costal foveae?","Rib head joint (ribs 1–10): cranial costal fovea = craniodorsal body of the SAME-numbered vertebra · caudal costal fovea = caudodorsal body of the vertebra in FRONT"),
("Rib tubercle articulates with?","Transverse process of the same-numbered vertebra (all but the last few ribs)"),
("Cranial thoracic mamma: blood supply?","4th–6th ventral + lateral cutaneous vessels + lateral thoracic vessels (axillary a.); notes: largely perforating brr. of the internal thoracic a."),
("Caudal thoracic mamma: blood supply?","6th–7th cutaneous vessels + mammary brr. of the cranial superficial epigastric vessels; notes: largely perforating brr. of the internal thoracic a."),
("Axilla: boundaries?","Space between thoracic limb + thoracic wall · ventral: pectorals · dorsal: serratus ventralis attachment to the scapula"),
("Phrenic nerve roots?","Ventral branches of C5, C6, C7 (deep C5 branch on the scalenus = most cranial root)"),
("Where do intercostal vessels + nerve run? Why does it matter?","Caudal border of each rib → enter the thorax along the CRANIAL border of the rib; at sternal ribs ventral intercostal aa. are double"),
("Typical thoracic spinal nerve branching?","Spinal nerve → dorsal branch (epaxials, skin) + ventral branch (= intercostal n.) + ramus communicans to the sympathetic trunk; lateral + ventral cutaneous brr."),
("Mandibular salivary gland vs mandibular lymph nodes?","Gland: one big lobulated mass at the linguofacial–maxillary confluence · Nodes: smaller, rostral, along the linguofacial v."),
("Which nerve is the ONLY motor supply to the trapezius?","Accessory nerve (CN XI)")]
L17=[
('Cranial epigastric artery',[],[(FR,'Internal thoracic a. (terminal branch, with the musculophrenic a.)'),('🧭 Course?','Caudally deep to the rectus abdominis; gives the cranial superficial epigastric a.')]),
('Cranial superficial epigastric artery',['superficial cranial epigastric artery'],[(FR,'Cranial epigastric a.'),(SU,'Pierces rectus abdominis → skin + caudal thoracic/cranial abdominal mammae')]),
('Transversus thoracis m.',['transversus thoracis muscle','transversus thoracis'],[(W,'Deep surface of the sternum + costal cartilages, inside the thorax'),(K,'Opening the thorax cuts it into 3 pieces (each side + sternum)')]),
('Pleurae',[],[]),
('Pulmonary (visceral) pleura',['pulmonary pleura','visceral pleura'],[(W,'Covers the lung surface, into the fissures'),(K,'Continuous with the parietal pleura at the root of the lung + pulmonary ligament')]),
('Parietal pleura',[],[]),
('Costal pleura',['parietal costal pleura'],[(W,'Parietal pleura lining the ribs + intercostal muscles')]),
('Diaphragmatic pleura',[],[]),
('Mediastinal pleura',['parietal mediastinal pleura'],[(W,'Parietal pleura on each side of the mediastinum')]),
('Mediastinum',['cranial mediastinum','middle mediastinum','caudal mediastinum','dorsal mediastinum','ventral mediastinum'],[('🧩 What is it?','Space between the two pleural sacs (between the mediastinal pleurae)'),('📦 Contents?','Heart, thymus, trachea, esophagus, great vessels, nerves, lymph nodes')]),
('Pericardial mediastinal pleura',[],[(W,'Mediastinal pleura covering the fibrous pericardium (outer layer of the pericardial sac)')]),
('Plica venae cavae',['plica venae cavae'],[('🧩 What is it?','Fold of right pleura enclosing the caudal vena cava + right phrenic n.'),(K,'Accessory lobe lies in the mediastinal recess left of it')]),
('Root of the lung',[],[]),
('Pulmonary ligament',['left pulmonary ligament'],[('🧩 What is it?','Pleural fold: caudal lobe → mediastinum (on the right, usually also the accessory lobe)'),(K,'Caudal extension of the pleural reflection at the root of the lung')]),
('Thymus',[],[(W,'Cranial mediastinum, ventral to the great vessels'),(K,'Large in young dogs, regresses with age')]),
('Internal thoracic artery',['right internal thoracic artery','left internal thoracic artery','internal thoracic artery and vein','=internal thoracic'],[(FR,'Subclavian a.'),('🌿 Branches?','Ventral intercostal + perforating brr. → ends as musculophrenic + cranial epigastric aa.')]),
('Musculophrenic artery',[],[(FR,'Internal thoracic a. (terminal branch)'),('🧭 Course?','Along the costal arch at the diaphragm attachment')]),
('Left lung: cranial lobe, cranial part',['cranial part of cranial lobe','lung cranial part of cranial lobe','cranial part of left cranial lobe'],[(K,'Left cranial lobe = cranial + caudal parts (the left has no middle lobe)')]),
('Left lung: cranial lobe, caudal part',['caudal part of cranial lobe','left lung caudal part of cranial lobe'],[(K,'Caudal part of the left cranial lobe sits over the heart')]),
('Left lung: caudal lobe',['left caudal lobe','left lung caudal lobe'],[(K,'Largest left lobe; aortic impression on its medial surface')]),
('Right lung: cranial lobe',['right cranial lobe','right lung cranial lobe'],[(K,'Separated from the middle lobe by the cardiac notch')]),
('Right lung: middle lobe',['right middle lobe','right lung middle lobe'],[(CL,'Most common lobe to undergo TORSION (deep-chested dogs)'),(K,'Its segmental bronchi are cranial + caudal (others: dorsal + ventral)')]),
('Right lung: caudal lobe',['right caudal lobe','right lung caudal lobe'],[(K,'Largest right lobe; pulmonary ligament attaches here')]),
('Right lung: accessory lobe',['accessory lobe','accessory lobe right lung','accessory lobe of lung'],[(W,'Mediastinal recess, left of the plica venae cavae, caudal to the heart'),(K,'Only on the RIGHT lung')]),
('Cardiac notch',[],[(W,'Right lung, between the cranial + middle lobes'),(CL,'Heart touches the thoracic wall here (right side) → pericardiocentesis/auscultation window')]),
('Principal bronchi',['right principal bronchus','left principal bronchus','=lpb','=rpb'],[('🧩 Are?','Right + left primary bronchi from the tracheal bifurcation')]),
('Carina',['carina of trachea'],[('📏 Level?','Tracheal bifurcation ≈ T4–T5; heart base ventral to it'),('🩻 Radiology?','Displaced = atrial enlargement/heart-base mass; landmark for esophageal foreign bodies')]),
('Lobar bronchi',['=rb1','=rb2','=rb3','=rb4','=lb1','=lb2','bronchi'],[('🧩 Order?','Principal (1°) → lobar (2°) → segmental (3°) bronchi')]),
('Tracheobronchial lymph nodes',['left tracheobronchial lymph node'],[(W,'At the tracheal bifurcation (right, left, middle)'),(SU,'Lungs + bronchi')]),
('Aortic impression',['aortic groove'],[(W,'Medial surface of the LEFT lung, where the descending aorta lies')]),
('Cranial vena cava',['=cranial vena cava'],[('🩸 Formed by?','Right + left brachiocephalic vv. (+ costocervical vv.)'),('➡️ Ends?','Right atrium')]),
('Brachiocephalic vein',['left brachiocephalic vein','right brachiocephalic vein','=brachiocephalic','brachiocephalic vein'],[('🩸 Formed by?','External jugular v. + subclavian v.'),('➡️ Joins?','The opposite one → cranial vena cava')]),
('External jugular vein',['right external jugular vein','=external jugular'],[('➡️ Drains into?','Brachiocephalic v. (with the subclavian v.)')]),
('Subclavian vein',['left subclavian vein','=subclavian vein'],[('➡️ Joins?','External jugular v. → brachiocephalic v.')]),
('Right azygos vein',['azygos vein'],[(SU,'Dorsal thoracic wall (intercostal vv.) → cranial vena cava'),(W,'Right side, along the vertebral bodies; arches over the right lung root')]),
('Thoracic duct',[],[('🧭 Course?','Cisterna chyli → dorsal thorax (aorta–azygos) → crosses the left esophagus → left brachiocephalic v. / venous angle'),(K,'Straw/red-brown content, beaded walls; often double')]),
('Cisterna chyli',[],[(W,'Craniodorsal abdomen (not dissected now)'),('🧩 What?','Thin lymph sac that gives origin to the thoracic duct')]),
('Left tracheal trunk',['left tracheal trk','left tracheal trunk'],[(SU,'Lymph from the left head + neck (medial retropharyngeal LN) → thoracic duct/left venous angle'),(W,'In or parallel to the left carotid sheath')]),
('Right tracheal trunk',[],[]),
('Aorta',['=aorta','thoracic aorta'],[('🧩 Segments?','Ascending aorta → aortic arch → descending aorta')]),
('Ascending aorta',[],[(W,'From the left ventricle, medial to the pulmonary trunk; very short'),('🌿 Branches?','Right + left coronary aa.')]),
('Aortic arch',[],[(K,'Turns dorsally + left'),('🌿 Branches?','Brachiocephalic trunk, then left subclavian a.')]),
('Descending aorta',[],[(W,'Ventral to the vertebrae, caudally'),('🌿 Branches?','Dorsal intercostal aa. (4th onward), bronchoesophageal a.')]),
('Coronary arteries',['=coronary arteries'],[(FR,'Ascending aorta (aortic sinuses): the first branches of the aorta')]),
('Brachiocephalic trunk',[],[(FR,'Aortic arch (1st branch)'),('🌿 Branches?','LEFT common carotid, RIGHT common carotid, then continues as the right subclavian a.')]),
('Left common carotid artery',['left common carotid'],[(FR,'Brachiocephalic trunk ⚠️ (dog: NOT the aortic arch)')]),
('Right common carotid artery',['right common carotid','right and left common carotid arteries'],[(FR,'Brachiocephalic trunk')]),
('Right subclavian artery',['right subclavian'],[(FR,'Brachiocephalic trunk (its continuation)')]),
('Left subclavian artery',['left subclavian'],[(FR,'Aortic arch directly (2nd branch)')]),
('Vertebral artery',['right vertebral','left vertebral','right vertebral artery','vertebral artery and nerve'],[(FR,'Subclavian a. (1st branch)'),('🧭 Course?','Through the transverse foramina C6 → C1 to the brain + spinal cord')]),
('Costocervical trunk',['right costocervical trunk'],[(FR,'Subclavian a.'),('🌿 Branches?','Dorsal scapular, deep cervical, thoracic vertebral aa. (first 3 dorsal intercostals)')]),
('Superficial cervical artery',['=superficial cervical'],[(FR,'Subclavian a.'),(SU,'Superficial neck + shoulder (superficial cervical LN region)')]),
]
T17=[("Pleurae: two kinds?","Pulmonary (visceral) pleura on the lungs + parietal pleura lining the cavity"),
("Parietal pleura: 3 parts?","Costal · diaphragmatic · mediastinal"),
("Diaphragmatic pleura?","Parietal pleura covering the thoracic surface of the diaphragm"),
("Root of the lung: contents?","Principal bronchus, pulmonary a., pulmonary vv., bronchial vessels, nerves + lymphatics, sleeved in pleura at the hilus"),
("Right tracheal trunk drains to?","Right head + neck lymph → right venous angle (ext. jugular/brachiocephalic v.)"),
("Carina: vertebral level + why it matters?","T4–T5; heart base ventral to it → radiographic landmark for atrial enlargement, heart-base masses, esophageal foreign bodies"),
("Which lung lobe most often twists, and its odd bronchus feature?","Right middle lobe; segmental bronchi are cranial + caudal (not dorsal + ventral)"),
("Count the lobes: left vs right lung?","Left: cranial (cranial + caudal parts) + caudal · Right: cranial, middle, caudal, accessory"),
("Order of aortic arch branches (dog)?","Brachiocephalic trunk (→ L common carotid, R common carotid, R subclavian) → left subclavian a."),
("Branch order off each subclavian a.?","Vertebral a. → costocervical trunk → superficial cervical a. → internal thoracic a. → continues as axillary a."),
("Pulmonary ligament: extra attachment on the right?","Usually also the accessory lobe"),
("Thoracic duct: where to find it?","Thin duct on the LEFT face of the esophagus, just cranial to where the aorta crosses it")]
L18=[
('Aorta',['=aorta','thoracic aorta'],[('🧩 Segments?','Ascending aorta → aortic arch → descending aorta')]),
('Ascending aorta',[],[(W,'From the left ventricle, medial to the pulmonary trunk; short, hidden by fat/thymus')]),
('Aortic arch',[],[(K,'Sharp turn dorsally + left; where the big branches leave')]),
('Descending aorta',[],[(W,'Ventral to the vertebrae; gives the dorsal intercostal aa.')]),
('Coronary arteries',['=coronary arteries'],[(FR,'Aortic sinuses of the ascending aorta')]),
('Brachiocephalic trunk',[],[(FR,'Aortic arch (1st branch)'),('🌿 Branches?','Left common carotid, right common carotid, right subclavian a.')]),
('Left common carotid artery',['left common carotid'],[(FR,'Brachiocephalic trunk ⚠️ (not the aortic arch)')]),
('Right common carotid artery',['right common carotid','right and left common carotid arteries'],[(FR,'Brachiocephalic trunk')]),
('Right subclavian artery',['right subclavian'],[(FR,'Brachiocephalic trunk')]),
('Left subclavian artery',['left subclavian'],[(FR,'Aortic arch (2nd branch)')]),
('Vertebral artery',['right vertebral','left vertebral','right vertebral artery','vertebral artery and nerve'],[(FR,'Subclavian a. (1st branch)')]),
('Costocervical trunk',['right costocervical trunk'],[(FR,'Subclavian a.'),('🌿 Branches?','Dorsal scapular, deep cervical, thoracic vertebral aa.')]),
('Superficial cervical artery',['=superficial cervical'],[(FR,'Subclavian a.')]),
('Internal thoracic artery',['right internal thoracic artery','left internal thoracic artery','internal thoracic artery and vein','=internal thoracic'],[(FR,'Subclavian a.'),('➡️ Ends as?','Musculophrenic + cranial epigastric aa.')]),
('Bronchoesophageal artery',['right bronchoesophageal branch','left bronchoesophageal branch'],[(FR,'Most often the right 5th dorsal intercostal a. (very variable; ~50%)'),(SU,'NUTRITIONAL blood to bronchi + esophagus (functional = pulmonary a.)')]),
('Dorsal intercostal arteries',['dorsal intercostal artery','=intercostal artery','=intercostal'],[(FR,'First 3: costocervical trunk · rest: aorta')]),
('Phrenic nerves',['phrenic nerve','phrenic nerve to diaphragm'],[('🧬 Roots?','C5, C6, C7 ventral branches'),('🧭 Course?','Over the pericardium (right one in the plica venae cavae) → motor to the diaphragm')]),
('Nervous system',[],[]),('Central nervous system',[],[]),('Peripheral nervous system',[],[]),('Brain',[],[]),('Spinal cord',[],[]),('Cranial nerves',[],[]),('Spinal nerves',[],[]),
('Sensory (afferent) axons',[],[]),('Motor (efferent) axons',[],[]),('Motor portion',[],[]),('Somatic efferent neurons',[],[]),('Visceral efferent neurons',[],[]),('Neuron',[],[]),
('Autonomic nervous system',[],[]),('Ganglion',[],[]),('Nuclei',[],[]),('Preganglionic neuron',[],[]),('Postganglionic neuron',[],[]),
('Sympathetic division',[],[]),('Thoracolumbar',[],[]),('Parasympathetic division',['=parasympathetic'],[]),('Craniosacral',[],[]),('Ventral root',[],[]),('Dorsal root',[],[]),
('Spinal nerve',['thoracic nerve'],[('🌿 Branches?','Dorsal branch + ventral branch + ramus communicans')]),
('Ramus communicans',['communicating rami from cervicothoracic ganglion to ventral branches of cervical and thoracic nerves'],[('🔗 Connects?','Spinal nerve ↔ sympathetic trunk ganglion')]),
('Sympathetic trunk',['=sympathetic trunk'],[(W,'Chain of ganglia ventrolateral to the vertebral bodies')]),
('Sympathetic trunk ganglion',[],[('🧩 Contains?','Postganglionic sympathetic cell bodies (segmental)')]),
('Splanchnic nerves',['thoracic greater splanchnic nerve','lumbar splanchnics'],[('🧩 Carry?','Preganglionic sympathetics that pass THROUGH the trunk to collateral (prevertebral) ganglia, e.g. celiac')]),
('Cranial cervical ganglion',[],[(W,'Cranial end of the cervical sympathetic trunk, near the skull base'),(SU,'Postganglionic sympathetics to the head')]),
('Cervicothoracic ganglion',['left cervicothoracic ganglion'],[(W,'Thoracic inlet, on the longus colli (fused caudal cervical + 1st thoracic ganglia)'),('🌿 Gives?','Ansa subclavia, vertebral n., cardiac nn., rami to C7–T2')]),
('Brachial plexus',[],[]),
('Vertebral nerve',['vertebral artery and nerve'],[(FR,'Cervicothoracic ganglion'),('🧭 Course?','With the vertebral a. through the transverse foramina → sympathetics to cervical spinal nerves')]),
('Ansa subclavia',[],[('🧩 What?','Sympathetic loop around the SUBCLAVIAN A.: cervicothoracic ganglion ↔ middle cervical ganglion')]),
('Middle cervical ganglion',[],[(W,'Caudal end of the vagosympathetic trunk, at the ansa subclavia'),('🌿 Gives?','Cardiac nerves')]),
('Cardiac nerves',['cardiac autonomic nerves'],[('🧩 Carry?','Sympathetic + parasympathetic (vagal) fibers to heart + lungs, plus sensory fibers')]),
('Vagosympathetic trunk',[],[(W,'Carotid sheath, medial to the common carotid a.'),(K,'Separates into vagus + sympathetic trunk at the middle cervical ganglion')]),
('Vagus nerve',['left vagus nerve','=vagus nerve','=x'],[('🧩 What?','CN X: parasympathetic (+ sensory) to thoracic + abdominal viscera')]),
('Left recurrent laryngeal nerve',[],[('🔁 Loops around?','AORTIC ARCH (caudal to the ligamentum arteriosum) → back up the trachea'),('➡️ Becomes?','Caudal laryngeal n.')]),
('Right recurrent laryngeal nerve',[],[]),
('Caudal laryngeal nerve',[],[]),
('Dorsal branch of the vagus nerve',['dorsal branch of vagus nerve'],[('🔀 Joins?','Opposite dorsal branch → dorsal vagal trunk on the esophagus')]),
('Ventral branch of the vagus nerve',[],[]),
('Ventral vagal trunk',['ventral trunk of vagus nerve'],[('🧩 Formed by?','Right + left ventral vagal branches; runs ventrally on the esophagus → esophageal hiatus')]),
('Dorsal vagal trunk',[],[]),
('Pericardium',['=pericardium'],[('🧩 Layers (outer → inner)?','Pericardial mediastinal pleura · fibrous pericardium · parietal serous pericardium (clinical "sac")')]),
('Parietal serous pericardium',[],[(W,'Lines the fibrous pericardium; outer wall of the pericardial cavity')]),
('Fibrous pericardium',[],[(K,'Tough middle layer; anchored to the diaphragm by the phrenicopericardial lig.')]),
('Pericardial mediastinal pleura',[],[(W,'Outermost layer: mediastinal pleura on the fibrous pericardium')]),
('Phrenicopericardial ligament',['ventral mediastinum phrenicopericardial ligament'],[(A,'Apex of the fibrous pericardium → ventral diaphragm')]),
('Serous pericardium',[],[]),('Parietal layer (serous pericardium)',[],[]),('Visceral layer (serous pericardium)',['visceral serous pericardium epicardium'],[(K,'= Epicardium, on the heart surface')]),
('Epicardium',['visceral serous pericardium epicardium'],[(K,'= Visceral layer of the serous pericardium')]),
('Pericardial cavity',[],[('🧩 Between?','Parietal + visceral serous layers; thin fluid film'),(CL,'Effusion here → cardiac tamponade')]),
('Heart',['=heart'],[]),
('Auricular surface',[],[]),('Atrial surface',[],[]),
('Coronary groove',['coronary sulcus'],[('🧩 Where?','Between atria + ventricles; coronary vessels + fat')]),
('Interventricular grooves',[],[]),
('Paraconal interventricular groove',['paraconal interventricular sulcus','paraconal interventricular artery vein and groove'],[(W,'LEFT (auricular) surface, cranial'),('📦 Contains?','Paraconal IV br. of the left coronary a. + great cardiac v.')]),
('Subsinuosal interventricular groove',[],[]),
('Right atrium',[],[('🧩 Parts?','Sinus venarum + right auricle')]),
('Sinus venarum',[],[]),
('Right auricle',[],[(K,'Blind pouch of the right atrium, lined by pectinate mm.')]),
('Caudal vena cava',['=caudal vena cava'],[('➡️ Ends?','Sinus venarum of the right atrium')]),
('Coronary sinus',['opening of coronary sinus','=coronary sinus'],[('🧩 What?','Termination of the great cardiac v. → right atrium, just ventral to the caudal vena cava opening')]),
('Cranial vena cava',['=cranial vena cava'],[('➡️ Ends?','Sinus venarum of the right atrium')]),
('Right atrioventricular orifice',[],[]),
('Interatrial septum',[],[]),
('Intervenous tubercle',[],[(W,'Ridge between the cranial + caudal vena cava openings'),(F,'Diverts inflow toward the right AV orifice')]),
('Fossa ovalis',['fossa ovalis','limbus fossae ovalis'],[('🧩 What?','Depression in the interatrial septum = remnant of the fetal foramen ovale')]),
('Pectinate muscles',['pectinate muscles'],[(W,'Muscular ridges inside the auricle, from the crista terminalis')]),
('Endocardium',[],[]),
('Crista terminalis',[],[(W,'Ridge between the sinus venarum + the auricle; pectinate mm. arise from it')]),
('Pulmonary trunk',[],[(FR,'Right ventricle (conus arteriosus)'),('🌿 Divides?','Right + left pulmonary aa.; linked to the aorta by the ligamentum arteriosum')]),
('Right atrioventricular valve',['right atrioventricular valve','septal cusp of right atrioventricular valve','parietal cusp of right atrioventricular valve'],[('🧩 Cusps?','Parietal + septal (anchored by chordae tendineae to papillary mm.)')]),
('Chordae tendineae',[],[]),
('Papillary muscles',['papillary muscles'],[(F,'Anchor the chordae tendineae → keep AV cusps from everting')]),
('Trabeculae carneae',[],[(W,'Muscular ridges on the ventricular walls')]),
('Trabecula septomarginalis',[],[]),
('Conus arteriosus',[],[(W,'Funnel-shaped outflow of the right ventricle → pulmonary trunk')]),
('Pulmonary valve semilunar cusps',['pulmonary valve','left semilunar valvula of pulmonary valve'],[('🧩 Cusps?','3 semilunar: right, left, intermediate')]),
('Nodule',['nodule of septal semilunar valvula'],[(W,'Thickening at the middle of the free edge of each semilunar cusp')]),
('Left atrium',[],[]),
('Left auricle',[],[(K,'Seen on the LEFT (auricular) surface, cranial to the paraconal groove')]),
('Valve of the foramen ovale',[],[]),
('Left atrioventricular valve',['left atrioventricular valve','septal cusp of left atrioventricular valve','parietal cusp of left atrioventricular valve'],[('🧩 Cusps?','Septal (deeper) + parietal (more superficial)'),('⚠️ Notes trap?','Aortic valve lies DEEP to the septal cusp, not lateral to it')]),
('Ligamentum arteriosum',[],[('🧩 What?','Remnant of the fetal ductus arteriosus: pulmonary trunk → aorta'),(CL,'Left recurrent laryngeal n. hooks caudal to it; persistent = PDA')]),
('Aortic valve',['aortic valve','septal semilunar valvula of aortic valve','left semilunar valvula of aortic valve','right semilunar valvula of aortic valve'],[('🧩 Cusps?','3 semilunar: right, left, septal')]),
('Sinus of the aorta',[],[]),
('Right coronary artery',[],[(FR,'Right aortic sinus'),('🧭 Course?','Right side of the coronary groove')]),
('Left coronary artery',[],[(FR,'Left aortic sinus; short trunk'),('🌿 Branches?','Circumflex br. + paraconal IV br. + septal br. (dominant in the dog)')]),
('Circumflex branch',['circumflex branch of left coronary artery','circumflex branch'],[('🧭 Course?','Left coronary groove → caudally to the right; gives the subsinuosal IV br.')]),
('Subsinuosal interventricular branch',['subsinuosal interventricular branch of left coronary artery','subsinuosal interventricular branch'],[(W,'Subsinuosal groove on the RIGHT (atrial) surface'),(FR,'Circumflex br. of the left coronary a.')]),
('Paraconal interventricular branch',['paraconal interventricular branch'],[(W,'Paraconal groove on the LEFT (auricular) surface')]),
('Septal branch',[],[(SU,'Interventricular septum (from the left coronary a.)')]),
('Great cardiac vein',[],[('🧭 Course?','Paraconal groove → left coronary groove → coronary sinus')]),
]
T18=[("Nervous system: 2 parts?","Central (brain + spinal cord) + peripheral (cranial nerves, spinal nerves, ganglia)"),
("Central nervous system = ?","Brain + spinal cord"),("Peripheral nervous system = ?","Cranial + spinal nerves and their ganglia, outside the CNS"),
("Brain vs spinal cord: which nerves leave each?","Brain → 12 pairs of cranial nerves · spinal cord → spinal nerves"),
("Spinal nerve: how formed?","Dorsal root (sensory, with spinal ganglion) + ventral root (motor) join at the intervertebral foramen"),
("Afferent vs efferent?","Afferent (sensory) = TO the CNS · Efferent (motor) = FROM the CNS (A comes before E: arrive, exit)"),
("Motor portion: 2 kinds of neurons?","Somatic efferent (skeletal muscle) + visceral efferent (smooth muscle, cardiac muscle, glands)"),
("Somatic efferent neurons vs visceral efferent neurons: how many neurons CNS → target?","Somatic: ONE neuron · Visceral (autonomic): TWO neurons (pre + post) with a ganglion synapse"),
("Neuron = ?","Cell body + its processes (axon + dendrites)"),
("Autonomic nervous system: job?","Controls involuntary structures (smooth + cardiac muscle, glands); 2-neuron efferent chain"),
("Ganglion vs nucleus?","Ganglion = cell bodies OUTSIDE the CNS · Nucleus = cell bodies INSIDE the CNS"),
("Preganglionic neuron vs postganglionic neuron?","Pre: cell body in CNS, axon to a ganglion · Post: cell body in the ganglion, axon to the target"),
("Sympathetic division = which outflow?","Thoracolumbar (thoracic + cranial lumbar spinal cord segments)"),
("Parasympathetic division = which outflow?","Craniosacral (brainstem nuclei of CN III, VII, IX, X + sacral segments)"),
("Ventral root vs dorsal root?","Ventral = motor (efferent) out · Dorsal = sensory (afferent) in, has the spinal ganglion"),
("Sympathetic path from spinal cord to a thoracic organ?","Ventral root → spinal nerve → ramus communicans → sympathetic trunk ganglion → (cardiac nn.) → heart/lungs"),
("Splanchnic nerves vs cardiac nerves?","Splanchnic: PREganglionic, pass through the trunk to collateral ganglia (abdomen) · Cardiac: mostly POSTganglionic from cervical ganglia"),
("Brachial plexus: spinal nerves?","Ventral branches of C6, C7, C8, T1 (± C5, T2)"),
("Right recurrent laryngeal nerve loops around?","Right SUBCLAVIAN a. (left loops around the aortic arch)"),
("Caudal laryngeal nerve?","Terminal part of the recurrent laryngeal n. → intrinsic laryngeal muscles (laryngeal paralysis)"),
("Recurrent laryngeal nerves carry which fibers?","Parasympathetic preganglionic + special visceral efferent (to striated laryngeal muscle) + sensory"),
("Ventral branch of the vagus nerve?","Each vagus splits dorsal to the heart base; R + L ventral branches → ventral vagal trunk on the esophagus"),
("Dorsal vagal trunk?","R + L dorsal vagal branches unite dorsal to the esophagus → through the esophageal hiatus"),
("Serous pericardium: 2 layers?","Parietal layer (lines the fibrous pericardium) + visceral layer = epicardium"),
("Parietal layer of the serous pericardium?","Inner lining of the fibrous pericardium; outer wall of the pericardial cavity"),
("Heart: auricular vs atrial surface?","Auricular = LEFT surface (both auricles seen) · Atrial = RIGHT surface"),
("Interventricular grooves: names + sides?","Paraconal = LEFT/auricular surface · Subsinuosal = RIGHT/atrial surface"),
("Subsinuosal interventricular groove: contents?","Subsinuosal IV br. (from the circumflex br., left coronary a.) + middle cardiac v."),
("Sinus venarum?","Main part of the right atrium receiving the venae cavae, coronary sinus + azygos v."),
("Right atrioventricular orifice?","Opening from the right atrium into the right ventricle, guarded by the right AV valve"),
("Interatrial septum?","Wall between the atria; bears the fossa ovalis (right side)"),
("Endocardium?","Inner lining of the heart chambers + valves"),
("Chordae tendineae?","Tendinous cords: AV valve cusps → papillary muscles"),
("Trabecula septomarginalis (moderator band)?","Cord across the RIGHT ventricle: septal papillary m. → parietal wall; carries Purkinje fibers. Spot it BEFORE reflecting the wall"),
("Left atrium: receives?","Pulmonary veins"),
("Valve of the foramen ovale?","Flap on the LEFT side of the interatrial septum; fetal one-way valve over the foramen ovale"),
("Sinus of the aorta?","Dilations above the aortic cusps; coronary aa. arise from the right + left sinuses"),
("Heart vs carina vs vertebrae?","Heart base lies ventral to the carina (T4–T5)"),
("Nutritional vs functional blood to the lung?","Nutritional: bronchoesophageal a. · Functional (gas exchange): pulmonary a."),
("Cutting a somatic nerve or vessel can also cut what?","Sympathetics that travel with it → loss of autonomic control distally")]
