# Practical 3 bold terms = Bethany's Canvas screenshots ONLY, same order (column 1 top→bottom, then 2, then 3).
# (term, [aliases], note). Facts come from p3data.FACTS by term.
S16=[('Atlanto-occipital joint',[]),('Apical ligament',[]),('Intervertebral disc',[]),('Ventral longitudinal ligament',[]),('Interspinous ligaments',['interspinous ligament']),('Cranial costal foveae',[]),('Second cervical spinal nerve',[]),('External jugular vein',['external jugular v','rt external jugular v']),('Mandibular salivary gland',['mandibular gland']),('Accessory nerve (cranial nerve XI)',['accessory nerve','accessory cranial nerve','cnxi','cn xi']),
('Fifth cervical spinal nerve',[]),('Dorsal intercostal arteries',['intercostal aa','intercostal arteries']),('Intercostal nerves',[]),('Axilla',[]),('Lateral thoracic nerve',[]),('Atlantoaxial joint',['atlanto-axial joint']),('Alar ligaments',['alar ligament']),('Annulus fibrosus',['anulus fibrosus']),('Dorsal longitudinal ligament',[]),('Supraspinous ligament',[]),
('Caudal costal foveae',[]),('Great auricular nerve',[]),('Linguofacial vein',['linguofacial v']),('Mandibular lymph nodes',[]),('Third cervical spinal nerve',[]),('Vagosympathetic trunk',['vagosympathetic nerve trunk']),('Ventral intercostal branches',['ventral intercostal branches from the internal thoracic artery and vein']),('Cranial thoracic mamma',['cranial thoracic']),('Lateral thoracic artery',[]),('Axillary lymph node',[])]
S17=[('Cranial epigastric artery',[]),('Pleurae',[]),('Costal pleura',[]),('Mediastinum',[]),('Root of the lung',[]),('Internal thoracic artery',['internal thoracic a']),('Left cranial lobe: cranial and caudal parts',['cranial part cranial lobe','caudal part caudal lobe','cranial part of left cranial lung lobe','caudal part of left cranial lung lobe','cranial lobe cranial part','cranial lobe caudal part']),('Right cranial lobe',['rt cr lung lobe']),('Right accessory lobe',['right accessory lung lobe','=accessory lobe']),('Carina',[]),
('Tracheobronchial lymph nodes',[]),('Brachiocephalic veins',['brachiocephalic vein','rt brachiocephalic v']),('Right azygos vein',['right azygous vein']),('Left tracheal trunk',['left right tracheal trunk']),('Ascending aorta',[]),('Coronary arteries',['left coronary artery','right coronary artery']),('Right common carotid artery',['right common carotid a']),('Vertebral artery',['vertebral a']),('Cranial superficial epigastric artery',[]),('Pulmonary (visceral) pleura',['pulmonary visceral pleura']),
('Diaphragmatic pleura',[]),('Pericardial mediastinal pleura',['outer pericardial mediastinal pleura']),('Pulmonary ligament',[]),('Musculophrenic artery',[]),('Left caudal lobe',['left caudal lung lobe']),('Right middle lobe',['rt middle lung lobe']),('Cardiac notch',[]),('Lobar bronchi',[]),('Aortic impression',[]),('External jugular veins',['external jugular vein','external jugular v','rt external jugular v']),
# --- page 2 screenshot ---
('Thoracic duct',[]),('Right tracheal trunk',['left right tracheal trunk']),('Aortic arch',[]),('Brachiocephalic trunk',[]),('Right subclavian artery',['right subclavian a']),('Costocervical trunk',[]),('Transversus thoracis',[]),('Parietal pleura',[]),('Mediastinal pleura',[]),('Plica venae cavae',['plica vena cava']),
('Thymus',[]),('Left lung',[]),('Right lung',[]),('Right caudal lobe',['rt cd lung lobe','right caudal lung lobe']),('Principal bronchi',[]),('Segmental bronchi',[]),('Cranial vena cava',[]),('Subclavian veins',['subclavian vein','rt subclavian v']),('Cisterna chyli',[]),('Aorta',['=aorta']),
('Descending aorta',[]),('Left common carotid artery',['left common carotid a']),('Left subclavian artery',[]),('Superficial cervical artery',['superficial cervical a'])]
S18=[('Aorta',['=aorta']),('Descending aorta',[]),('Left common carotid artery',['left common carotid a']),('Left subclavian artery',[]),('Superficial cervical artery',['superficial cervical a']),('Dorsal intercostal arteries',['intercostal aa','intercostal arteries']),('Peripheral nervous system',[]),('Cranial nerves',[]),('Motor (efferent) axons',[]),('Neuron',[]),
('Nucleus',[]),('Sympathetic division',[]),('Craniosacral',[]),('Ramus communicans',[]),('Splanchnic nerves',[]),('Cervicothoracic ganglion',[]),('Ansa subclavia',[]),('Vagosympathetic trunk',[]),('Right recurrent laryngeal nerve',[]),('Ventral branch of the vagus nerve',['ventral branch of vagus nerve','=ventral branch']),
('Pericardium',['=pericardium']),('Pericardial mediastinal pleura',['outer pericardial mediastinal pleura']),('Pericardial cavity',[]),('Atrial surface',[]),('Paraconal interventricular groove',[]),('Sinus venarum',[]),('Coronary sinus',[]),('Interatrial septum',[]),('Pectinate muscles',['pectinate muscle']),
# --- page 2 screenshot ---
('Papillary muscles',['papillary muscle']),('Conus arteriosus',[]),('Nodule',[]),('Valve of the foramen ovale',[]),('Aortic valve',[]),('Left coronary artery',[]),('Paraconal interventricular branch',[]),('Ascending aorta',[]),('Coronary arteries',['left coronary artery','right coronary artery']),('Right common carotid artery',['right common carotid a']),
('Vertebral artery',['vertebral a']),('Internal thoracic artery',['internal thoracic a']),('Phrenic nerves',['phrenic nerve']),('Brain',[]),('Spinal nerves',[]),('Somatic efferent neurons',[]),('Autonomic nervous system',[]),('Preganglionic neuron',[]),('Thoracolumbar',[]),('Ventral root',[]),
('Sympathetic trunk',[]),('Prevertebral (collateral) ganglia',['prevertebral ganglia','collateral ganglia']),('Brachial plexus',[]),('Middle cervical ganglion',[]),('Vagus nerve',['=vagus nerve','left vagus nerve']),('Caudal laryngeal nerve',[]),('Ventral vagal trunk',[]),('Parietal serous pericardium',['inner parietal serous pericardium']),('Phrenicopericardial ligament',[]),('Heart',['=heart']),
# --- page 3 screenshot ---
('Coronary groove',['coronary sulcus']),('Subsinuosal interventricular groove',[]),('Right auricle',[]),('Cranial vena cava',[]),('Intervenous tubercle',[]),('Endocardium',[]),('Right atrioventricular valve',['right av valve']),('Trabeculae carneae',[]),('Pulmonary valve',['pulmonary valve semilunar cusp']),('Left atrium',[]),
('Left atrioventricular valve',['left av valve']),('Sinus of the aorta',[]),('Circumflex branch',[]),('Septal branch',[]),('Aortic arch',[]),('Brachiocephalic trunk',[]),('Right subclavian artery',['right subclavian a']),('Costocervical trunk',[]),('Bronchoesophageal artery',['bronchoesophageal a']),('Central nervous system',[]),
('Spinal cord',[]),('Sensory (afferent) axons',[]),('Visceral efferent neurons',[]),('Ganglion',['=ganglion']),('Postganglionic neuron',[]),('Parasympathetic division',[]),('Dorsal root',[]),('Sympathetic trunk ganglion',['sympathetic trunk ganglia']),('Cranial cervical ganglion',[]),('Vertebral nerve',[]),
# --- page 4 screenshot ---
('Cardiac nerves',[]),('Left recurrent laryngeal nerve',[]),('Dorsal branch of the vagus nerve',['dorsal branch of vagus nerve','=dorsal branch']),('Dorsal vagal trunk',[]),('Fibrous pericardium',['middle fibrous pericardium']),('Visceral serous pericardium (epicardium)',['visceral epicardium serous pericardium','epicardium']),('Auricular surface',[]),('Interventricular grooves',['interventricular groove']),('Right atrium',[]),('Caudal vena cava',[]),
('Right atrioventricular orifice',[]),('Fossa ovalis',[]),('Crista terminalis',[]),('Chordae tendineae',['chordae tendinae']),('Trabecula septomarginalis (moderator band)',['trabecula septomarginalis','moderator band']),('Semilunar cusps',['semilunar cusp','pulmonary valve semilunar cusps']),('Left auricle',[]),('Ligamentum arteriosum',[]),('Right coronary artery',[]),('Subsinuosal interventricular branch',[]),
('Great cardiac vein',[])]
NOTE={}
EXACT={'Nucleus','Ganglion','Heart','Aorta'}  # term name itself must match a label exactly
CONCEPT={
'Central nervous system':'Brain + spinal cord',
'Spinal cord':'CNS within the vertebral canal; gives rise to the spinal nerves (dorsal + ventral roots)',
'Sensory (afferent) axons':'Carry impulses TO the CNS; cell bodies in the dorsal root (spinal) ganglion',
'Visceral efferent neurons':'Motor to smooth muscle, cardiac muscle + glands; TWO-neuron chain (= autonomic)',
'Ganglion':'Cluster of neuron cell bodies OUTSIDE the CNS (inside the CNS = nucleus)',
'Postganglionic neuron':'Cell body in an autonomic ganglion; axon runs to the target organ',
'Parasympathetic division':'Craniosacral outflow (CN III, VII, IX, X + sacral segments); long preganglionic, short postganglionic',
'Dorsal root':'Sensory (afferent) axons entering the spinal cord; carries the spinal (dorsal root) ganglion',
'Endocardium':'Inner lining of the heart chambers + valves',
'Interventricular grooves':'Paraconal = LEFT/auricular surface · Subsinuosal = RIGHT/atrial surface',
'Semilunar cusps':'3 cusps each in the pulmonary + aortic valves; a nodule sits mid free edge',
'Sinus of the aorta':'Dilations above the aortic valve cusps; coronary aa. arise from the right + left sinuses',
'Segmental bronchi':'Tertiary (3°) bronchi from each lobar bronchus. Right middle lobe: cranial + caudal segmental bronchi (all others dorsal + ventral)',
'Left lung':'2 lobes: cranial (cranial + caudal parts) + caudal',
'Right lung':'4 lobes: cranial, middle, caudal, accessory',
'Cisterna chyli':'Thin-walled lymph sac in the craniodorsal abdomen; gives origin to the thoracic duct',
'Right tracheal trunk':'Lymph from the right head + neck → right venous angle (external jugular/brachiocephalic v.)',
'Brain':'Part of the CNS in the cranial cavity; gives rise to the 12 pairs of cranial nerves',
'Spinal nerves':'Formed by dorsal (sensory) + ventral (motor) roots at the intervertebral foramen → dorsal branch, ventral branch, ramus communicans',
'Somatic efferent neurons':'Motor to striated skeletal muscle; ONE neuron from CNS to muscle (visceral efferent = two)',
'Autonomic nervous system':'Visceral efferent control of involuntary structures (smooth + cardiac muscle, glands); 2-neuron chain: preganglionic → ganglion → postganglionic',
'Preganglionic neuron':'Cell body in the CNS; axon runs to an autonomic ganglion (postganglionic = cell body in the ganglion → target)',
'Thoracolumbar':'= Sympathetic outflow: preganglionic cell bodies in thoracic + cranial lumbar spinal cord segments',
'Ventral root':'Motor (efferent) axons leaving the spinal cord; dorsal root = sensory, has the spinal ganglion',
'Prevertebral (collateral) ganglia':'Sympathetic ganglia away from the trunk in the abdomen, usually on a blood vessel (e.g. celiac, cranial mesenteric); receive preganglionics via splanchnic nn.',
'Caudal laryngeal nerve':'Terminal part of the recurrent laryngeal n. → intrinsic laryngeal muscles (laryngeal paralysis)',
'Heart':'Base = dorsal (great vessels), apex = ventral; auricular surface = left, atrial surface = right; base lies ventral to the carina (T4–T5)', # 🧠 answers for screenshot terms that can't be photographed
'Peripheral nervous system':'Cranial nerves + spinal nerves and their ganglia, outside the CNS (CNS = brain + spinal cord)',
'Cranial nerves':'12 pairs of nerves arising from the brain',
'Motor (efferent) axons':'Carry impulses FROM the CNS to effectors (muscle, glands). Afferent = sensory, TO the CNS',
'Neuron':'Cell body + its processes (axon + dendrites)',
'Nucleus':'Cluster of neuron cell bodies INSIDE the CNS (outside the CNS = ganglion)',
'Sympathetic division':'Thoracolumbar outflow: preganglionic cell bodies in thoracic + cranial lumbar spinal cord segments',
'Craniosacral':'= Parasympathetic outflow: brainstem nuclei of CN III, VII, IX, X + sacral spinal cord segments',
'Ramus communicans':'Connects a spinal nerve with its sympathetic trunk ganglion',
'Splanchnic nerves':'PREganglionic sympathetic axons that pass through the sympathetic trunk without synapsing → collateral (prevertebral) ganglia, e.g. celiac',
'Pleurae':'Serous membranes of the thorax: pulmonary (visceral) pleura on the lungs + parietal pleura (costal, diaphragmatic, mediastinal)',
'Mediastinum':'Space between the two pleural sacs (between the mediastinal pleurae): heart, thymus, trachea, esophagus, great vessels, nerves',
'Carina':'Partition at the tracheal bifurcation into the principal bronchi ≈ T4–T5; heart base is ventral to it (radiographic landmark)',
'Diaphragmatic pleura':'Parietal pleura covering the thoracic surface of the diaphragm',
'Root of the lung':'Principal bronchus + pulmonary a. + pulmonary vv. + bronchial vessels, nerves, lymphatics entering the hilus, sleeved in pleura',
'Axilla':'Space between the thoracic limb and thoracic wall; ventral = pectorals, dorsal = serratus ventralis attachment to the scapula',
'Ventral intercostal branches':'From the internal thoracic a. + v.; DOUBLE at the sternal ribs (cranial + caudal to each costal cartilage); anastomose with the dorsal intercostal aa.',
'Intercostal nerves':'Ventral branches of the thoracic spinal nerves; run on the caudal border of each rib; supply intercostal mm. + thoracic wall skin',
'Atlanto-occipital joint':'Occipital condyles + atlas · flexion/extension ("yes" joint); continuous with the atlantoaxial joint',
'Atlantoaxial joint':'Atlas + axis (dens in the fovea dentis) · rotation ("no" joint)',
'Apical ligament':'Apex of the dens → basioccipital bone between the occipital condyles (single, midline)',
'Alar ligaments':'Cranial end of the dens → occipital bone (paired, lateral to the apical lig.); limit rotation',
'Intervertebral disc':'Fibrous joint between vertebral bodies: anulus fibrosus (outer) + nucleus pulposus (inner gel)',
'Annulus fibrosus':'Outer collagen rings of the disc; thicker VENTRALLY → disc herniates dorsally into the vertebral canal',
'Ventral longitudinal ligament':'Ventral surface of the vertebral bodies, sacrum → axis; best developed caudal thoracic + lumbar',
'Dorsal longitudinal ligament':'Floor of the vertebral canal, ventral to the spinal cord, caudal → axis; widens over each anulus',
'Interspinous ligaments':'Connect adjacent spinous processes',
'Supraspinous ligament':'Apices of the spinous processes, Cd3 → T1; continues cranially as the nuchal ligament',
'Cranial costal foveae':'On the craniodorsal body of the SAME-numbered vertebra: articulates with the rib head (ribs 1–10)',
'Caudal costal foveae':'On the caudodorsal body of the vertebra in FRONT: shares the rib head joint (ribs 1–10)',
}
