# Build: Veterinary Systems I · Lecture area + old lecture exams as tap-to-check practice
# Run from repo root: python3 tools/sys_lecture.py
import html,time,re,json
E=html.escape; V=str(int(time.time()))
# (stem, [options], [correct indexes], why, sure)   sure=0 → ⚠️ flagged
X2025=[
("A dog is given a β-blocker. Which change is most likely observed in the SA node?",["Decreased slope of phase 0 depolarization","Hyperpolarization of the maximum diastolic potential","Increased cAMP and faster spontaneous depolarization","Reduced slope of phase 4 depolarization"],[3],"β-blocker → less cAMP → less funny current (HCN) → flatter phase 4 → slower heart rate",1),
("In a normal heart, why does the SA node act as the pacemaker rather than the AV node or Purkinje fibers?",["It depolarizes more rapidly than other cardiac tissues","It has the shortest refractory period","It receives greater sympathetic stimulation","It has the largest resting membrane potential"],[0],"Fastest spontaneous phase 4 depolarization reaches threshold first and sets the rate (overdrive suppression)",1),
("Acetylcholine signaling will cause which of the following in nodal cells?",["Increase the slope of phase 0","Increase the slope of phase 2","Reduce the slope of phase 3","Reduce the slope of phase 4"],[3],"ACh → M2 → ↓cAMP + ↑K⁺ permeability → flatter phase 4 → slower rate",1),
("A depolarization wave moving perpendicular to the axis of a lead will produce what ECG effect?",["Large positive deflection","Large negative deflection","Small or no deflection"],[2],"Perpendicular = isoelectric lead",1),
("Which of the following represents the depolarization of the AV node?",["P wave","Q wave","S wave","T wave","None of the above"],[4],"AV node depolarization is too small to see; it sits in the PR segment",1),
("The bizarre complexes in the ECG marked “C” are likely:",["Inverted T waves suggesting infarction","Overlapped P and T waves","P waves and QRS complexes stacked on top of each other","QRS complexes (ventricular depolarization) that did not start at the AV node"],[3],"Wide, bizarre QRS = ventricular origin (premature ventricular complex). (Answer from the stem; the ECG image isn't in the upload.)",1),
("You have a patient with atrial fibrillation. Which could be appropriate treatments? (select all that apply)",["Cardioversion","Class 1 antiarrhythmic (lidocaine)","Class 2 antiarrhythmic (propranolol)","Class 4 antiarrhythmic (diltiazem)"],[0,2,3],"LC21–22: rate control with β-blockers (class 2) and Ca²⁺ channel blockers (class 4); cardioversion is used for atrial fibrillation. Lidocaine = ventricular arrhythmias",1),
("On a well-prepared canine blood smear, the central pallor of erythrocytes is most evident because:",["Canine erythrocytes are slightly concave, increasing light transmission at the center","Canine erythrocytes have a higher hemoglobin concentration at the center","Erythrocytes shrink due to the hypertonic nature of plasma","Platelet overlay causes optical lightening at the center"],[0],"Biconcave disc → thinner center → paler",1),
("When comparing fields of a canine smear, an increased number of polychromatophilic cells would indicate:",["Degenerative anemia","Immune-mediated hemolysis","Neutrophilia","Regenerative anemia","Thrombocytopenia"],[3],"Polychromatophils = reticulocytes = marrow is responding",1),
("What is a significant difference in bovine blood compared to most mammals?",["Bovine erythrocytes are larger and more uniform","Lymphocytes often outnumber neutrophils","Platelets are larger and more granular","Rouleaux formation is common"],[1],"Ruminants: lymphocyte-predominant leukogram",1),
("What is a significant difference in camelid erythrocytes compared to most mammals?",["Are elliptical and non-nucleated","Contain central nuclei","Are larger and more spherical","Have highly irregular membranes"],[0],"Camelid RBCs = small, elliptical, no nucleus",1),
("A parrot’s blood smear shows abundant heterophils with rod-shaped granules. This leukocyte population functions analogously to mammalian:",["Basophils","Eosinophils","Monocytes","Neutrophils"],[3],"Heterophil = bird/reptile neutrophil",1),
("Bone marrow smear: a cell with basophilic cytoplasm and a smaller but relatively euchromatic, central nucleus. This cell is likely a:",["Band cell","Metarubricyte","Myelocyte","Reticulocyte","Rubricyte"],[4],"LC33: rubricyte = smaller nucleus + basophilic cytoplasm · metarubricyte = small DENSE nucleus, more eosinophilic",1),
("Bone marrow smear: a cell with eosinophilic granules and an oblong (but not dented) nucleus. This cell is likely a:",["Band cell","Metamyelocyte","Metarubricyte","Myelocyte","Rubricyte"],[3],"Myelocyte = round/oblong nucleus + specific granules · metamyelocyte = dented (kidney) · band = U-shaped",1),
("CBC from a dog: very low total neutrophils and increased band cells. This is consistent with:",["Degenerative anemia","Degenerative left shift","Regenerative anemia","Regenerative left shift"],[1],"Bands > or with LOW segs = degenerative left shift (marrow can't keep up)",1),
("Low hematocrit, increased MCV, decreased MCHC. Which could cause this? (select all that apply)",["Bone marrow insufficiency","Endocrine insufficiency (low EPO)","Hemolytic disorder","Internal bleeding","Iron deficiency"],[2,3],"Big, pale cells = reticulocytes = REGENERATIVE anemia → blood loss or hemolysis. Marrow/EPO problems are non-regenerative",1),
("In what locations can hematopoiesis occur (including extreme/pathological conditions)? (select all that apply)",["Bone marrow","Kidney","Spleen","Thymus"],[0,2],"Bone marrow normally; spleen (and liver) = extramedullary hematopoiesis. Kidney makes EPO but not blood cells. ⚠️ Confirm thymus with Dr. Basel",0),
("Which signaling molecule is an antithrombotic signal that is lost when the endothelium is damaged?",["Endothelin","Prostacyclin (PGI2)","Serotonin","Thromboxane A2 (TXA2)","von Willebrand factor (vWF)"],[1],"Healthy endothelium makes PGI2 (and NO) to keep platelets away",1),
("Which binds to GPIb to facilitate strong adhesion of platelets to damaged vessel walls?",["Fibrinogen (I)","Plasmin","Thrombin (IIa)","Tissue factor (TF)","von Willebrand factor (vWF)"],[4],"vWF bridges exposed collagen ↔ platelet GPIb",1),
("Which clotting factor pathway is activated by release of tissue factor (TF, III)?",["Common pathway","Effector pathway","Extrinsic pathway","Intrinsic pathway"],[2],"TF + VIIa = extrinsic",1),
("Which protein is important for clot degradation and formation of fibrin degradation products?",["Antithrombin","Plasmin","Protein C/S","TFPI","von Willebrand factor (vWF)"],[1],"Plasmin = fibrinolysis",1),
("Corgi with repeated epistaxis and petechiae. Buccal mucosal bleeding time is prolonged; prothrombin time is normal. Likely:",["Vascular spasm disorder","Primary hemostasis disorder","Secondary hemostasis disorder","Tertiary hemostasis disorder"],[1],"Petechiae + long BMBT + normal PT = platelet/vWF problem (primary). Corgi → think von Willebrand disease",1),
("Which cytokine most directly stimulates eosinophil proliferation and differentiation?",["IL-3","IL-4","IL-5","G-CSF"],[2],"IL-5 = eosinophils · G-CSF = neutrophils · IL-3 = basophils",1),
("Which immune cell type primarily kills virus-infected or tumor cells without prior antigen exposure?",["Cytotoxic T-cell","NK cell","Neutrophil","Plasma cell"],[1],"NK = innate; cytotoxic T cell needs prior activation",1),
("Which innate immune cell secretes numerous cytokines to regulate most other immune cells?",["Basophil","Eosinophil","Monocyte","Neutrophil"],[1],"LC35: eosinophil functions = killing parasites + REGULATING IMMUNE CELLS",1),
("Which cell type is the only antigen-presenting cell able to activate naïve T-cells?",["B-cell","Dendritic cell","Monocyte","Macrophage"],[1],"Dendritic cells prime naïve T cells",1),
("In which region of the lymph node would you find the highest concentration of B-cell follicles and germinal centers?",["Hilus","Medulla","Outer cortex","Paracortex"],[2],"Nodules = outer cortex",1),
("What is the predominant lymphocyte type in the paracortex of the lymph node?",["B-cell","Plasma cell","T-cell","NK cell"],[2],"Paracortex = T-cell zone (thymus-dependent)",1),
("Why is it normal for lymphocytes to invade the surface epithelium of the tonsil?",["They are pathologically responding to infection","Tonsils function as antigen-sampling lymphoid tissue","They are circulating to bone marrow","The epithelium is replaced by fibrous tissue"],[1],"",1),
("What is the predominant lymphocyte type within the PALS of the spleen?",["B-cell","Macrophage","Plasma cell","T-cell"],[3],"Periarteriolar lymphoid sheath = T cells",1),
("What is the function of the rod-shaped endothelial cells lining splenic sinusoids?",["Facilitate removal of effete erythrocytes","Release histamine to recruit neutrophils","Secrete antibodies into the circulation","Produce fibrin during inflammation"],[0],"Gaps between rod cells filter out old, stiff RBCs",1),
("Where does negative selection of T-cells occur in the thymus?",["Outer cortex","Inner cortex","Medulla","Subcapsular zone"],[2],"LC37: medullary epithelial cells + dendritic cells delete self-reactive T cells. Positive selection = cortex",1),
]
X2024=[
("Fat deposits in the heart are more likely associated with which heart layer?",["Endocardium","Epicardium","Myocardium"],[1],"Epicardium = mesothelium + CT + fat; coronary vessels run here",1),
("Which is most accurate regarding Purkinje fibers in the heart?",["They are typically concentrated under the epicardium","They have myofibrils that stain eosinophilically","They lack nuclei","They resemble myelinated nerve fibers"],[1],"They sit under the ENDOcardium and have nuclei. Their few myofibrils are pink, pushed to the edges. ⚠️ Not confirmed: ask Dr. Klimek about the 'myelinated nerve fiber' look",0),
("What type of tissue is the tunica adventitia of a muscular artery?",["Dense irregular connective tissue","Dense regular connective tissue","Loose connective tissue"],[2],"LC19: tunica adventitia = loose connective tissue",1),
("What is the major difference between a small muscular artery and an arteriole?",["Diameter of the lumen","Location of the vessel","Presence of vasa vasorum","Thickness of smooth muscle"],[3],"Arteriole = 1–3 smooth muscle layers · artery = more than 3",1),
("Where would you look to identify the vasa vasorum of a large vessel?",["Between muscle cells of the tunica media","In the connective tissue of the tunica adventitia","Under the tunica intima"],[1],"",1),
("Normal dog smear: abundant pale cytoplasm with occasional granules or vacuoles, large euchromatic nucleus of variable shape. Which cell?",["Basophil","Eosinophil","Lymphocyte","Monocyte","Neutrophil"],[3],"Monocyte = big, gray-blue vacuolated cytoplasm, variable (kidney/amoeboid) nucleus",1),
("Which white blood cell type is most involved in fighting viral infections?",["Basophil","Eosinophil","Lymphocyte","Neutrophil"],[2],"",1),
("Which white blood cell type is the most active phagocyte for bacteria?",["Basophil","Eosinophil","Lymphocyte","Neutrophil"],[3],"",1),
("Which circulating cell type is most numerous in normal dogs?",["Band neutrophil","Eosinophil","Lymphocyte","Monocyte","Segmented neutrophil"],[4],"Dogs = neutrophil-predominant (cattle = lymphocyte-predominant)",1),
("Which term applies when you observe red blood cells of various shapes on a blood smear?",["Anemia","Anisocytosis","Neutrophilia","Poikilocytosis","Polychromasia"],[3],"Poikilo = SHAPE · aniso = SIZE",1),
("In adult animals, most bone marrow has few hematopoietic cells and many adipocytes. What is this marrow called?",["Fatty marrow","Mature marrow","Red marrow","Yellow marrow"],[3],"",1),
("Increased M-CSF signaling would tend to increase hematopoiesis of which cell type?",["Erythrocyte","Monocyte","Neutrophil","Thrombocyte"],[1],"M = monocyte/macrophage · G = granulocyte (neutrophil) · EPO = RBC · TPO = platelets",1),
("Which is a correct description of a reticulocyte?",["An immature neutrophil with a U-shaped nucleus and numerous neutral granules","An immature neutrophil with a dented nucleus and identifiable granules","An immature RBC, slightly larger than normal with speckled, slightly basophilic cytoplasm and no biconcave shape","An immature RBC with a heterochromatic, acentric nucleus"],[2],"A = band · B = metamyelocyte · D = metarubricyte",1),
("Anemia with increased MCV, decreased MCHC, and numerous reticulocytes is consistent with:",["Degenerative left shift","Non-regenerative anemia","Regenerative anemia","Regenerative left shift"],[2],"",1),
("Which channel is responsible for the unstable phase 4 current in nodal cardiomyocytes (the funny current)?",["Fast voltage-gated Na⁺ (Nav1.5)","HCN","Slow L-type Ca²⁺ (Cav1.2)","Transient T-type Ca²⁺ (Cav3.1)","Voltage-gated K⁺ (Kv)"],[1],"",1),
("Acetylcholine signaling in nodal cardiomyocytes will cause which? (select ALL that apply)",["Decreased heart rate","Decreased intracellular cAMP","Increased potassium permeability","Increased heart rate","Increased intracellular cAMP"],[0,1,2],"M2 → Gi → ↓cAMP; Gβγ opens K⁺ channels → hyperpolarized, flatter phase 4",1),
("Which antiarrhythmic works by slowing the repolarization of the heart?",["Ivabradine (class 0)","Lidocaine (class 1)","Propranolol (class 2)","Amiodarone (class 3)","Diltiazem (class 4)"],[3],"Class 3 = K⁺ channel blockers → prolong repolarization",1),
("In a standard ECG, where does the black lead go?",["Left forepaw","Left hindpaw","Right forepaw","Right hindpaw"],[0],"White on right · snow over grass · smoke (black) over fire (red) → black = left fore",1),
("Where are the reference and recording electrodes for lead III?",["Ref: left forepaw, Rec: left hindpaw","Ref: left hindpaw, Rec: left forepaw","Ref: right forepaw, Rec: left hindpaw","Ref: right forepaw, Rec: left forepaw"],[0],"Lead I = RF→LF · II = RF→LH · III = LF→LH",1),
("What is the angle of lead III?",["−30°","60°","120°","210°"],[2],"Lead I = 0° · II = 60° · III = 120°",1),
("Which type of granulocyte appears to be important in regulating many other types of immune cells?",["Basophil","Eosinophil","Monocyte","Neutrophil"],[1],"LC35: eosinophils kill parasites AND regulate immune cells",1),
("Which signal is likely to increase the hematopoietic production of eosinophils?",["IL-3","IL-5","G-CSF","M-CSF"],[1],"",1),
("Which cell type is the only type able to activate a naïve T-cell?",["Dendritic cell","Eosinophil","Macrophage","Plasma cell"],[0],"",1),
("Which cell type is the innate immune system equivalent of a Tc-cell?",["Neutrophil","NK cell","Plasma cell","TH-cell"],[1],"",1),
("Which cell type predominates in the germinal center of a lymph nodule?",["B-cell","Plasma cell","TH-cell","TC-cell"],[0],"",1),
("Where would it NOT be pathological to find large numbers of lymphocytes invading the epithelium?",["Appendix","Lymph nodes","Peyer’s patches","Tonsils"],[3],"Hallmark of the tonsil",1),
("Where are nodules located in the lymph node?",["Hilus","Medulla","Outer cortex","Paracortex"],[2],"",1),
("What cell type predominates in the paracortex of the lymph node?",["B-cell","Macrophage","Plasma cell","T-cell"],[3],"",1),
("Which is the main blood flow through the white pulp of the spleen?",["Central arterioles","High endothelial venules","Penicillar arterioles","Splenic cords"],[0],"Central arteriole runs inside the PALS; penicillar arterioles are in the red pulp",1),
("What is the primary cell type found in the PALS?",["B-cell","Macrophage","Plasma cell","T-cell"],[3],"",1),
("What is the function of the rod-shaped endothelial cells in the splenic sinusoids?",["Attract T cells to seed the spleen","Filter effete RBCs","Phagocytose opsonized antigens","Secrete antibodies into the blood"],[1],"",1),
("Where does negative selection occur in the thymus?",["Outer cortex","Inner cortex","Medulla"],[2],"",1),
]
CSS='''*{box-sizing:border-box}body{margin:0;background:#fff9fd;color:#493451;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Arial,sans-serif;line-height:1.45}.wrap{max-width:820px;margin:auto;padding:16px}.back{display:inline-block;margin:0 0 10px;padding:8px 14px;border-radius:999px;background:#f3eafb;color:#65328c;font-weight:800;text-decoration:none}.hero{color:#fff;background:linear-gradient(135deg,#5d347e,#8855b8 55%,#df78ad);padding:20px;border-radius:22px}.hero h1{margin:0;font-size:24px}.hero p{margin:6px 0 0}.bar{display:flex;gap:8px;flex-wrap:wrap;margin:12px 0}.bar button{border:0;border-radius:999px;padding:9px 14px;background:#f3eafb;color:#65328c;font-weight:800;font-size:15px}.score{margin-left:auto;font-weight:900;color:#70428f;align-self:center}.q{background:#fff;border:1px solid #eadff2;border-left:7px solid #7b42a0;border-radius:18px;padding:14px;margin:12px 0}.q h3{margin:0 0 10px;font-size:17px;color:#3b1d66}.q h3 span{font-family:ui-monospace,Menlo,monospace;color:#b0679a;font-size:13px;margin-right:6px}.opt{display:block;width:100%;text-align:left;border:1.5px solid #eadff2;background:#fbf6fe;border-radius:12px;padding:10px 12px;margin:6px 0;font-size:16px;color:#493451}.opt.sel{border-color:#8855b8;background:#efe3fa}.opt.ok{border-color:#3fa77a;background:#e1f5ec}.opt.no{border-color:#e0459a;background:#ffe3ef}.chk{border:0;border-radius:999px;padding:8px 14px;background:#7b42a0;color:#fff;font-weight:800;margin-top:4px}.why{display:none;margin-top:8px;padding:10px 12px;border-radius:12px;background:#fdf2f9;font-size:15px}.q.done .why{display:block}.flag{color:#b35a00;font-weight:800}.note{background:#fff;border:1px dashed #eadff2;border-radius:14px;padding:10px 12px;margin:12px 0;font-size:14px}@media(max-width:600px){.wrap{padding:10px}}'''
JS='''let S=0,N=0;const sc=document.getElementById('sc');function upd(){sc.textContent='✅ '+S+' / '+N}
document.querySelectorAll('.q').forEach(q=>{const multi=q.dataset.m==='1',ans=JSON.parse(q.dataset.a),os=[...q.querySelectorAll('.opt')];
function grade(){if(q.classList.contains('done'))return;q.classList.add('done');let picked=os.map((o,i)=>o.classList.contains('sel')?i:-1).filter(i=>i>=0);os.forEach((o,i)=>{if(ans.includes(i))o.classList.add('ok');else if(o.classList.contains('sel'))o.classList.add('no')});N++;if(picked.length===ans.length&&picked.every(i=>ans.includes(i)))S++;else q.dataset.miss='1';upd()}
os.forEach(o=>o.onclick=()=>{if(q.classList.contains('done'))return;if(multi){o.classList.toggle('sel')}else{os.forEach(x=>x.classList.remove('sel'));o.classList.add('sel');grade()}});const c=q.querySelector('.chk');if(c)c.onclick=grade});
document.getElementById('shuf').onclick=()=>{const w=document.getElementById('qs');[...w.children].sort(()=>Math.random()-.5).forEach(x=>w.appendChild(x))};
document.getElementById('miss').onclick=()=>{document.querySelectorAll('.q').forEach(q=>{q.style.display=q.dataset.miss?'':'none'})};
document.getElementById('all').onclick=()=>{document.querySelectorAll('.q').forEach(q=>q.style.display='')};upd();'''
def page(fn,title,sub,qs,note):
    out=[]
    for i,(stem,opts,ans,why,sure) in enumerate(qs,1):
        m=len(ans)>1 or 'select all' in stem.lower()
        ob=''.join(f'<button class="opt">{chr(65+j)}. {E(o)}</button>' for j,o in enumerate(opts))
        fl='' if sure else '<div class="flag">⚠️ Not 100% sure. Confirm with the instructor.</div>'
        out.append(f'<div class="q" data-a="{json.dumps(ans)}" data-m="{int(m)}"><h3><span>Q{i}</span>{E(stem)}</h3>{ob}{"<button class=chk>Check ✓</button>" if m else ""}<div class="why">✅ <b>{", ".join(chr(65+a) for a in ans)}</b>{" · "+E(why) if why else ""}{fl}</div></div>')
    open(fn,'w').write(f'<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{E(title)}</title><style>{CSS}</style></head><body><div class="wrap"><a class="back" href="systems-lecture.html?v={V}">← Back to Lecture</a><div class="hero"><h1>{E(title)}</h1><p>{E(sub)}</p></div><div class="note">{note}</div><div class="bar"><button id="shuf">🎲 Shuffle</button><button id="miss">🔁 Misses only</button><button id="all">↺ Show all</button><span class="score" id="sc"></span></div><div id="qs">{"".join(out)}</div></div><script>{JS}</script></body></html>')
NOTE='Tap an answer to check it. Select-all questions need ✓ Check. Answers were worked out from the lecture slides (<b>not an official key</b>). ⚠️ = ask before trusting. ECG/figure questions whose image wasn’t in the upload are left out.'
page('systems-lec-old2025.html','📝 Old Lecture Exam · 2025','Cardio electrophysiology & ECG · blood, marrow & hemostasis · defensive cells & lymphatics · '+str(len(X2025))+' Q',X2025,NOTE+' Skipped: Q1–2 (action-potential figure), Q8–11 and Q13–14 (ECG strips A–D).')
page('systems-lec-old2024.html','📝 Old Lecture Exam · 2024','Circulatory microanatomy & blood · hematopoiesis · ECG · defensive cells & lymphatics · '+str(len(X2024))+' Q',X2024,NOTE+' Skipped: section-D action-potential question and ECG strips A–C (4 questions).')
HUB=open('veterinary-systems.html').read()
style=HUB[HUB.index('<style>'):HUB.index('</style>')+8]
open('systems-lecture.html','w').write(f'<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#8855b8"><title>📖 Veterinary Systems I · Lecture</title>{style}</head><body><div class="wrap"><section class="hero"><h1>📖 Veterinary Systems I · Lecture</h1><p>Lecture Exam 3 · Fri 10/16 · Lectures 19–37 + Musch Parts 1–6</p></section><div class="nav"><a href="veterinary-systems.html?v={V}">← Back</a></div><div class="grid"><a class="tile" href="systems-lec-old2025.html?v={V}"><div class="emoji">📝</div><h2>Old Exam · 2025</h2><p>{len(X2025)} tap-to-check questions · ECG, blood, hemostasis, lymphatics</p></a><a class="tile" href="systems-lec-old2024.html?v={V}"><div class="emoji">📝</div><h2>Old Exam · 2024</h2><p>{len(X2024)} tap-to-check questions · vessels, blood, ECG, lymphatics</p></a></div><div class="footer">KSU Vet School Study Mate · Fall 2026</div></div></body></html>')
if 'systems-lecture.html' not in HUB:
    HUB=HUB.replace('<a class="tile" href="systems-lab.html',f'<a class="tile" href="systems-lecture.html?v={V}"><div class="emoji">📖</div><h2>Lecture</h2><p>Exam 3 · old exams for practice</p></a>\n<a class="tile" href="systems-lab.html',1).replace('<p>Lab practicals</p>','<p>Lecture · Lab practicals</p>')
HUB=re.sub(r'systems-lecture\.html\?v=\d+',f'systems-lecture.html?v={V}',HUB)
open('veterinary-systems.html','w').write(HUB)
sw=open('sw.js').read(); open('sw.js','w').write(re.sub(r"ksu-study-mate-v(\d+)-\d+",lambda m:f"ksu-study-mate-v{int(m.group(1))+1}-{V}",sw))
print(len(X2025),len(X2024))
